libuofs3_FILES = ../../Telegraph/TGWebSearchResultsGalleryGifItemView.m \
../../Telegraph/TGWebSearchResultsGalleryImageItem.m \
../../Telegraph/TGWebSearchResultsGalleryImageItemView.m \
../../Telegraph/TGWebSearchResultsGalleryInternalGifItem.m \
../../Telegraph/TGWebSearchResultsGalleryInternalGifItemView.m \
../../Telegraph/TGWebSearchResultsGalleryInternalImageItem.m \
../../Telegraph/TGWebSearchThumbnailDataSource.m \
../../Telegraph/TGWebpageFooterModel.m \
../../Telegraph/TGWebpageSignals.m \
../../Telegraph/TGWorker.m \
../../Telegraph/TGWorkerPool.m \
../../Telegraph/TGWorkerTask.m \
../../Telegraph/TGYoutubeContentPropertiesActor.m \
../../Telegraph/TGYoutubeDataContentProperty.m \
../../Telegraph/TLBotInlineMessage_botInlineMessageMediaAuto.mm \
../../Telegraph/TLBotInlineMessage_botInlineMessageMediaContact.mm \
../../Telegraph/TLBotInlineMessage_botInlineMessageMediaGeo.mm \
../../Telegraph/TLBotInlineMessage_botInlineMessageMediaVenue.mm \
../../Telegraph/TLBotInlineMessage_botInlineMessageText.mm \
../../Telegraph/TLBotInlineResult_botInlineMediaResult.mm \
../../Telegraph/TLBotInlineResult_botInlineResult.mm \
../../Telegraph/TLChat_channel.mm \
../../Telegraph/TLChat_channelForbidden.mm \
../../Telegraph/TLChat_chat.mm \
../../Telegraph/TLChatFull_channelFull.mm \
../../Telegraph/TLChatInvite_chatInvite.mm \
../../Telegraph/TLChatParticipants_chatParticipantsForbidden.mm \
../../Telegraph/TLConfig_config.mm \
../../Telegraph/TLDcOption_modernDcOption.mm \
../../Telegraph/TLDialog_dialog.mm \
../../Telegraph/TLDialog_dialogFeed.mm \
../../Telegraph/TLDocumentAttribute_documentAttributeAudio.m \
../../Telegraph/TLDocumentAttributeSticker.mm \
../../Telegraph/TLDraftMessage_draftMessage.mm \
../../Telegraph/TLGame_game.mm \
../../Telegraph/TLInputMediaUploadedDocument.mm \
../../Telegraph/TLInputMediaUploadedPhoto.mm \
../../Telegraph/TLInputPeerNotifySettings_inputPeerNotifySettings.mm \
../../Telegraph/TLInputSecureValue_inputSecureValue.mm \
../../Telegraph/TLInputSingleMedia_inputSingleMedia.mm \
../../Telegraph/TLInvoice_invoice.mm \
../../Telegraph/TLLangPackStringPluralized.m \
../../Telegraph/TLMessage_modernMessage.mm \
../../Telegraph/TLMessage_modernMessageService.mm \
../../Telegraph/TLMessageAction_messageActionPhoneCall.mm \
../../Telegraph/TLMessageFwdHeader_messageFwdHeader.mm \
../../Telegraph/TLMessageMedia_messageMediaDocument.mm \
../../Telegraph/TLMessageMedia_messageMediaInvoice.mm \
../../Telegraph/TLMessageMedia_messageMediaPhoto.mm \
../../Telegraph/TLMessages_BotResults_botResults.mm \
../../Telegraph/TLPageBlock_pageBlockEmbed.mm \
../../Telegraph/TLPaymentRequestedInfo_paymentRequestedInfo.mm \
../../Telegraph/TLPayments_PaymentCeceipt_payments_paymentReceipt.mm \
../../Telegraph/TLPayments_sendPaymentForm.mm \
../../Telegraph/TLPeerNotifySettings_peerNotifySettings.mm \
../../Telegraph/TLPhoneCall_phoneCallDiscarded.mm \
../../Telegraph/TLPhoneCall_phoneCallWaiting.mm \
../../Telegraph/TLRPCaccount_acceptAuthorization.mm \
../../Telegraph/TLRPCaccount_deleteSecureValue.mm \
../../Telegraph/TLRPCaccount_getAllSecureValues.mm \
../../Telegraph/TLRPCaccount_getAuthorizationForm.mm \
../../Telegraph/TLRPCaccount_getSecureValue.mm \
../../Telegraph/TLRPCaccount_saveSecureValue.mm \
../../Telegraph/TLRPCaccount_sendChangePhoneCode.mm \
../../Telegraph/TLRPCaccount_sendConfirmPhoneCode.m \
../../Telegraph/TLRPCaccount_sendVerifyEmailCode.mm \
../../Telegraph/TLRPCaccount_sendVerifyPhoneCode.mm \
../../Telegraph/TLRPCaccount_verifyEmail.mm \
../../Telegraph/TLRPCaccount_verifyPhone.mm \
../../Telegraph/TLRPCauth_sendCode.mm \
../../Telegraph/TLRPCchannels_changeFeedBroadcast.mm \
../../Telegraph/TLRPCchannels_getAdminLog.mm \
../../Telegraph/TLRPCchannels_getFeed.mm \
../../Telegraph/TLRPCchannels_getFeedSources.mm \
../../Telegraph/TLRPCchannels_readFeed.mm \
../../Telegraph/TLRPCchannels_setFeedBroadcasts.mm \
../../Telegraph/TLRPCcontacts_toggleTopPeers.mm \
../../Telegraph/TLRPChelp_acceptTermsOfService.mm \
../../Telegraph/TLRPChelp_getDeepLinkInfo.mm \
../../Telegraph/TLRPChelp_getPassportConfig.mm \
../../Telegraph/TLRPChelp_getProxyData.m \
../../Telegraph/TLRPChelp_getTermsOfServiceUpdate.mm \
../../Telegraph/TLRPCmessages_clearAllDrafts.mm \
../../Telegraph/TLRPCmessages_editGeoLive.mm \
../../Telegraph/TLRPCmessages_editMessage.mm \
../../Telegraph/TLRPCmessages_forwardMessages.mm \
../../Telegraph/TLRPCmessages_getBotCallbackAnswer.mm \
../../Telegraph/TLRPCmessages_getDialogUnreadMarks.mm \
../../Telegraph/TLRPCmessages_getDialogs.mm \
../../Telegraph/TLRPCmessages_getInlineBotResults.mm \
../../Telegraph/TLRPCmessages_markDialogUnread.mm \
../../Telegraph/TLRPCmessages_report.mm \
../../Telegraph/TLRPCmessages_saveDraft.mm \
../../Telegraph/TLRPCmessages_search.mm \
../../Telegraph/TLRPCmessages_searchStickerSets.mm \
../../Telegraph/TLRPCmessages_sendInlineBotResult.mm \
../../Telegraph/TLRPCmessages_sendMultiMedia.mm \
../../Telegraph/TLSecureValue_secureValue.mm \
../../Telegraph/TLStickerSet_stickerSet.mm \
../../Telegraph/TLUpdate_updateChannelTooLong.m \
../../Telegraph/TLUpdate_updatePinnedDialogs.mm \
../../Telegraph/TLUpdate_updateReadFeed.mm \
../../Telegraph/TLUpdate_updateServiceNotification.mm \
../../Telegraph/TLUpdates_modernUpdateShortChatMessage.mm \
../../Telegraph/TLUpdates_modernUpdateShortMessage.mm \
../../Telegraph/TLUpdates_updateShortSentMessage.mm \
../../Telegraph/TLUpdates+TG.m \
../../Telegraph/TLUpdates_ChannelDifference_manual.mm \
../../Telegraph/TLUser_modernUser.mm \
../../Telegraph/TLUserFull_userFull.mm \
../../Telegraph/TLWebPage_webPageExternal.mm \
../../Telegraph/TLWebPage_manual.mm \
../../Telegraph/TLaccount_AuthorizationForm_account_authorizationForm.mm \
../../Telegraph/TLaccount_Password_account_password.mm \
../../Telegraph/TLaccount_PasswordSettings_account_passwordSettings.mm \
../../Telegraph/TLaccount_updateProfile_updateProfile.m \
../../Telegraph/TLauth_Authorization_auth_authorization.mm \
../../Telegraph/TLauth_SentCode_auth_sentCode.mm \
../../Telegraph/TLchannelDifferenceTooLong.mm \
../../Telegraph/TLchannels_FeedSources_channels_feedSources.mm \
../../Telegraph/TLhelp_AppUpdate_help_appUpdate.mm \
../../Telegraph/TLhelp_DeepLinkInfo_help_deepLinkInfo.mm \
../../Telegraph/TLhelp_ProxyData.mm \
../../Telegraph/TLhelp_TermsOfService_help_termsOfService.mm \
../../Telegraph/TLmessages_BotCallbackAnswer_botCallbackAnswer.mm \
../../Telegraph/TLmessages_FeedMessages_messages_feedMessages.mm \
../../Telegraph/TLmessages_Messages_modernChannelMessages.mm \
../../Telegraph/TLpayments_PaymentForm_payments_paymentForm.mm \
../../Telegraph/TLpayments_SavedInfo_payments_savedInfo.mm \
../../Telegraph/TLpayments_ValidatedRequestedInfo_payments_validatedRequestedInfo.mm \
../../Telegraph/TransformImageView.m \
../../Telegraph/UIViewController+Proxy.m \
../../Telegraph/emoji_suggestions.cpp \
../../Telegraph/emoji_suggestions_data.cpp \
../../Telegraph/main.m \
../../Telegraph/quaternion.cpp \
../../Telegraph/thirdparty/diag_range.c \
../../Telegraph/thirdparty/ogg/ogg/bitwise.c \
../../Telegraph/thirdparty/ogg/ogg/framing.c \
../../Telegraph/thirdparty/opus_header.c \
../../Telegraph/thirdparty/opusenc.m \
../../Telegraph/thirdparty/opusenc/picture.c \
../../Telegraph/thirdparty/opusenc/wav_io.c \
../../Telegraph/thirdparty/opusfile/info.c \
../../Telegraph/thirdparty/opusfile/internal.c \
../../Telegraph/thirdparty/opusfile/opusfile.c \
../../Telegraph/thirdparty/opusfile/stream.c \
../../Watch/Bridge/TGBridgeActionMediaAttachment+TGActionMediaAttachment.m \
../../Watch/Bridge/TGBridgeActionMediaAttachment.m \
../../Watch/Bridge/TGBridgeAudioMediaAttachment+TGAudioMediaAttachment.m \
../../Watch/Bridge/TGBridgeAudioMediaAttachment.m \
../../Watch/Bridge/TGBridgeAudioSubscription.m \
../../Watch/Bridge/TGBridgeBotCommandInfo+TGBotCommandInfo.m \
../../Watch/Bridge/TGBridgeBotCommandInfo.m \
../../Watch/Bridge/TGBridgeBotInfo+TGBotInfo.m \
../../Watch/Bridge/TGBridgeBotInfo.m \
../../Watch/Bridge/TGBridgeBotReplyMarkup+TGBotReplyMarkup.m \
../../Watch/Bridge/TGBridgeBotReplyMarkup.m \
../../Watch/Bridge/TGBridgeChat+TGConversation.m \
../../Watch/Bridge/TGBridgeChat.m \
../../Watch/Bridge/TGBridgeChatListSubscription.m \
../../Watch/Bridge/TGBridgeChatMessageListSubscription.m \
../../Watch/Bridge/TGBridgeChatMessageListView+TGChatMessageListView.m \
../../Watch/Bridge/TGBridgeChatMessageListView.m \
../../Watch/Bridge/TGBridgeCommon.m \
../../Watch/Bridge/TGBridgeContactMediaAttachment+TGContactMediaAttachment.m \
../../Watch/Bridge/TGBridgeContactMediaAttachment.m \
../../Watch/Bridge/TGBridgeContactsSubscription.m \
../../Watch/Bridge/TGBridgeContext.m \
../../Watch/Bridge/TGBridgeConversationSubscription.m \
../../Watch/Bridge/TGBridgeDocumentMediaAttachment+TGDocumentMediaAttachment.m \
../../Watch/Bridge/TGBridgeDocumentMediaAttachment.m \
../../Watch/Bridge/TGBridgeForwardedMessageMediaAttachment+TGForwardedMessageMediaAttachment.m \
../../Watch/Bridge/TGBridgeForwardedMessageMediaAttachment.m \
../../Watch/Bridge/TGBridgeImageInfo+TGImageInfo.m \
../../Watch/Bridge/TGBridgeImageInfo.m \
../../Watch/Bridge/TGBridgeImageMediaAttachment+TGImageMediaAttachment.m \
../../Watch/Bridge/TGBridgeImageMediaAttachment.m \
../../Watch/Bridge/TGBridgeLocationMediaAttachment+TGLocationMediaAttachment.m \
../../Watch/Bridge/TGBridgeLocationMediaAttachment.m \
../../Watch/Bridge/TGBridgeLocationSubscription.m \
../../Watch/Bridge/TGBridgeLocationVenue+TGLocationVenue.m \
../../Watch/Bridge/TGBridgeLocationVenue.m \
../../Watch/Bridge/TGBridgeMediaAttachment+TGMediaAttachment.m \
../../Watch/Bridge/TGBridgeMediaAttachment.m \
../../Watch/Bridge/TGBridgeMediaSubscription.m \
../../Watch/Bridge/TGBridgeMessage+TGMessage.m \
../../Watch/Bridge/TGBridgeMessage.m \
../../Watch/Bridge/TGBridgeMessageEntities.m \
../../Watch/Bridge/TGBridgeMessageEntitiesAttachment+TGMessageEntitiesAttachment.m \
../../Watch/Bridge/TGBridgeMessageEntitiesAttachment.m \
../../Watch/Bridge/TGBridgeMessageEntity+TGMessageEntity.m \
../../Watch/Bridge/TGBridgePeerNotificationSettings+TGPeerNotificationSettings.m \
../../Watch/Bridge/TGBridgePeerNotificationSettings.m \
../../Watch/Bridge/TGBridgePeerSettingsSubscription.m \
../../Watch/Bridge/TGBridgeRemoteSubscription.m \
../../Watch/Bridge/TGBridgeReplyMarkupMediaAttachment+TGReplyMarkupAttachment.m \
../../Watch/Bridge/TGBridgeReplyMarkupMediaAttachment.m \
../../Watch/Bridge/TGBridgeReplyMessageMediaAttachment+TGReplyMessageMediaAttachment.m \
../../Watch/Bridge/TGBridgeReplyMessageMediaAttachment.m \
../../Watch/Bridge/TGBridgeResponse.m \
../../Watch/Bridge/TGBridgeSendMessageSubscription.m \
../../Watch/Bridge/TGBridgeStateSubscription.m \
../../Watch/Bridge/TGBridgeStickerPack+TGStickerPack.m \
../../Watch/Bridge/TGBridgeStickerPack.m \
../../Watch/Bridge/TGBridgeStickersSubscription.m \
../../Watch/Bridge/TGBridgeSubscription.m \
../../Watch/Bridge/TGBridgeUnsupportedMediaAttachment+TGUnsupportedMediaAttachment.m \
../../Watch/Bridge/TGBridgeUnsupportedMediaAttachment.m \
../../Watch/Bridge/TGBridgeUser+TGUser.m \
../../Watch/Bridge/TGBridgeUser.m \
../../Watch/Bridge/TGBridgeUserInfoSubscription.m \
../../Watch/Bridge/TGBridgeVideoMediaAttachment+TGVideoMediaAttachment.m \
../../Watch/Bridge/TGBridgeVideoMediaAttachment.m \
../../Watch/Bridge/TGBridgeWebPageMediaAttachment+TGWebPageMediaAttachment.m \
../../Watch/Bridge/TGBridgeWebPageMediaAttachment.m \
../../legacy/TL/MtProtoKit_Legacy.m \
../../legacy/TL/NSData+GZip.m \
../../legacy/TL/NSInputStream+TL.m \
../../legacy/TL/NSOutputStream+TL.m \
../../legacy/TL/TGZeroOutputStream.m \
../../legacy/TL/TL/NSArray_Authorization.mm \
../../legacy/TL/TL/NSArray_BotCommand.mm \
../../legacy/TL/TL/NSArray_BotInfo.mm \
../../legacy/TL/TL/NSArray_BotInlineResult.mm \
../../legacy/TL/TL/NSArray_CdnPublicKey.mm \
../../legacy/TL/TL/NSArray_ChannelAdminLogEvent.mm \
../../legacy/TL/TL/NSArray_ChannelParticipant.mm \
../../legacy/TL/TL/NSArray_Chat.mm \
../../legacy/TL/TL/NSArray_ChatParticipant.mm \
../../legacy/TL/TL/NSArray_Contact.mm \
../../legacy/TL/TL/NSArray_ContactBlocked.mm \
../../legacy/TL/TL/NSArray_ContactLocated.mm \
../../legacy/TL/TL/NSArray_ContactRequest.mm \
../../legacy/TL/TL/NSArray_ContactStatus.mm \
../../legacy/TL/TL/NSArray_ContactSuggested.mm \
../../legacy/TL/TL/NSArray_DcNetworkStats.mm \
../../legacy/TL/TL/NSArray_DcOption.mm \
../../legacy/TL/TL/NSArray_DestroySessionRes.mm \
../../legacy/TL/TL/NSArray_Dialog.mm \
../../legacy/TL/TL/NSArray_DisabledFeature.mm \
../../legacy/TL/TL/NSArray_Document.mm \
../../legacy/TL/TL/NSArray_DocumentAttribute.mm \
../../legacy/TL/TL/NSArray_EncryptedMessage.mm \
../../legacy/TL/TL/NSArray_FileHash.mm \
../../legacy/TL/TL/NSArray_FoundGif.mm \
../../legacy/TL/TL/NSArray_HighScore.mm \
../../legacy/TL/TL/NSArray_ImportedContact.mm \
../../legacy/TL/TL/NSArray_InputChannel.mm \
../../legacy/TL/TL/NSArray_InputContact.mm \
../../legacy/TL/TL/NSArray_InputDocument.mm \
../../legacy/TL/TL/NSArray_InputPeer.mm \
../../legacy/TL/TL/NSArray_InputPhoto.mm \
../../legacy/TL/TL/NSArray_InputPrivacyRule.mm \
../../legacy/TL/TL/NSArray_InputUser.mm \
../../legacy/TL/TL/NSArray_KeyboardButton.mm \
../../legacy/TL/TL/NSArray_KeyboardButtonRow.mm \
../../legacy/TL/TL/NSArray_LabeledPrice.mm \
../../legacy/TL/TL/NSArray_LangPackLanguage.mm \
../../legacy/TL/TL/NSArray_LangPackString.mm \
../../legacy/TL/TL/NSArray_Message.mm \
../../legacy/TL/TL/NSArray_MessageEntity.mm \
../../legacy/TL/TL/NSArray_MessageRange.mm \
../../legacy/TL/TL/NSArray_PageBlock.mm \
../../legacy/TL/TL/NSArray_Peer.mm \
../../legacy/TL/TL/NSArray_PhoneConnection.mm \
../../legacy/TL/TL/NSArray_Photo.mm \
../../legacy/TL/TL/NSArray_PhotoSize.mm \
../../legacy/TL/TL/NSArray_PopularContact.mm \
../../legacy/TL/TL/NSArray_PrivacyRule.mm \
../../legacy/TL/TL/NSArray_ReceivedNotifyMessage.mm \
../../legacy/TL/TL/NSArray_RichText.mm \
../../legacy/TL/TL/NSArray_SchemeMethod.mm \
../../legacy/TL/TL/NSArray_SchemeParam.mm \
../../legacy/TL/TL/NSArray_SchemeType.mm \
../../legacy/TL/TL/NSArray_SecureValue.mm \
../../legacy/TL/TL/NSArray_ShippingOption.mm \
../../legacy/TL/TL/NSArray_StickerPack.mm \
../../legacy/TL/TL/NSArray_StickerSet.mm \
../../legacy/TL/TL/NSArray_StickerSetCovered.mm \
../../legacy/TL/TL/NSArray_TopPeer.mm \
../../legacy/TL/TL/NSArray_TopPeerCategoryPeers.mm \
../../legacy/TL/TL/NSArray_Update.mm \
../../legacy/TL/TL/NSArray_User.mm \
../../legacy/TL/TL/NSArray_WallPaper.mm \
../../legacy/TL/TL/NSArray_int.mm \
../../legacy/TL/TL/NSArray_long.mm \
../../legacy/TL/TL/NSArray_string.mm \
../../legacy/TL/TL/TLAccountDaysTTL.mm \
../../legacy/TL/TL/TLAuthorization.mm \
../../legacy/TL/TL/TLBadMsgNotification.mm \
../../legacy/TL/TL/TLBotCommand.mm \
../../legacy/TL/TL/TLBotInfo.mm \
../../legacy/TL/TL/TLBotInlineMessage.mm \
../../legacy/TL/TL/TLBotInlineResult.mm \
../../legacy/TL/TL/TLCdnConfig.mm \
../../legacy/TL/TL/TLCdnPublicKey.mm \
../../legacy/TL/TL/TLChannelAdminLogEvent.mm \
../../legacy/TL/TL/TLChannelAdminLogEventAction.mm \
../../legacy/TL/TL/TLChannelAdminLogEventsFilter.mm \
../../legacy/TL/TL/TLChannelAdminRights.mm \
../../legacy/TL/TL/TLChannelBannedRights.mm \
../../legacy/TL/TL/TLChannelMessagesFilter.mm \
../../legacy/TL/TL/TLChannelParticipant.mm \
../../legacy/TL/TL/TLChannelParticipantsFilter.mm \
../../legacy/TL/TL/TLChat.mm \
../../legacy/TL/TL/TLChatFull.mm \
../../legacy/TL/TL/TLChatInvite.mm \
../../legacy/TL/TL/TLChatLocated.mm \
../../legacy/TL/TL/TLChatParticipant.mm \
../../legacy/TL/TL/TLChatParticipants.mm \
../../legacy/TL/TL/TLChatPhoto.mm \
../../legacy/TL/TL/TLClient_DH_Inner_Data.mm \
../../legacy/TL/TL/TLConfig.mm \
../../legacy/TL/TL/TLContact.mm \
../../legacy/TL/TL/TLContactBlocked.mm \
../../legacy/TL/TL/TLContactLink.mm \
../../legacy/TL/TL/TLContactLocated.mm \
../../legacy/TL/TL/TLContactRequest.mm \
../../legacy/TL/TL/TLContactStatus.mm \
../../legacy/TL/TL/TLContactSuggested.mm \
../../legacy/TL/TL/TLDataJSON.mm \
../../legacy/TL/TL/TLDcNetworkStats.mm \
../../legacy/TL/TL/TLDcOption.mm \
../../legacy/TL/TL/TLDestroySessionRes.mm \
../../legacy/TL/TL/TLDestroySessionsRes.mm \
../../legacy/TL/TL/TLDialog.mm \
../../legacy/TL/TL/TLDialogPeer.mm \
../../legacy/TL/TL/TLDisabledFeature.mm \
../../legacy/TL/TL/TLDocument.mm \
../../legacy/TL/TL/TLDocumentAttribute.mm \
../../legacy/TL/TL/TLDraftMessage.mm \
../../legacy/TL/TL/TLEmbedPostMedia.mm \
../../legacy/TL/TL/TLEncryptedChat.mm \
../../legacy/TL/TL/TLEncryptedFile.mm \
../../legacy/TL/TL/TLEncryptedMessage.mm \
../../legacy/TL/TL/TLError.mm \
../../legacy/TL/TL/TLExportedChatInvite.mm \
../../legacy/TL/TL/TLExportedMessageLink.mm \
../../legacy/TL/TL/TLFeedBroadcasts.mm \
../../legacy/TL/TL/TLFeedPosition.mm \
../../legacy/TL/TL/TLFileHash.mm \
../../legacy/TL/TL/TLFileLocation.mm \
../../legacy/TL/TL/TLFoundGif.mm \
../../legacy/TL/TL/TLFutureSalt.mm \
../../legacy/TL/TL/TLGame.mm \
../../legacy/TL/TL/TLGeoPlaceName.mm \
../../legacy/TL/TL/TLGeoPoint.mm \
../../legacy/TL/TL/TLGlobalPrivacySettings.mm \
../../legacy/TL/TL/TLHighScore.mm \
../../legacy/TL/TL/TLHttpWait.mm \
../../legacy/TL/TL/TLImportedContact.mm \
../../legacy/TL/TL/TLInitConnection.mm \
../../legacy/TL/TL/TLInlineBotSwitchPM.mm \
../../legacy/TL/TL/TLInputBotInlineMessage.mm \
../../legacy/TL/TL/TLInputBotInlineResult.mm \
../../legacy/TL/TL/TLInputChannel.mm \
../../legacy/TL/TL/TLInputChatPhoto.mm \
../../legacy/TL/TL/TLInputCheckPasswordSRP.mm \
../../legacy/TL/TL/TLInputContact.mm \
../../legacy/TL/TL/TLInputDialogPeer.mm \
../../legacy/TL/TL/TLInputDocument.mm \
../../legacy/TL/TL/TLInputEncryptedChat.mm \
../../legacy/TL/TL/TLInputEncryptedFile.mm \
../../legacy/TL/TL/TLInputFile.mm \
../../legacy/TL/TL/TLInputFileLocation.mm \
../../legacy/TL/TL/TLInputGame.mm \
../../legacy/TL/TL/TLInputGeoPlaceName.mm \
../../legacy/TL/TL/TLInputGeoPoint.mm \
../../legacy/TL/TL/TLInputMedia.mm \
../../legacy/TL/TL/TLInputNotifyPeer.mm \
../../legacy/TL/TL/TLInputPaymentCredentials.mm \
../../legacy/TL/TL/TLInputPeer.mm \
../../legacy/TL/TL/TLInputPeerNotifySettings.mm \
../../legacy/TL/TL/TLInputPhoneCall.mm \
../../legacy/TL/TL/TLInputPhoto.mm \
../../legacy/TL/TL/TLInputPhotoCrop.mm \
../../legacy/TL/TL/TLInputPrivacyKey.mm \
../../legacy/TL/TL/TLInputPrivacyRule.mm \
../../legacy/TL/TL/TLInputSecureFile.mm \
../../legacy/TL/TL/TLInputSecureValue.mm \
../../legacy/TL/TL/TLInputSingleMedia.mm \
../../legacy/TL/TL/TLInputStickerSet.mm \
../../legacy/TL/TL/TLInputStickeredMedia.mm \
../../legacy/TL/TL/TLInputUser.mm \
../../legacy/TL/TL/TLInputWebDocument.mm \
../../legacy/TL/TL/TLInputWebFileLocation.mm \
../../legacy/TL/TL/TLInvoice.mm \
../../legacy/TL/TL/TLInvokeAfterMsg.mm \
../../legacy/TL/TL/TLKeyboardButton.mm \
../../legacy/TL/TL/TLKeyboardButtonRow.mm \
../../legacy/TL/TL/TLLabeledPrice.mm \
../../legacy/TL/TL/TLLangPackDifference.mm \
../../legacy/TL/TL/TLLangPackLanguage.mm \
../../legacy/TL/TL/TLLangPackString.mm \
../../legacy/TL/TL/TLMaskCoords.mm \
../../legacy/TL/TL/TLMessage.mm \
../../legacy/TL/TL/TLMessageAction.mm \
../../legacy/TL/TL/TLMessageEntity.mm \
../../legacy/TL/TL/TLMessageFwdHeader.mm \
../../legacy/TL/TL/TLMessageGroup.mm \
../../legacy/TL/TL/TLMessageMedia.mm \
../../legacy/TL/TL/TLMessageRange.mm \
../../legacy/TL/TL/TLMessagesFilter.mm \
../../legacy/TL/TL/TLMetaClassStore.mm \
../../legacy/TL/TL/TLMetaScheme.mm \
../../legacy/TL/TL/TLMetaSchemeData.mm \
../../legacy/TL/TL/TLMsgDetailedInfo.mm \
../../legacy/TL/TL/TLMsgResendReq.mm \
../../legacy/TL/TL/TLMsgsAck.mm \
../../legacy/TL/TL/TLMsgsAllInfo.mm \
../../legacy/TL/TL/TLMsgsStateInfo.mm \
../../legacy/TL/TL/TLMsgsStateReq.mm \
../../legacy/TL/TL/TLNearestDc.mm \
../../legacy/TL/TL/TLNewSession.mm \
../../legacy/TL/TL/TLNotifyPeer.mm \
../../legacy/TL/TL/TLP_Q_inner_data.mm \
../../legacy/TL/TL/TLPage.mm \
../../legacy/TL/TL/TLPageBlock.mm \
../../legacy/TL/TL/TLPasswordKdfAlgo.mm \
../../legacy/TL/TL/TLPaymentRequestedInfo.mm \
../../legacy/TL/TL/TLPaymentSavedCredentials.mm \
../../legacy/TL/TL/TLPeer.mm \
../../legacy/TL/TL/TLPeerNotifySettings.mm \
../../legacy/TL/TL/TLPeerSettings.mm \
../../legacy/TL/TL/TLPhoneCall.mm \
../../legacy/TL/TL/TLPhoneCallDiscardReason.mm \
../../legacy/TL/TL/TLPhoneCallProtocol.mm \
../../legacy/TL/TL/TLPhoneConnection.mm \
../../legacy/TL/TL/TLPhoto.mm \
../../legacy/TL/TL/TLPhotoSize.mm \
../../legacy/TL/TL/TLPong.mm \
../../legacy/TL/TL/TLPopularContact.mm \
../../legacy/TL/TL/TLPostAddress.mm \
../../legacy/TL/TL/TLPrivacyKey.mm \
../../legacy/TL/TL/TLPrivacyRule.mm \
../../legacy/TL/TL/TLProtoMessage.mm \
../../legacy/TL/TL/TLProtoMessageCopy.mm \
../../legacy/TL/TL/TLRPCaccount_changePhone.mm \
../../legacy/TL/TL/TLRPCaccount_checkUsername.mm \
../../legacy/TL/TL/TLRPCaccount_confirmPhone.mm \
../../legacy/TL/TL/TLRPCaccount_deleteAccount.mm \
../../legacy/TL/TL/TLRPCaccount_getAccountTTL.mm \
../../legacy/TL/TL/TLRPCaccount_getAuthorizations.mm \
../../legacy/TL/TL/TLRPCaccount_getNotifySettings.mm \
../../legacy/TL/TL/TLRPCaccount_getPassword.mm \
../../legacy/TL/TL/TLRPCaccount_getPasswordSettings.mm \
../../legacy/TL/TL/TLRPCaccount_getPrivacy.mm \
../../legacy/TL/TL/TLRPCaccount_getTmpPassword.mm \
../../legacy/TL/TL/TLRPCaccount_getWallPapers.mm \
../../legacy/TL/TL/TLRPCaccount_getWebAuthorizations.mm \
../../legacy/TL/TL/TLRPCaccount_registerDevice.mm \
../../legacy/TL/TL/TLRPCaccount_reportPeer.mm \
../../legacy/TL/TL/TLRPCaccount_resetAuthorization.mm \
../../legacy/TL/TL/TLRPCaccount_resetNotifySettings.mm \
../../legacy/TL/TL/TLRPCaccount_resetWebAuthorization.mm \
../../legacy/TL/TL/TLRPCaccount_resetWebAuthorizations.mm \
../../legacy/TL/TL/TLRPCaccount_setAccountTTL.mm \
../../legacy/TL/TL/TLRPCaccount_setPassword.mm \
../../legacy/TL/TL/TLRPCaccount_setPrivacy.mm \
../../legacy/TL/TL/TLRPCaccount_unregisterDevice.mm \
../../legacy/TL/TL/TLRPCaccount_updateDeviceLocked.mm \
../../legacy/TL/TL/TLRPCaccount_updateNotifySettings.mm \
../../legacy/TL/TL/TLRPCaccount_updatePasswordSettings.mm \
../../legacy/TL/TL/TLRPCaccount_updateStatus.mm \
../../legacy/TL/TL/TLRPCaccount_updateUsername.mm \
../../legacy/TL/TL/TLRPCauth_cancelCode.mm \
../../legacy/TL/TL/TLRPCauth_checkPassword.mm \
../../legacy/TL/TL/TLRPCauth_checkPhone.mm \
../../legacy/TL/TL/TLRPCauth_exportAuthorization.mm \
../../legacy/TL/TL/TLRPCauth_importAuthorization.mm \
../../legacy/TL/TL/TLRPCauth_logOut.mm \
../../legacy/TL/TL/TLRPCauth_recoverPassword.mm \
../../legacy/TL/TL/TLRPCauth_requestPasswordRecovery.mm \
../../legacy/TL/TL/TLRPCauth_resendCode.mm \
../../legacy/TL/TL/TLRPCauth_resetAccountPassword.mm \
../../legacy/TL/TL/TLRPCauth_resetAuthorizations.mm \
../../legacy/TL/TL/TLRPCauth_sendInvites.mm \
../../legacy/TL/TL/TLRPCauth_signIn.mm \
../../legacy/TL/TL/TLRPCauth_signUp.mm \
../../legacy/TL/TL/TLRPCchannels_checkUsername.mm \
../../legacy/TL/TL/TLRPCchannels_createChannel.mm \
../../legacy/TL/TL/TLRPCchannels_deleteChannel.mm \
../../legacy/TL/TL/TLRPCchannels_deleteHistory.mm \
../../legacy/TL/TL/TLRPCchannels_deleteMessages.mm \
../../legacy/TL/TL/TLRPCchannels_deleteUserHistory.mm \
../../legacy/TL/TL/TLRPCchannels_editAbout.mm \
../../legacy/TL/TL/TLRPCchannels_editAdmin.mm \
../../legacy/TL/TL/TLRPCchannels_editBanned.mm \
../../legacy/TL/TL/TLRPCchannels_editPhoto.mm \
../../legacy/TL/TL/TLRPCchannels_editTitle.mm \
../../legacy/TL/TL/TLRPCchannels_exportInvite.mm \
../../legacy/TL/TL/TLRPCchannels_exportMessageLink.mm \
../../legacy/TL/TL/TLRPCchannels_getAdminLogMeta.mm \
../../legacy/TL/TL/TLRPCchannels_getAdminedPublicChannels.mm \
../../legacy/TL/TL/TLRPCchannels_getChannels.mm \
../../legacy/TL/TL/TLRPCchannels_getFullChannel.mm \
../../legacy/TL/TL/TLRPCchannels_getMessages.mm \
../../legacy/TL/TL/TLRPCchannels_getParticipant.mm \
../../legacy/TL/TL/TLRPCchannels_getParticipants.mm \
../../legacy/TL/TL/TLRPCchannels_inviteToChannel.mm \
../../legacy/TL/TL/TLRPCchannels_joinChannel.mm \
../../legacy/TL/TL/TLRPCchannels_leaveChannel.mm \
../../legacy/TL/TL/TLRPCchannels_readHistory.mm \
../../legacy/TL/TL/TLRPCchannels_readMessageContents.mm \
../../legacy/TL/TL/TLRPCchannels_reportSpam.mm \
../../legacy/TL/TL/TLRPCchannels_searchFeed.mm \
../../legacy/TL/TL/TLRPCchannels_setStickers.mm \
../../legacy/TL/TL/TLRPCchannels_toggleInvites.mm \
../../legacy/TL/TL/TLRPCchannels_togglePreHistoryHidden.mm \
../../legacy/TL/TL/TLRPCchannels_toggleSignatures.mm \
../../legacy/TL/TL/TLRPCchannels_updatePinnedMessage.mm \
../../legacy/TL/TL/TLRPCchannels_updateUsername.mm \
../../legacy/TL/TL/TLRPCcontacts_acceptRequest.mm \
../../legacy/TL/TL/TLRPCcontacts_block.mm \
../../legacy/TL/TL/TLRPCcontacts_clearContact.mm \
../../legacy/TL/TL/TLRPCcontacts_declineRequest.mm \
../../legacy/TL/TL/TLRPCcontacts_deleteContact.mm \
../../legacy/TL/TL/TLRPCcontacts_deleteContacts.mm \
../../legacy/TL/TL/TLRPCcontacts_getBlocked.mm \
../../legacy/TL/TL/TLRPCcontacts_getContactIDs.mm \
../../legacy/TL/TL/TLRPCcontacts_getContacts.mm \
../../legacy/TL/TL/TLRPCcontacts_getLink.mm \
../../legacy/TL/TL/TLRPCcontacts_getLocated.mm \
../../legacy/TL/TL/TLRPCcontacts_getRequests.mm \
../../legacy/TL/TL/TLRPCcontacts_getStatuses.mm \
../../legacy/TL/TL/TLRPCcontacts_getSuggested.mm \
../../legacy/TL/TL/TLRPCcontacts_getTopPeers.mm \
../../legacy/TL/TL/TLRPCcontacts_importContacts.mm \
../../legacy/TL/TL/TLRPCcontacts_resetSaved.mm \
../../legacy/TL/TL/TLRPCcontacts_resetTopPeerRating.mm \
../../legacy/TL/TL/TLRPCcontacts_resolveUsername.mm \
../../legacy/TL/TL/TLRPCcontacts_search.mm \
../../legacy/TL/TL/TLRPCcontacts_sendRequest.mm \
../../legacy/TL/TL/TLRPCcontacts_unblock.mm \
../../legacy/TL/TL/TLRPCcontest_saveDeveloperInfo.mm \
../../legacy/TL/TL/TLRPCdestroy_session.mm \
../../legacy/TL/TL/TLRPCdestroy_sessions.mm \
../../legacy/TL/TL/TLRPCgeo_saveGeoPlace.mm \
../../legacy/TL/TL/TLRPCget_future_salts.mm \
../../legacy/TL/TL/TLRPChelp_getAppChangelog.mm \
../../legacy/TL/TL/TLRPChelp_getAppPrefs.mm \
../../legacy/TL/TL/TLRPChelp_getAppUpdate.mm \
../../legacy/TL/TL/TLRPChelp_getCdnConfig.mm \
../../legacy/TL/TL/TLRPChelp_getConfig.mm \
../../legacy/TL/TL/TLRPChelp_getInviteText.mm \
../../legacy/TL/TL/TLRPChelp_getNearestDc.mm \
../../legacy/TL/TL/TLRPChelp_getRecentMeUrls.mm \
../../legacy/TL/TL/TLRPChelp_getScheme.mm \
../../legacy/TL/TL/TLRPChelp_getSupport.mm \
../../legacy/TL/TL/TLRPChelp_saveNetworkStats.mm \
../../legacy/TL/TL/TLRPChelp_test.mm \
../../legacy/TL/TL/TLRPClangpack_getDifference.mm \
../../legacy/TL/TL/TLRPClangpack_getLangPack.mm \
../../legacy/TL/TL/TLRPClangpack_getLanguages.mm \
../../legacy/TL/TL/TLRPClangpack_getStrings.mm \
../../legacy/TL/TL/TLRPCmessages_acceptEncryption.mm \
../../legacy/TL/TL/TLRPCmessages_addChatUser.mm \
../../legacy/TL/TL/TLRPCmessages_checkChatInvite.mm \
../../legacy/TL/TL/TLRPCmessages_clearRecentStickers.mm \
../../legacy/TL/TL/TLRPCmessages_createChat.mm \
../../legacy/TL/TL/TLRPCmessages_deactivateChat.mm \
../../legacy/TL/TL/TLRPCmessages_deleteChatUser.mm \
../../legacy/TL/TL/TLRPCmessages_deleteHistory.mm \
../../legacy/TL/TL/TLRPCmessages_deleteMessages.mm \
../../legacy/TL/TL/TLRPCmessages_discardEncryption.mm \
../../legacy/TL/TL/TLRPCmessages_editChatAdmin.mm \
../../legacy/TL/TL/TLRPCmessages_editChatPhoto.mm \
../../legacy/TL/TL/TLRPCmessages_editChatTitle.mm \
../../legacy/TL/TL/TLRPCmessages_exportChatInvite.mm \
../../legacy/TL/TL/TLRPCmessages_faveSticker.mm \
../../legacy/TL/TL/TLRPCmessages_forwardMessagesMeta.mm \
../../legacy/TL/TL/TLRPCmessages_getAllChats.mm \
../../legacy/TL/TL/TLRPCmessages_getAllDrafts.mm \
../../legacy/TL/TL/TLRPCmessages_getAllStickers.mm \
../../legacy/TL/TL/TLRPCmessages_getArchivedStickers.mm \
../../legacy/TL/TL/TLRPCmessages_getAttachedStickers.mm \
../../legacy/TL/TL/TLRPCmessages_getChats.mm \
../../legacy/TL/TL/TLRPCmessages_getCommonChats.mm \
../../legacy/TL/TL/TLRPCmessages_getDhConfig.mm \
../../legacy/TL/TL/TLRPCmessages_getDialogsMeta.mm \
../../legacy/TL/TL/TLRPCmessages_getDocumentByHash.mm \
../../legacy/TL/TL/TLRPCmessages_getFavedStickers.mm \
../../legacy/TL/TL/TLRPCmessages_getFeaturedStickers.mm \
../../legacy/TL/TL/TLRPCmessages_getFullChat.mm \
../../legacy/TL/TL/TLRPCmessages_getHistory.mm \
../../legacy/TL/TL/TLRPCmessages_getMaskStickers.mm \
../../legacy/TL/TL/TLRPCmessages_getMessageEditData.mm \
../../legacy/TL/TL/TLRPCmessages_getMessages.mm \
../../legacy/TL/TL/TLRPCmessages_getMessagesViews.mm \
../../legacy/TL/TL/TLRPCmessages_getPeerDialogs.mm \
../../legacy/TL/TL/TLRPCmessages_getPeerSettings.mm \
../../legacy/TL/TL/TLRPCmessages_getPinnedDialogs.mm \
../../legacy/TL/TL/TLRPCmessages_getRecentLocations.mm \
../../legacy/TL/TL/TLRPCmessages_getRecentStickers.mm \
../../legacy/TL/TL/TLRPCmessages_getSavedGifs.mm \
../../legacy/TL/TL/TLRPCmessages_getStickerSet.mm \
../../legacy/TL/TL/TLRPCmessages_getStickers.mm \
../../legacy/TL/TL/TLRPCmessages_getUnreadMentions.mm \
../../legacy/TL/TL/TLRPCmessages_getUnusedStickers.mm \
../../legacy/TL/TL/TLRPCmessages_getWebPage.mm \
../../legacy/TL/TL/TLRPCmessages_getWebPagePreview.mm \
../../legacy/TL/TL/TLRPCmessages_hideReportSpam.mm \
../../legacy/TL/TL/TLRPCmessages_importChatInvite.mm \
../../legacy/TL/TL/TLRPCmessages_installStickerSet.mm \
../../legacy/TL/TL/TLRPCmessages_migrateChat.mm \
../../legacy/TL/TL/TLRPCmessages_readEncryptedHistory.mm \
../../legacy/TL/TL/TLRPCmessages_readFeaturedStickers.mm \
../../legacy/TL/TL/TLRPCmessages_readHistory.mm \
../../legacy/TL/TL/TLRPCmessages_readMentions.mm \
../../legacy/TL/TL/TLRPCmessages_readMessageContents.mm \
../../legacy/TL/TL/TLRPCmessages_receivedMessages.mm \
../../legacy/TL/TL/TLRPCmessages_receivedQueue.mm \
../../legacy/TL/TL/TLRPCmessages_reorderPinnedDialogs.mm \
../../legacy/TL/TL/TLRPCmessages_reorderStickerSets.mm \
../../legacy/TL/TL/TLRPCmessages_reportEncryptedSpam.mm \
../../legacy/TL/TL/TLRPCmessages_reportSpam.mm \
../../legacy/TL/TL/TLRPCmessages_requestEncryption.mm \
../../legacy/TL/TL/TLRPCmessages_restoreMessages.mm \
../../legacy/TL/TL/TLRPCmessages_saveGif.mm \
../../legacy/TL/TL/TLRPCmessages_saveRecentSticker.mm \
../../legacy/TL/TL/TLRPCmessages_searchGifs.mm \
../../legacy/TL/TL/TLRPCmessages_searchGlobal.mm
