libuofs2_FILES = ../../Telegraph/TGGroupAvatarGalleryModel.m \
../../Telegraph/TGGroupInfoCollectionItem.m \
../../Telegraph/TGGroupInfoCollectionItemView.m \
../../Telegraph/TGGroupInfoContactListCreateLinkCell.m \
../../Telegraph/TGGroupInfoController.m \
../../Telegraph/TGGroupInfoSelectContactController.m \
../../Telegraph/TGGroupInfoShareLinkController.m \
../../Telegraph/TGGroupInfoShareLinkLinkItem.m \
../../Telegraph/TGGroupInfoShareLinkLinkItemView.m \
../../Telegraph/TGGroupInfoUserCell.m \
../../Telegraph/TGGroupInfoUserCollectionItem.m \
../../Telegraph/TGGroupInfoUserCollectionItemView.m \
../../Telegraph/TGGroupInvitationInfo.m \
../../Telegraph/TGGroupInviteSheet.m \
../../Telegraph/TGGroupInviteSheetItemView.m \
../../Telegraph/TGGroupInviteSheetMoreCell.m \
../../Telegraph/TGGroupManagementSignals.m \
../../Telegraph/TGGroupModernConversationCompanion.m \
../../Telegraph/TGGroupedCell.m \
../../Telegraph/TGGroupedUserOnlineSignals.m \
../../Telegraph/TGGroupsInCommonController.m \
../../Telegraph/TGHashtagOverviewController.m \
../../Telegraph/TGHashtagSearchController.m \
../../Telegraph/TGHeaderCollectionItem.m \
../../Telegraph/TGHeaderCollectionItemView.m \
../../Telegraph/TGHolderSet.m \
../../Telegraph/TGHoleMessageViewModel.m \
../../Telegraph/TGICloudEmergencyDataSignals.m \
../../Telegraph/TGICloudFileDownloadActor.m \
../../Telegraph/TGICloudItem.m \
../../Telegraph/TGImageDownloadActor.m \
../../Telegraph/TGImageFileReference.m \
../../Telegraph/TGImageInfo+Telegraph.m \
../../Telegraph/TGImageMediaAttachment+Telegraph.m \
../../Telegraph/TGImageMessageViewModel.m \
../../Telegraph/TGImageSearchActor.m \
../../Telegraph/TGInlineBotsInputCell.m \
../../Telegraph/TGInlineBotsInputPanel.m \
../../Telegraph/TGInlineBotsSettingsCell.m \
../../Telegraph/TGInlineVideoModel.m \
../../Telegraph/TGInlineVideoView.m \
../../Telegraph/TGInputAccessoryView.m \
../../Telegraph/TGInputMenuItem.m \
../../Telegraph/TGInstagramContentPropertiesActor.m \
../../Telegraph/TGInstagramDataContentProperty.m \
../../Telegraph/TGInstagramMediaIdSignal.m \
../../Telegraph/TGInstantPage+TG.m \
../../Telegraph/TGInstantPageAudioView.m \
../../Telegraph/TGInstantPageChannelView.m \
../../Telegraph/TGInstantPageColorView.m \
../../Telegraph/TGInstantPageController.m \
../../Telegraph/TGInstantPageControllerNavigationBar.m \
../../Telegraph/TGInstantPageControllerView.m \
../../Telegraph/TGInstantPageEmbedView.m \
../../Telegraph/TGInstantPageFooterButtonView.m \
../../Telegraph/TGInstantPageImageView.m \
../../Telegraph/TGInstantPageLayout.m \
../../Telegraph/TGInstantPageLinkSelectionView.m \
../../Telegraph/TGInstantPageMedia.m \
../../Telegraph/TGInstantPageMediaArguments.m \
../../Telegraph/TGInstantPageScrollState.m \
../../Telegraph/TGInstantPageSettingsView.m \
../../Telegraph/TGInstantPageSlideshowView.m \
../../Telegraph/TGInstantPageTile.m \
../../Telegraph/TGInstantPageTileView.m \
../../Telegraph/TGInstantPreviewTouchAreaModel.m \
../../Telegraph/TGInstantPreviewTouchAreaView.m \
../../Telegraph/TGInterfaceAssets.m \
../../Telegraph/TGInterfaceManager.m \
../../Telegraph/TGInternalGifSearchResult+TGMediaItem.m \
../../Telegraph/TGInternalGifSearchResult.m \
../../Telegraph/TGInternalGifSearchResultGalleryItem.m \
../../Telegraph/TGInternalGifSearchResultGalleryItemView.m \
../../Telegraph/TGInternalGifSearchResultItem.m \
../../Telegraph/TGInternalGifSearchResultItemView.m \
../../Telegraph/TGItemCollectionGalleryItem.m \
../../Telegraph/TGItemCollectionGalleryItemView.m \
../../Telegraph/TGItemCollectionGalleryModel.m \
../../Telegraph/TGItemCollectionGalleryVideoBaseItemView.m \
../../Telegraph/TGItemCollectionGalleryVideoItemView.m \
../../Telegraph/TGJpegTurbo.m \
../../Telegraph/TGKeychainImport.m \
../../Telegraph/TGLabelMenuItem.m \
../../Telegraph/TGLabelMenuItemView.m \
../../Telegraph/TGLegacyComponentsContext.m \
../../Telegraph/TGLegacyComponentsGlobalsProvider.m \
../../Telegraph/TGLegacyWallpaperController.m \
../../Telegraph/TGLinkPreviewsContentProperty.m \
../../Telegraph/TGLinkTargetView.m \
../../Telegraph/TGListThumbnailSignals.m \
../../Telegraph/TGLiveLocationElapsedViewModel.m \
../../Telegraph/TGLiveLocationManager.m \
../../Telegraph/TGLiveLocationMessageViewModel.m \
../../Telegraph/TGLiveLocationSession.m \
../../Telegraph/TGLiveLocationSignals.m \
../../Telegraph/TGLiveLocationTitlePanel.m \
../../Telegraph/TGLiveUploadActor.m \
../../Telegraph/TGLoadConversationAndHistoryForSearchActor.m \
../../Telegraph/TGLoadingItemView.m \
../../Telegraph/TGLoadingPlaceholderMessageModel.m \
../../Telegraph/TGLocalizationSelectionController.m \
../../Telegraph/TGLocalizationSignals.m \
../../Telegraph/TGLocationMessageViewModel.m \
../../Telegraph/TGLocationPulseViewModel.m \
../../Telegraph/TGLocationRequestActor.m \
../../Telegraph/TGLocationReverseGeocodeActor.m \
../../Telegraph/TGLocationServicesStateActor.m \
../../Telegraph/TGLocationThumbnailDataSource.m \
../../Telegraph/TGLocationVenueIconDataSource.m \
../../Telegraph/TGLockIconView.m \
../../Telegraph/TGLoginCodeController.m \
../../Telegraph/TGLoginCountriesController.m \
../../Telegraph/TGLoginCountryCell.m \
../../Telegraph/TGLoginPasswordController.m \
../../Telegraph/TGLoginPasswordView.m \
../../Telegraph/TGLoginPhoneController.m \
../../Telegraph/TGLoginProfileController.m \
../../Telegraph/TGLoginResetAccountControllerView.m \
../../Telegraph/TGLoginResetAccountProtectedController.m \
../../Telegraph/TGLogoutRequestBuilder.m \
../../Telegraph/TGMainTabsController.m \
../../Telegraph/TGMapSnapshotterActor.m \
../../Telegraph/TGMarqueeLabel.m \
../../Telegraph/TGMaskStickersSignals.m \
../../Telegraph/TGMeContactsCell.m \
../../Telegraph/TGMediaAssetContentProperty.m \
../../Telegraph/TGMediaCacheIndexData.m \
../../Telegraph/TGMediaListPhotoDataSource.m \
../../Telegraph/TGMediaLiveUploadWatcher.m \
../../Telegraph/TGMediaOriginInfo+Telegraph.m \
../../Telegraph/TGMediaPostingContext.m \
../../Telegraph/TGMediaPreviewTask.m \
../../Telegraph/TGMediaSearchController.m \
../../Telegraph/TGMediaSignals.m \
../../Telegraph/TGMediaStoreContext.m \
../../Telegraph/TGMenuItem.m \
../../Telegraph/TGMenuSection.m \
../../Telegraph/TGMenuSheetCheckItemView.m \
../../Telegraph/TGMenuSheetModernButtonItemView.m \
../../Telegraph/TGMessage+Telegraph.m \
../../Telegraph/TGMessageGroupedLayout.m \
../../Telegraph/TGMessageImageAdditionalDataView.m \
../../Telegraph/TGMessageImageView.m \
../../Telegraph/TGMessageImageViewModel.m \
../../Telegraph/TGMessageImageViewTimestampView.m \
../../Telegraph/TGMessageModernConversationItem.m \
../../Telegraph/TGMessageNotificationView.m \
../../Telegraph/TGMessageRange.m \
../../Telegraph/TGMessageReplyButtonsModel.m \
../../Telegraph/TGMessageSearchSignals.m \
../../Telegraph/TGMessageUniqueIdContentProperty.m \
../../Telegraph/TGMessageViewModel.m \
../../Telegraph/TGMessageViewedContentProperty.m \
../../Telegraph/TGMessageViewsView.m \
../../Telegraph/TGMessageViewsViewModel.m \
../../Telegraph/TGMessagesSearchActor.m \
../../Telegraph/TGMigratedChannelConversationHeaderView.m \
../../Telegraph/TGModenConcersationReplyAssociatedPanel.m \
../../Telegraph/TGModernButtonView.m \
../../Telegraph/TGModernButtonViewModel.m \
../../Telegraph/TGModernCheckButtonView.m \
../../Telegraph/TGModernCheckButtonViewModel.m \
../../Telegraph/TGModernClockProgressView.m \
../../Telegraph/TGModernClockProgressViewModel.m \
../../Telegraph/TGModernCollectionCell.m \
../../Telegraph/TGModernColorView.m \
../../Telegraph/TGModernColorViewModel.m \
../../Telegraph/TGModernConversationActionInputPanel.m \
../../Telegraph/TGModernConversationActivity.m \
../../Telegraph/TGModernConversationActivityManager.m \
../../Telegraph/TGModernConversationAudioPlayer.m \
../../Telegraph/TGModernConversationAudioPlayerContext.m \
../../Telegraph/TGModernConversationAudioPreviewInputPanel.m \
../../Telegraph/TGModernConversationAvatarButton.m \
../../Telegraph/TGModernConversationBarButtonItem.m \
../../Telegraph/TGModernConversationCollectionView.m \
../../Telegraph/TGModernConversationCollectionViewInstantPreviewRecognizer.m \
../../Telegraph/TGModernConversationCommandsAssociatedPanel.m \
../../Telegraph/TGModernConversationCompanion.m \
../../Telegraph/TGModernConversationComplexMediaContextResultsAssociatedPanel.m \
../../Telegraph/TGModernConversationContactLinkTitlePanel.m \
../../Telegraph/TGModernConversationController.m \
../../Telegraph/TGModernConversationControllerDynamicTypeSignals.m \
../../Telegraph/TGModernConversationControllerView.m \
../../Telegraph/TGModernConversationDimWindow.m \
../../Telegraph/TGModernConversationEditingMessageInputPanel.m \
../../Telegraph/TGModernConversationEditingPanel.m \
../../Telegraph/TGModernConversationEmptyListPlaceholderView.m \
../../Telegraph/TGModernConversationForwardInputPanel.m \
../../Telegraph/TGModernConversationGenericContextResultsAssociatedPanel.m \
../../Telegraph/TGModernConversationGenericContextResultsAssociatedPanelSwitchPm.m \
../../Telegraph/TGModernConversationGenericEmptyListView.m \
../../Telegraph/TGModernConversationGenericTitlePanel.m \
../../Telegraph/TGModernConversationGroupTitlePanel.m \
../../Telegraph/TGModernConversationInputAttachButton.m \
../../Telegraph/TGModernConversationInputPanel.m \
../../Telegraph/TGModernConversationInputTextPanel.m \
../../Telegraph/TGModernConversationItem.m \
../../Telegraph/TGModernConversationMediaContextResultsAssociatedPanel.m \
../../Telegraph/TGModernConversationPrivateTitlePanel.m \
../../Telegraph/TGModernConversationRestrictedInlineAssociatedPanel.m \
../../Telegraph/TGModernConversationRestrictedInputPanel.m \
../../Telegraph/TGModernConversationSearchInputPanel.m \
../../Telegraph/TGModernConversationTitleIcon.m \
../../Telegraph/TGModernConversationTitlePanel.m \
../../Telegraph/TGModernConversationTitleView.m \
../../Telegraph/TGModernConversationUpgradeStateTitlePanel.m \
../../Telegraph/TGModernConversationViewContext.m \
../../Telegraph/TGModernConversationViewLayout.m \
../../Telegraph/TGModernConversationWebPreviewInputPanel.m \
../../Telegraph/TGModernDataImageView.m \
../../Telegraph/TGModernDataImageViewModel.m \
../../Telegraph/TGModernDateHeaderView.m \
../../Telegraph/TGModernDateViewModel.m \
../../Telegraph/TGModernFlatteningView.m \
../../Telegraph/TGModernFlatteningViewModel.m \
../../Telegraph/TGModernGalleryMessageImageItem.m \
../../Telegraph/TGModernGalleryMessageImageItemView.m \
../../Telegraph/TGModernGalleryNewVideoItemView.m \
../../Telegraph/TGModernGalleryPIPHeaderView.m \
../../Telegraph/TGModernGalleryRotationGestureRecognizer.m \
../../Telegraph/TGModernGalleryVideoFooterView.m \
../../Telegraph/TGModernGalleryVideoItem.m \
../../Telegraph/TGModernGalleryVideoItemView.m \
../../Telegraph/TGModernGalleryVideoPlayerState.m \
../../Telegraph/TGModernGalleryVideoPlayerView.m \
../../Telegraph/TGModernGalleryVideoScrubbingInterfaceView.m \
../../Telegraph/TGModernImageView.m \
../../Telegraph/TGModernImageViewModel.m \
../../Telegraph/TGModernLabelViewModel.m \
../../Telegraph/TGModernLetteredAvatarView.m \
../../Telegraph/TGModernMediaCollectionView.m \
../../Telegraph/TGModernMediaListCell.m \
../../Telegraph/TGModernMediaListController.m \
../../Telegraph/TGModernMediaListImageItem.m \
../../Telegraph/TGModernMediaListImageItemView.m \
../../Telegraph/TGModernMediaListLayout.m \
../../Telegraph/TGModernMediaListModel.m \
../../Telegraph/TGModernMediaListThumbnailItemView.m \
../../Telegraph/TGModernMediaListVideoItem.m \
../../Telegraph/TGModernMediaListVideoItemView.m \
../../Telegraph/TGModernRemoteImageView.m \
../../Telegraph/TGModernRemoteImageViewModel.m \
../../Telegraph/TGModernRemoteWallpaperListActor.m \
../../Telegraph/TGModernSendCommonMessageActor.m \
../../Telegraph/TGModernSendMessageActor.m \
../../Telegraph/TGModernSendSecretMessageActor.m \
../../Telegraph/TGModernTemporaryView.m \
../../Telegraph/TGModernTextView.m \
../../Telegraph/TGModernTextViewModel.m \
../../Telegraph/TGModernUnreadHeaderView.m \
../../Telegraph/TGModernViewContext.m \
../../Telegraph/TGModernViewInlineMediaContext.m \
../../Telegraph/TGModernViewModel.m \
../../Telegraph/TGModernViewStorage.m \
../../Telegraph/TGMultipartFileDownloadActor.m \
../../Telegraph/TGMultipleStickerPacksCell.m \
../../Telegraph/TGMultipleStickerPacksCollectionItemView.m \
../../Telegraph/TGMusicAudioMessageModel.m \
../../Telegraph/TGMusicPlayer.m \
../../Telegraph/TGMusicPlayerCompleteView.m \
../../Telegraph/TGMusicPlayerController.m \
../../Telegraph/TGMusicPlayerFullView.m \
../../Telegraph/TGMusicPlayerItem.m \
../../Telegraph/TGMusicPlayerItemSignals.m \
../../Telegraph/TGMusicPlayerModeButton.m \
../../Telegraph/TGMusicPlayerPlaylist.m \
../../Telegraph/TGMusicPlayerScrubbingArea.m \
../../Telegraph/TGMusicPlayerView.m \
../../Telegraph/TGMusicPlaylistCell.m \
../../Telegraph/TGMusicUtils.m \
../../Telegraph/TGMusicWebpageFooterModel.m \
../../Telegraph/TGNativeAudioPlayer.m \
../../Telegraph/TGNavigationBarMusicPlayerProvider.m \
../../Telegraph/TGNetworkOverridesController.m \
../../Telegraph/TGNetworkSettings.m \
../../Telegraph/TGNetworkTypeManager.m \
../../Telegraph/TGNetworkUsageController.m \
../../Telegraph/TGNetworkWorker.m \
../../Telegraph/TGNotificationAudioPreviewView.m \
../../Telegraph/TGNotificationBackgroundView.m \
../../Telegraph/TGNotificationContactPreviewView.m \
../../Telegraph/TGNotificationContentView.m \
../../Telegraph/TGNotificationController.m \
../../Telegraph/TGNotificationException.m \
../../Telegraph/TGNotificationExceptionCell.m \
../../Telegraph/TGNotificationExceptionsController.m \
../../Telegraph/TGNotificationExceptionsSignal.m \
../../Telegraph/TGNotificationFilePreviewView.m \
../../Telegraph/TGNotificationForwardHeaderView.m \
../../Telegraph/TGNotificationMediaPreviewView.m \
../../Telegraph/TGNotificationMessageLabel.m \
../../Telegraph/TGNotificationMessageViewModel.m \
../../Telegraph/TGNotificationOverlayView.m \
../../Telegraph/TGNotificationPreviewView.m \
../../Telegraph/TGNotificationPrivacyAccountSetting.m \
../../Telegraph/TGNotificationReplyButtonsView.m \
../../Telegraph/TGNotificationReplyHeaderView.m \
../../Telegraph/TGNotificationReplyPanelView.m \
../../Telegraph/TGNotificationSettingsController.m \
../../Telegraph/TGNotificationStickerPreviewView.m \
../../Telegraph/TGNotificationTextPreviewView.m \
../../Telegraph/TGNotificationVenuePreviewView.m \
../../Telegraph/TGNotificationView.m \
../../Telegraph/TGOpenInAppItem.m \
../../Telegraph/TGOpenInBrowserItems.m \
../../Telegraph/TGOpenInCarouselCell.m \
../../Telegraph/TGOpenInCarouselItemView.m \
../../Telegraph/TGOpenInLocationItems.m \
../../Telegraph/TGOpenInMenu.m \
../../Telegraph/TGOpenInSignals.m \
../../Telegraph/TGOpenInSocialItems.m \
../../Telegraph/TGOpenInVideoItems.m \
../../Telegraph/TGOpusAudioPlayerAU.m \
../../Telegraph/TGOpusAudioRecorder.m \
../../Telegraph/TGPasscodeSettingsController.m \
../../Telegraph/TGPasscodeSignals.m \
../../Telegraph/TGPasscodeWindow.m \
../../Telegraph/TGPassportAddressController.m \
../../Telegraph/TGPassportBirthDateItemView.m \
../../Telegraph/TGPassportBirthDateMenu.m \
../../Telegraph/TGPassportDocumentController.m \
../../Telegraph/TGPassportEmailCodeController.m \
../../Telegraph/TGPassportEmailController.m \
../../Telegraph/TGPassportErrors.m \
../../Telegraph/TGPassportFieldCollectionItem.m \
../../Telegraph/TGPassportFieldCollectionItemView.m \
../../Telegraph/TGPassportFile.m \
../../Telegraph/TGPassportFileCollectionItem.m \
../../Telegraph/TGPassportFileCollectionItemView.m \
../../Telegraph/TGPassportForm.m \
../../Telegraph/TGPassportFormRequest.m \
../../Telegraph/TGPassportGalleryItem.m \
../../Telegraph/TGPassportGalleryItemView.m \
../../Telegraph/TGPassportGalleryModel.m \
../../Telegraph/TGPassportGenderItemView.m \
../../Telegraph/TGPassportGenderMenu.m \
../../Telegraph/TGPassportHeaderView.m \
../../Telegraph/TGPassportICloud.m \
../../Telegraph/TGPassportIdentityController.m \
../../Telegraph/TGPassportLanguageMap.m \
../../Telegraph/TGPassportPasswordView.m \
../../Telegraph/TGPassportPhoneCodeController.m \
../../Telegraph/TGPassportPhoneController.m \
../../Telegraph/TGPassportRequestController.m \
../../Telegraph/TGPassportScanController.m \
../../Telegraph/TGPassportSetupPasswordView.m \
../../Telegraph/TGPassportSignals.m \
../../Telegraph/TGPasswordConfirmationController.m \
../../Telegraph/TGPasswordEmailController.m \
../../Telegraph/TGPasswordEntryController.m \
../../Telegraph/TGPasswordHintController.m \
../../Telegraph/TGPasswordInputItem.m \
../../Telegraph/TGPasswordInputItemView.m \
../../Telegraph/TGPasswordPlaceholderItem.m \
../../Telegraph/TGPasswordPlaceholderItemView.m \
../../Telegraph/TGPasswordRecoveryController.m \
../../Telegraph/TGPasswordSettingsController.m \
../../Telegraph/TGPasswordSetupController.m \
../../Telegraph/TGPasswordSetupView.m \
../../Telegraph/TGPaymentAlertController.m \
../../Telegraph/TGPaymentAlertView.m \
../../Telegraph/TGPaymentCheckoutController.m \
../../Telegraph/TGPaymentCheckoutHeaderItem.m \
../../Telegraph/TGPaymentCheckoutHeaderItemView.m \
../../Telegraph/TGPaymentCheckoutInfoController.m \
../../Telegraph/TGPaymentCheckoutPriceItem.m \
../../Telegraph/TGPaymentCheckoutPriceItemView.m \
../../Telegraph/TGPaymentForm.m \
../../Telegraph/TGPaymentMethodController.m \
../../Telegraph/TGPaymentPasswordAlert.m \
../../Telegraph/TGPaymentPasswordEntryController.m \
../../Telegraph/TGPaymentPasswordEntryControllerView.m \
../../Telegraph/TGPaymentReceiptController.m \
../../Telegraph/TGPaymentWebController.m \
../../Telegraph/TGPeerAvatarImageDataSource.m \
../../Telegraph/TGPeerAvatarThumbnailDataSource.m \
../../Telegraph/TGPeerInfoSignals.m \
../../Telegraph/TGPeerNotificationSettingsSignals.m \
../../Telegraph/TGPeerRatingUpdates.m \
../../Telegraph/TGPeerReadState.m \
../../Telegraph/TGPeerSettingsActor.m \
../../Telegraph/TGPhoneCodeCollectionItem.m \
../../Telegraph/TGPhoneCodeCollectionItemView.m \
../../Telegraph/TGPhoneLabelPickerController.m \
../../Telegraph/TGPhoneMainViewController.m \
../../Telegraph/TGPhoneTextField.m \
../../Telegraph/TGPhonebookNumber.m \
../../Telegraph/TGPhonebookRecord.m \
../../Telegraph/TGPhonebookSignals.m \
../../Telegraph/TGPhonebookUserInfoController.m \
../../Telegraph/TGPhotoGridCell.m \
../../Telegraph/TGPhotoMessageViewModel.m \
../../Telegraph/TGPhotoThumbnailDataSource.m \
../../Telegraph/TGPickerSheet.m \
../../Telegraph/TGPinnedMessageTitlePanel.m \
../../Telegraph/TGPlaceholderImageDataSource.m \
../../Telegraph/TGPreparedAssetImageMessage.m \
../../Telegraph/TGPreparedAssetVideoMessage.m \
../../Telegraph/TGPreparedCloudDocumentMessage.m \
../../Telegraph/TGPreparedContactMessage.m \
../../Telegraph/TGPreparedDownloadDocumentMessage.m \
../../Telegraph/TGPreparedDownloadExternalDocumentMessage.m \
../../Telegraph/TGPreparedDownloadExternalGifMessage.m \
../../Telegraph/TGPreparedDownloadExternalImageMessage.m \
../../Telegraph/TGPreparedDownloadImageMessage.m \
../../Telegraph/TGPreparedForwardedMessage.m \
../../Telegraph/TGPreparedGameMessage.m \
../../Telegraph/TGPreparedLocalDocumentMessage.m \
../../Telegraph/TGPreparedLocalImageMessage.m \
../../Telegraph/TGPreparedLocalVideoMessage.m \
../../Telegraph/TGPreparedMapMessage.m \
../../Telegraph/TGPreparedMessage.m \
../../Telegraph/TGPreparedRemoteDocumentMessage.m \
../../Telegraph/TGPreparedRemoteImageMessage.m \
../../Telegraph/TGPreparedRemoteVideoMessage.m \
../../Telegraph/TGPreparedTextMessage.m \
../../Telegraph/TGPresentation.m \
../../Telegraph/TGPresentationAssets.m \
../../Telegraph/TGPresentationImages.m \
../../Telegraph/TGPreviewAboutItemView.m \
../../Telegraph/TGPreviewAudioItemView.m \
../../Telegraph/TGPreviewConversationItemView.m \
../../Telegraph/TGPreviewGifItemView.m \
../../Telegraph/TGPreviewLocationItemView.m \
../../Telegraph/TGPreviewMenu.m \
../../Telegraph/TGPreviewPhotoItemView.m \
../../Telegraph/TGPreviewPresentationHelper.m \
../../Telegraph/TGPreviewStickerItemView.m \
../../Telegraph/TGPreviewTextItemView.m \
../../Telegraph/TGPreviewWebPageItemView.m \
../../Telegraph/TGPrivacyCustomShareListController.m \
../../Telegraph/TGPrivacyLastSeenController.m \
../../Telegraph/TGPrivacySettingsController.m \
../../Telegraph/TGPrivateDataSettingsController.m \
../../Telegraph/TGPrivateModernConversationCompanion.m \
../../Telegraph/TGProfilePhotoListActor.m \
../../Telegraph/TGProfileUserAvatarGalleryItem.m \
../../Telegraph/TGProfileUserAvatarGalleryItemView.m \
../../Telegraph/TGProfileUserAvatarGalleryModel.m \
../../Telegraph/TGProxyBarButton.m \
../../Telegraph/TGProxyButtonItemView.m \
../../Telegraph/TGProxyCollectionItem.m \
../../Telegraph/TGProxyCollectionItemView.m
