libuofs1_FILES = ../../Share/TGProgressAlert.m \
../../Telegraph/TGDownloadMessagesSignal.m \
../../Telegraph/TelegramMediaResources.m \
../../Telegraph/API/SecretLayer1.m \
../../Telegraph/API/SecretLayer17.m \
../../Telegraph/API/SecretLayer20.m \
../../Telegraph/API/SecretLayer23.m \
../../Telegraph/API/SecretLayer46.m \
../../Telegraph/API/SecretLayer66.m \
../../Telegraph/API/SecretLayer73.m \
../../Telegraph/ATActor.m \
../../Telegraph/ATActorSystem.m \
../../Telegraph/ATQueue.m \
../../Telegraph/AdHoc/TGModernLetteredAvatarViewModel.m \
../../Telegraph/AdHoc/TGUsernameCollectionItem.m \
../../Telegraph/AttitudeESKF.cpp \
../../Telegraph/DrawingContext.m \
../../Telegraph/EDSunriseSet.m \
../../Telegraph/EMImage.m \
../../Telegraph/EMImageData.m \
../../Telegraph/EMInMemoryImageCache.m \
../../Telegraph/FetchResources.m \
../../Telegraph/ImageResourceDatas.m \
../../Telegraph/MediaBox.m \
../../Telegraph/MediaBoxContexts.m \
../../Telegraph/MultipartFetch.m \
../../Telegraph/PhotoResources.m \
../../Telegraph/TGAcceleratedVideoView.m \
../../Telegraph/TGAccessChecker.m \
../../Telegraph/TGAccessRequiredAlertView.m \
../../Telegraph/TGAccountInfoCollectionItem.m \
../../Telegraph/TGAccountSettings.m \
../../Telegraph/TGAccountSettingsActor.mm \
../../Telegraph/TGAccountSettingsController.m \
../../Telegraph/TGAccountSettingsUpdateActor.mm \
../../Telegraph/TGAccountSignals.m \
../../Telegraph/TGAccountTTLSetting.m \
../../Telegraph/TGActionMediaAttachment+Telegraph.m \
../../Telegraph/TGActionMenuItem.m \
../../Telegraph/TGActionMenuItemCell.m \
../../Telegraph/TGActionSheet.m \
../../Telegraph/TGActor.m \
../../Telegraph/TGAdSignals.m \
../../Telegraph/TGAddPaymentCardController.m \
../../Telegraph/TGAddToExistingContactController.m \
../../Telegraph/TGAdminLogConversationCompanion.m \
../../Telegraph/TGAlertSoundController.m \
../../Telegraph/TGAnimatedImageMessageViewModel.m \
../../Telegraph/TGAnimatedMediaContextResultCell.m \
../../Telegraph/TGAnimationThumbnailDataSource.m \
../../Telegraph/TGAppDelegate.mm \
../../Telegraph/TGAppSession.m \
../../Telegraph/TGAppSessionItem.m \
../../Telegraph/TGAppSessionItemView.m \
../../Telegraph/TGAppearanceAutoNightController.m \
../../Telegraph/TGAppearanceColorCollectionItem.m \
../../Telegraph/TGAppearanceColorCollectionItemView.m \
../../Telegraph/TGAppearanceColorPickerItemView.m \
../../Telegraph/TGAppearanceController.m \
../../Telegraph/TGAppearancePreviewCollectionItem.m \
../../Telegraph/TGAppearancePreviewCollectionItemView.m \
../../Telegraph/TGApplication.m \
../../Telegraph/TGApplicationFeatureDescription.m \
../../Telegraph/TGApplicationFeatures.m \
../../Telegraph/TGApplicationMainWindow.m \
../../Telegraph/TGApplyStateRequestBuilder.m \
../../Telegraph/TGApplyUpdatesActor.mm \
../../Telegraph/TGApplyUsernameActor.m \
../../Telegraph/TGArchivedStickerPacksAlert.m \
../../Telegraph/TGArchivedStickerPacksAlertView.m \
../../Telegraph/TGArchivedStickerPacksController.m \
../../Telegraph/TGArchivedStickerPacksSummary.m \
../../Telegraph/TGArticleWebpageFooterModel.m \
../../Telegraph/TGAttachmentFileTipView.m \
../../Telegraph/TGAttachmentSheetButtonItemView.m \
../../Telegraph/TGAttachmentSheetCheckmarkVariantItemView.m \
../../Telegraph/TGAttachmentSheetEmbedItemView.m \
../../Telegraph/TGAttachmentSheetItemView.m \
../../Telegraph/TGAttachmentSheetScrollView.m \
../../Telegraph/TGAttachmentSheetView.m \
../../Telegraph/TGAttachmentSheetWindow.m \
../../Telegraph/TGAudioDownloadActor.m \
../../Telegraph/TGAudioMediaAttachment+Telegraph.m \
../../Telegraph/TGAudioMessageViewModel.m \
../../Telegraph/TGAudioPlayer.m \
../../Telegraph/TGAudioRecorder.m \
../../Telegraph/TGAudioSessionManager.m \
../../Telegraph/TGAudioSliderArea.m \
../../Telegraph/TGAudioSliderButton.m \
../../Telegraph/TGAudioSliderView.m \
../../Telegraph/TGAudioSliderViewModel.m \
../../Telegraph/TGAudioWaveformSignal.m \
../../Telegraph/TGAudioWaveformView.m \
../../Telegraph/TGAudioWebpageFooterModel.m \
../../Telegraph/TGAuthSession.m \
../../Telegraph/TGAuthSessionItem.m \
../../Telegraph/TGAuthSessionItemView.m \
../../Telegraph/TGAuthSessionListSignals.m \
../../Telegraph/TGAuthSessionsController.m \
../../Telegraph/TGAuthSessionsEmptyView.m \
../../Telegraph/TGAutoDownloadPreferences.m \
../../Telegraph/TGAutoDownloadSettingsController.m \
../../Telegraph/TGBackspaceTextField.m \
../../Telegraph/TGBingSearchActor.m \
../../Telegraph/TGBingSearchResultItem+TGMediaItem.m \
../../Telegraph/TGBingSearchResultItem.m \
../../Telegraph/TGBlockListRequestActor.mm \
../../Telegraph/TGBlockedController.m \
../../Telegraph/TGBlockedPeersSignals.m \
../../Telegraph/TGBotContextExternalResult.m \
../../Telegraph/TGBotContextMediaResult.m \
../../Telegraph/TGBotContextResult.m \
../../Telegraph/TGBotContextResultSendMessageAuto.m \
../../Telegraph/TGBotContextResultSendMessageContact.m \
../../Telegraph/TGBotContextResultSendMessageGeo.m \
../../Telegraph/TGBotContextResultSendMessageText.m \
../../Telegraph/TGBotContextResults.m \
../../Telegraph/TGBotConversationHeaderView.m \
../../Telegraph/TGBotSignals.m \
../../Telegraph/TGBotUserInfoController.m \
../../Telegraph/TGBridgeAudioDecoder.mm \
../../Telegraph/TGBridgeAudioEncoder.m \
../../Telegraph/TGBridgeAudioHandler.m \
../../Telegraph/TGBridgeChatListHandler.m \
../../Telegraph/TGBridgeChatMessageListHandler.m \
../../Telegraph/TGBridgeContactsHandler.m \
../../Telegraph/TGBridgeContextService.m \
../../Telegraph/TGBridgeConversationHandler.m \
../../Telegraph/TGBridgeLocalizationService.m \
../../Telegraph/TGBridgeLocationHandler.m \
../../Telegraph/TGBridgeMediaHandler.m \
../../Telegraph/TGBridgePeerSettingsHandler.m \
../../Telegraph/TGBridgePresetsService.m \
../../Telegraph/TGBridgeRemoteHandler.m \
../../Telegraph/TGBridgeSendMessageHandler.m \
../../Telegraph/TGBridgeServer.m \
../../Telegraph/TGBridgeService.m \
../../Telegraph/TGBridgeSignalManager.m \
../../Telegraph/TGBridgeStateHandler.m \
../../Telegraph/TGBridgeStickersHandler.m \
../../Telegraph/TGBridgeStickersService.m \
../../Telegraph/TGBridgeSubscriptionHandler.m \
../../Telegraph/TGBridgeUserInfoHandler.m \
../../Telegraph/TGBrightnessCollectionItem.m \
../../Telegraph/TGBrightnessCollectionItemView.m \
../../Telegraph/TGButtonCollectionItem.m \
../../Telegraph/TGButtonCollectionItemView.m \
../../Telegraph/TGButtonMenuItem.m \
../../Telegraph/TGButtonMenuItemCell.m \
../../Telegraph/TGButtonsMenuItem.m \
../../Telegraph/TGButtonsMenuItemView.m \
../../Telegraph/TGCacheController.m \
../../Telegraph/TGCacheIndexingItem.m \
../../Telegraph/TGCacheIndexingItemView.m \
../../Telegraph/TGCachePeerItem.m \
../../Telegraph/TGCachePeerItemView.m \
../../Telegraph/TGCachedConversationData.m \
../../Telegraph/TGCachedPeerSettings.m \
../../Telegraph/TGCachedStickerPack.m \
../../Telegraph/TGCachedUserData.m \
../../Telegraph/TGCallAcceptButton.m \
../../Telegraph/TGCallAlertView.m \
../../Telegraph/TGCallAudioPlayer.m \
../../Telegraph/TGCallAudioRouteButtonItemView.m \
../../Telegraph/TGCallAvatarView.m \
../../Telegraph/TGCallBackgroundView.m \
../../Telegraph/TGCallButton.m \
../../Telegraph/TGCallButtonsView.m \
../../Telegraph/TGCallCell.m \
../../Telegraph/TGCallConnectionDescription.m \
../../Telegraph/TGCallContext.m \
../../Telegraph/TGCallController.mm \
../../Telegraph/TGCallDataSettingsController.m \
../../Telegraph/TGCallDebugView.m \
../../Telegraph/TGCallDiscardReason.m \
../../Telegraph/TGCallEncryptionKeyView.m \
../../Telegraph/TGCallIdenticonView.m \
../../Telegraph/TGCallInfoView.m \
../../Telegraph/TGCallKitAdapter.m \
../../Telegraph/TGCallManager.m \
../../Telegraph/TGCallMessageButton.m \
../../Telegraph/TGCallMessageViewModel.m \
../../Telegraph/TGCallRatingView.m \
../../Telegraph/TGCallReceptionView.m \
../../Telegraph/TGCallSession.mm \
../../Telegraph/TGCallSettingsController.m \
../../Telegraph/TGCallSignals.m \
../../Telegraph/TGCallState.m \
../../Telegraph/TGCallStatusBarView.m \
../../Telegraph/TGCallUtils.mm \
../../Telegraph/TGCallView.m \
../../Telegraph/TGCallWebrtcRuntimeIOS6.mm \
../../Telegraph/TGCameraController+Shortcut.m \
../../Telegraph/TGCameraShareSignals.m \
../../Telegraph/TGCancelAccountResetController.m \
../../Telegraph/TGCdnData.m \
../../Telegraph/TGCdnFileData.m \
../../Telegraph/TGChangeNameActor.m \
../../Telegraph/TGChangePeerBlockStatusActor.m \
../../Telegraph/TGChangePeerSettingsActor.m \
../../Telegraph/TGChangePhoneActor.m \
../../Telegraph/TGChangePhoneNumberCodeController.m \
../../Telegraph/TGChangePhoneNumberHelpController.m \
../../Telegraph/TGChangePhoneNumberHelpView.m \
../../Telegraph/TGChangePhoneNumberNumberController.m \
../../Telegraph/TGChangePrivacySettingsActor.m \
../../Telegraph/TGChannelAboutSetupController.m \
../../Telegraph/TGChannelAdminLogEmptyView.m \
../../Telegraph/TGChannelAdminLogEntry.m \
../../Telegraph/TGChannelAdminLogFilterController.m \
../../Telegraph/TGChannelAdminRights+Telegraph.m \
../../Telegraph/TGChannelBanController.m \
../../Telegraph/TGChannelBannedRights+Telegraph.m \
../../Telegraph/TGChannelConversationCompanion.mm \
../../Telegraph/TGChannelGroupHistoryController.m \
../../Telegraph/TGChannelGroupInfoController.m \
../../Telegraph/TGChannelInfoController.m \
../../Telegraph/TGChannelIntroController.m \
../../Telegraph/TGChannelLinkSetupController.m \
../../Telegraph/TGChannelList.m \
../../Telegraph/TGChannelManagementSignals.m \
../../Telegraph/TGChannelMembersController.m \
../../Telegraph/TGChannelMembersControllerEmptyView.m \
../../Telegraph/TGChannelModeratorCollectionItem.m \
../../Telegraph/TGChannelModeratorCollectionItemView.m \
../../Telegraph/TGChannelModeratorController.m \
../../Telegraph/TGChannelStateSignals.m \
../../Telegraph/TGChannelStickersController.m \
../../Telegraph/TGChatActionItem.m \
../../Telegraph/TGChatActionItemView.m \
../../Telegraph/TGChatActionsContainerView.m \
../../Telegraph/TGChatActionsController.m \
../../Telegraph/TGChatActionsInfoView.m \
../../Telegraph/TGChatActionsView.m \
../../Telegraph/TGChatListSignals.m \
../../Telegraph/TGChatMessageListSignal.mm \
../../Telegraph/TGChatMessageListView.m \
../../Telegraph/TGChatSearchController.m \
../../Telegraph/TGChatSettingsController.m \
../../Telegraph/TGCheckCollectionItem.m \
../../Telegraph/TGCheckCollectionItemView.m \
../../Telegraph/TGCheckImageStoredActor.m \
../../Telegraph/TGCheckPasswordActor.m \
../../Telegraph/TGCheckUpdatesActor.m \
../../Telegraph/TGCheckUsernameAvailabilityActor.m \
../../Telegraph/TGCloudStorageConversationEmptyView.m \
../../Telegraph/TGCollectionBottonDisclosureItem.m \
../../Telegraph/TGCollectionBottonDisclosureItemView.m \
../../Telegraph/TGCollectionItem.m \
../../Telegraph/TGCollectionItemView.m \
../../Telegraph/TGCollectionMenuController.m \
../../Telegraph/TGCollectionMenuLayout.m \
../../Telegraph/TGCollectionMenuSection.m \
../../Telegraph/TGCollectionMenuSectionList.m \
../../Telegraph/TGCollectionMenuView.m \
../../Telegraph/TGCollectionMultilineInputItem.m \
../../Telegraph/TGCollectionMultilineInputItemView.m \
../../Telegraph/TGCollectionStaticMultilineTextItem.m \
../../Telegraph/TGCollectionStaticMultilineTextItemView.m \
../../Telegraph/TGCollectionViewUpdateContext.m \
../../Telegraph/TGColorImageDataSource.m \
../../Telegraph/TGCommandKeyboardView.m \
../../Telegraph/TGCommandPanelCell.m \
../../Telegraph/TGCommentCollectionItem.m \
../../Telegraph/TGCommentCollectionItemView.m \
../../Telegraph/TGCommentMenuItem.m \
../../Telegraph/TGCommentMenuItemView.m \
../../Telegraph/TGConfirmationCodeData.m \
../../Telegraph/TGContactCell.m \
../../Telegraph/TGContactCellContents.m \
../../Telegraph/TGContactListRequestBuilder.mm \
../../Telegraph/TGContactListSearchActor.m \
../../Telegraph/TGContactMediaAttachment+Telegraph.m \
../../Telegraph/TGContactMessageViewModel.m \
../../Telegraph/TGContactsController.mm \
../../Telegraph/TGContactsGlobalSearchActor.m \
../../Telegraph/TGContentBubbleEmbeddedMediaModel.m \
../../Telegraph/TGContentBubbleViewModel.m \
../../Telegraph/TGConversation+Telegraph.m \
../../Telegraph/TGConversationActivityRequestBuilder.m \
../../Telegraph/TGConversationAddMemberRequestActor.m \
../../Telegraph/TGConversationAddMessagesActor.mm \
../../Telegraph/TGConversationChangePhotoActor.m \
../../Telegraph/TGConversationChangeTitleRequestActor.m \
../../Telegraph/TGConversationChatInfoRequestActor.m \
../../Telegraph/TGConversationClearHistoryActor.m \
../../Telegraph/TGConversationCollectionItem.m \
../../Telegraph/TGConversationCollectionItemView.m \
../../Telegraph/TGConversationCreateChatRequestActor.m \
../../Telegraph/TGConversationDeleteActor.m \
../../Telegraph/TGConversationDeleteMemberRequestActor.m \
../../Telegraph/TGConversationDeleteMessagesActor.m \
../../Telegraph/TGConversationHistoryAsyncRequestActor.m \
../../Telegraph/TGConversationHistoryRequestActor.m \
../../Telegraph/TGConversationScrollButton.m \
../../Telegraph/TGConversationScrollButtonContainer.m \
../../Telegraph/TGConversationScrollMessageStack.m \
../../Telegraph/TGConversationScrollState.m \
../../Telegraph/TGConversationSignals.m \
../../Telegraph/TGConversationSwitchCollectionItem.m \
../../Telegraph/TGConversationSwitchCollectionItemView.m \
../../Telegraph/TGConvertToSupergroupController.m \
../../Telegraph/TGCountryAndPhoneCollectionItem.m \
../../Telegraph/TGCountryAndPhoneCollectionItemView.m \
../../Telegraph/TGCreateContactController.m \
../../Telegraph/TGCreateEncryptedChatController.m \
../../Telegraph/TGCreateFeedController.mm \
../../Telegraph/TGCreateGroupController.m \
../../Telegraph/TGCreditCardNumberCollectionItem.m \
../../Telegraph/TGCreditCardNumberCollectionItemView.m \
../../Telegraph/TGCurrencyFormatter.m \
../../Telegraph/TGCustomActionSheet.m \
../../Telegraph/TGCustomAlertView.m \
../../Telegraph/TGDataItem.m \
../../Telegraph/TGDatabaseInterface.m \
../../Telegraph/TGDatabaseLegacy.m \
../../Telegraph/TGDatabaseReadMessagesByDate.m \
../../Telegraph/TGDatabaseUpdateMessage.m \
../../Telegraph/TGDatacenterContext.mm \
../../Telegraph/TGDatacenterWatchdogActor.m \
../../Telegraph/TGDebugController.m \
../../Telegraph/TGDeleteAccountActor.m \
../../Telegraph/TGDeleteAccountController.m \
../../Telegraph/TGDeleteProfilePhotoActor.m \
../../Telegraph/TGDeleteUserAvatarActor.m \
../../Telegraph/TGDialogListCellEditingButton.m \
../../Telegraph/TGDialogListCellEditingControls.m \
../../Telegraph/TGDialogListItem.m \
../../Telegraph/TGDialogListRecentPeers.m \
../../Telegraph/TGDialogListRecentPeersCell.m \
../../Telegraph/TGDialogListRemoteOffset.m \
../../Telegraph/TGDialogListRequestBuilder.mm \
../../Telegraph/TGDialogListSearchActor.m \
../../Telegraph/TGDialogListTitleContainer.m \
../../Telegraph/TGDiscardEncryptedChatActor.m \
../../Telegraph/TGDisclosureActionCollectionItem.m \
../../Telegraph/TGDisclosureActionCollectionItemView.m \
../../Telegraph/TGDocumentController.m \
../../Telegraph/TGDocumentDownloadActor.m \
../../Telegraph/TGDocumentEncryptedFileReference.m \
../../Telegraph/TGDocumentHttpFileReference.m \
../../Telegraph/TGDocumentMediaAttachment+Telegraph.m \
../../Telegraph/TGDocumentMessageIconModel.m \
../../Telegraph/TGDocumentMessageIconView.m \
../../Telegraph/TGDocumentMessageViewModel.m \
../../Telegraph/TGDocumentWebpageFooterModel.m \
../../Telegraph/TGDocumentWithIconContentModel.m \
../../Telegraph/TGDocumentWithThumbnailContentModel.m \
../../Telegraph/TGDownloadAudioSignal.m \
../../Telegraph/TGDownloadHistoryForNavigatingToMessageSignal.m \
../../Telegraph/TGDownloadLocalizationActor.m \
../../Telegraph/TGDownloadMessagesActor.m \
../../Telegraph/TGDropboxHelper.m \
../../Telegraph/TGDropboxItem.m \
../../Telegraph/TGEditProfileController.m \
../../Telegraph/TGEditableCollectionItemView.m \
../../Telegraph/TGEditingScrollView.m \
../../Telegraph/TGEditingScrollViewGestureRecognizer.m \
../../Telegraph/TGEmbedInternalPlayerView.m \
../../Telegraph/TGEmbedItemView.m \
../../Telegraph/TGEmbedMenu.m \
../../Telegraph/TGEmbedPIPController.m \
../../Telegraph/TGEmbedPIPPlaceholderView.m \
../../Telegraph/TGEmbedPIPView.m \
../../Telegraph/TGEmbedPlayerController.m \
../../Telegraph/TGEmbedPreviewController.m \
../../Telegraph/TGEmbedPreviewView.m \
../../Telegraph/TGEmojiSuggestions.mm \
../../Telegraph/TGEmptyGalleryFooterAccessoryView.m \
../../Telegraph/TGEncryptedChatResponseActor.m \
../../Telegraph/TGEncryptionKeyViewController.m \
../../Telegraph/TGExtendedChatDataRequestActor.m \
../../Telegraph/TGExtendedUserDataRequestActor.m \
../../Telegraph/TGExternalGalleryModel.m \
../../Telegraph/TGExternalGifSearchResult+TGMediaItem.m \
../../Telegraph/TGExternalGifSearchResult.m \
../../Telegraph/TGExternalGifSearchResultGalleryItem.m \
../../Telegraph/TGExternalGifSearchResultGalleryItemView.m \
../../Telegraph/TGExternalGifSearchResultItem.m \
../../Telegraph/TGExternalGifSearchResultItemView.m \
../../Telegraph/TGExternalImageSearchResult.m \
../../Telegraph/TGExternalShareSignals.m \
../../Telegraph/TGFaqActor.m \
../../Telegraph/TGFaqController.m \
../../Telegraph/TGFastCameraControlPanel.m \
../../Telegraph/TGFastCameraController.m \
../../Telegraph/TGFastTwoStepVerificationSetupController.m \
../../Telegraph/TGFavoriteStickersSignal.m \
../../Telegraph/TGFeaturedStickerPacksController.m \
../../Telegraph/TGFeed.m \
../../Telegraph/TGFeedConversationCompanion.m \
../../Telegraph/TGFeedConversationInputPanel.m \
../../Telegraph/TGFeedDialogListCompanion.mm \
../../Telegraph/TGFeedGroupingController.m \
../../Telegraph/TGFeedList.m \
../../Telegraph/TGFeedManagementSignals.m \
../../Telegraph/TGFeedNotificationsController.m \
../../Telegraph/TGFeedPosition.m \
../../Telegraph/TGFileDownloadActor.m \
../../Telegraph/TGFileReferenceManager.m \
../../Telegraph/TGFileThumbnailDataSource.m \
../../Telegraph/TGFileUploadActor.mm \
../../Telegraph/TGFlatActionCell.m \
../../Telegraph/TGFontSizeCollectionItem.m \
../../Telegraph/TGFontSizeCollectionItemView.m \
../../Telegraph/TGForceTouchGestureRecognizer.m \
../../Telegraph/TGForwardContactPickerController.m \
../../Telegraph/TGForwardTargetController.m \
../../Telegraph/TGGDPRNoticeController.m \
../../Telegraph/TGGLVideoView.m \
../../Telegraph/TGGalleryPhotoActor.m \
../../Telegraph/TGGalleryPhotoDataSource.m \
../../Telegraph/TGGalleryVideoPreviewDataSource.m \
../../Telegraph/TGGenericContextResultCell.m \
../../Telegraph/TGGenericModernConversationCompanion.mm \
../../Telegraph/TGGenericPeerGalleryGroupItem.m \
../../Telegraph/TGGenericPeerMediaGalleryActionsAccessoryView.m \
../../Telegraph/TGGenericPeerMediaGalleryDefaultFooterView.m \
../../Telegraph/TGGenericPeerMediaGalleryDefaultHeaderView.m \
../../Telegraph/TGGenericPeerMediaGalleryDeleteAccessoryView.m \
../../Telegraph/TGGenericPeerMediaGalleryGifItem.m \
../../Telegraph/TGGenericPeerMediaGalleryGifItemView.m \
../../Telegraph/TGGenericPeerMediaGalleryGroupSliderView.m \
../../Telegraph/TGGenericPeerMediaGalleryImageItem.m \
../../Telegraph/TGGenericPeerMediaGalleryModel.m \
../../Telegraph/TGGenericPeerMediaGalleryVideoItem.m \
../../Telegraph/TGGenericPeerMediaGalleryVideoItemView.m \
../../Telegraph/TGGenericPeerMediaListImageItem.m \
../../Telegraph/TGGenericPeerMediaListModel.m \
../../Telegraph/TGGenericPeerMediaListVideoItem.m \
../../Telegraph/TGGenericPeerPlaylistSignals.m \
../../Telegraph/TGGenericPeerVoiceMessagesPlaylistSignal.m \
../../Telegraph/TGGifGalleryAddAccessoryView.m \
../../Telegraph/TGGifGalleryModel.m \
../../Telegraph/TGGifKeyboardBalancedLayout.m \
../../Telegraph/TGGifKeyboardBalancedPartition.m \
../../Telegraph/TGGifKeyboardCell.m \
../../Telegraph/TGGiphySearchActor.m \
../../Telegraph/TGGiphySearchResultItem+TGMediaItem.m \
../../Telegraph/TGGiphySearchResultItem.m \
../../Telegraph/TGGlobalMessageSearchSignals.m \
../../Telegraph/TGGroupAdminsController.m \
../../Telegraph/TGGroupAvatarGalleryItem.m \
../../Telegraph/TGGroupAvatarGalleryItemView.m \
../../Telegraph/TGGroupAvatarGalleryModel.m \
../../Telegraph/TGGroupInfoCollectionItem.m \
../../Telegraph/TGGroupInfoCollectionItemView.m \
../../Telegraph/TGGroupInfoContactListCreateLinkCell.m \
../../Telegraph/TGGroupInfoController.m \
../../Telegraph/TGGroupInfoSelectContactController.m \
../../Telegraph/TGGroupInfoShareLinkController.m \
../../Telegraph/TGGroupInfoShareLinkLinkItem.m \
../../Telegraph/TGGroupInfoShareLinkLinkItemView.m \
../../Telegraph/TGGroupInfoUserCell.m \
../../Telegraph/TGGroupInfoUserCollectionItem.m \
../../Telegraph/TGGroupInfoUserCollectionItemView.m \
../../Telegraph/TGGroupInvitationInfo.m \
../../Telegraph/TGGroupInviteSheet.m \
../../Telegraph/TGGroupInviteSheetItemView.m \
../../Telegraph/TGGroupInviteSheetMoreCell.m \
../../Telegraph/TGGroupManagementSignals.m \
../../Telegraph/TGGroupModernConversationCompanion.m \
../../Telegraph/TGGroupedCell.m \
../../Telegraph/TGGroupedUserOnlineSignals.m \
../../Telegraph/TGGroupsInCommonController.m \
../../Telegraph/TGHashtagOverviewController.m \
../../Telegraph/TGHashtagSearchController.m \
../../Telegraph/TGHeaderCollectionItem.m \
../../Telegraph/TGHeaderCollectionItemView.m \
../../Telegraph/TGHolderSet.m \
../../Telegraph/TGHoleMessageViewModel.m \
../../Telegraph/TGICloudEmergencyDataSignals.m \
../../Telegraph/TGICloudFileDownloadActor.m \
../../Telegraph/TGICloudItem.m \
../../Telegraph/TGImageDownloadActor.m \
../../Telegraph/TGImageFileReference.m \
../../Telegraph/TGImageInfo+Telegraph.mm \
../../Telegraph/TGImageMediaAttachment+Telegraph.m \
../../Telegraph/TGImageMessageViewModel.m \
../../Telegraph/TGImageSearchActor.m \
../../Telegraph/TGInlineBotsInputCell.m \
../../Telegraph/TGInlineBotsInputPanel.m \
../../Telegraph/TGInlineBotsSettingsCell.m \
../../Telegraph/TGInlineVideoModel.m \
../../Telegraph/TGInlineVideoView.m \
../../Telegraph/TGInputAccessoryView.m \
../../Telegraph/TGInputMenuItem.m \
../../Telegraph/TGInstagramContentPropertiesActor.m \
../../Telegraph/TGInstagramDataContentProperty.m \
../../Telegraph/TGInstagramMediaIdSignal.m \
../../Telegraph/TGInstantPage+TG.m \
../../Telegraph/TGInstantPageAudioView.m \
../../Telegraph/TGInstantPageChannelView.m \
../../Telegraph/TGInstantPageColorView.m \
../../Telegraph/TGInstantPageController.m \
../../Telegraph/TGInstantPageControllerNavigationBar.m \
../../Telegraph/TGInstantPageControllerView.m \
../../Telegraph/TGInstantPageEmbedView.m \
../../Telegraph/TGInstantPageFooterButtonView.m \
../../Telegraph/TGInstantPageImageView.m \
../../Telegraph/TGInstantPageLayout.m \
../../Telegraph/TGInstantPageLinkSelectionView.m \
../../Telegraph/TGInstantPageMedia.m \
../../Telegraph/TGInstantPageMediaArguments.m \
../../Telegraph/TGInstantPageScrollState.m \
../../Telegraph/TGInstantPageSettingsView.m \
../../Telegraph/TGInstantPageSlideshowView.m \
../../Telegraph/TGInstantPageTile.m \
../../Telegraph/TGInstantPageTileView.m \
../../Telegraph/TGInstantPreviewTouchAreaModel.m \
../../Telegraph/TGInstantPreviewTouchAreaView.m \
../../Telegraph/TGInterfaceAssets.mm \
../../Telegraph/TGInterfaceManager.mm \
../../Telegraph/TGInternalGifSearchResult+TGMediaItem.m \
../../Telegraph/TGInternalGifSearchResult.m \
../../Telegraph/TGInternalGifSearchResultGalleryItem.m \
../../Telegraph/TGInternalGifSearchResultGalleryItemView.m \
../../Telegraph/TGInternalGifSearchResultItem.m \
../../Telegraph/TGInternalGifSearchResultItemView.m \
../../Telegraph/TGItemCollectionGalleryItem.m \
../../Telegraph/TGItemCollectionGalleryItemView.m \
../../Telegraph/TGItemCollectionGalleryModel.m \
../../Telegraph/TGItemCollectionGalleryVideoBaseItemView.m \
../../Telegraph/TGItemCollectionGalleryVideoItemView.m \
../../Telegraph/TGJpegTurbo.m \
../../Telegraph/TGKeychainImport.m \
../../Telegraph/TGLabelMenuItem.m \
../../Telegraph/TGLabelMenuItemView.m \
../../Telegraph/TGLegacyComponentsContext.m \
../../Telegraph/TGLegacyComponentsGlobalsProvider.m \
../../Telegraph/TGLegacyWallpaperController.m \
../../Telegraph/TGLinkPreviewsContentProperty.m \
../../Telegraph/TGLinkTargetView.m \
../../Telegraph/TGListThumbnailSignals.m \
../../Telegraph/TGLiveLocationElapsedViewModel.m \
../../Telegraph/TGLiveLocationManager.m \
../../Telegraph/TGLiveLocationMessageViewModel.m \
../../Telegraph/TGLiveLocationSession.m \
../../Telegraph/TGLiveLocationSignals.m \
../../Telegraph/TGLiveLocationTitlePanel.m \
../../Telegraph/TGLiveUploadActor.m \
../../Telegraph/TGLoadConversationAndHistoryForSearchActor.m \
../../Telegraph/TGLoadingItemView.m \
../../Telegraph/TGLoadingPlaceholderMessageModel.m \
../../Telegraph/TGLocalizationSelectionController.m \
../../Telegraph/TGLocalizationSignals.m \
../../Telegraph/TGLocationMessageViewModel.m \
../../Telegraph/TGLocationPulseViewModel.m \
../../Telegraph/TGLocationRequestActor.m \
../../Telegraph/TGLocationReverseGeocodeActor.mm \
../../Telegraph/TGLocationServicesStateActor.m \
../../Telegraph/TGLocationThumbnailDataSource.m \
../../Telegraph/TGLocationVenueIconDataSource.m \
../../Telegraph/TGLockIconView.m \
../../Telegraph/TGLoginCodeController.m \
../../Telegraph/TGLoginCountriesController.m \
../../Telegraph/TGLoginCountryCell.m \
../../Telegraph/TGLoginPasswordController.m \
../../Telegraph/TGLoginPasswordView.m \
../../Telegraph/TGLoginPhoneController.m \
../../Telegraph/TGLoginProfileController.m \
../../Telegraph/TGLoginResetAccountControllerView.m \
../../Telegraph/TGLoginResetAccountProtectedController.m \
../../Telegraph/TGLogoutRequestBuilder.m \
../../Telegraph/TGMainTabsController.m \
../../Telegraph/TGMapSnapshotterActor.m \
../../Telegraph/TGMarqueeLabel.m \
../../Telegraph/TGMaskStickersSignals.m \
../../Telegraph/TGMeContactsCell.m \
../../Telegraph/TGMediaAssetContentProperty.m \
../../Telegraph/TGMediaCacheIndexData.m \
../../Telegraph/TGMediaListPhotoDataSource.m \
../../Telegraph/TGMediaLiveUploadWatcher.m \
../../Telegraph/TGMediaOriginInfo+Telegraph.m \
../../Telegraph/TGMediaPostingContext.m \
../../Telegraph/TGMediaPreviewTask.m \
../../Telegraph/TGMediaSearchController.m \
../../Telegraph/TGMediaSignals.m \
../../Telegraph/TGMediaStoreContext.m \
../../Telegraph/TGMenuItem.m \
../../Telegraph/TGMenuSection.m \
../../Telegraph/TGMenuSheetCheckItemView.m \
../../Telegraph/TGMenuSheetModernButtonItemView.m \
../../Telegraph/TGMessage+Telegraph.m \
../../Telegraph/TGMessageGroupedLayout.m \
../../Telegraph/TGMessageImageAdditionalDataView.m \
../../Telegraph/TGMessageImageView.m \
../../Telegraph/TGMessageImageViewModel.m \
../../Telegraph/TGMessageImageViewTimestampView.m \
../../Telegraph/TGMessageModernConversationItem.mm \
../../Telegraph/TGMessageNotificationView.mm \
../../Telegraph/TGMessageRange.mm \
../../Telegraph/TGMessageReplyButtonsModel.m \
../../Telegraph/TGMessageSearchSignals.m \
../../Telegraph/TGMessageUniqueIdContentProperty.m \
../../Telegraph/TGMessageViewModel.m \
../../Telegraph/TGMessageViewedContentProperty.m \
../../Telegraph/TGMessageViewsView.m \
../../Telegraph/TGMessageViewsViewModel.m \
../../Telegraph/TGMessagesSearchActor.m
