libuofs4_FILES = ../../Telegraph/TLRPCmessages_getBotCallbackAnswer.m \
../../Telegraph/TLRPCmessages_getDialogUnreadMarks.m \
../../Telegraph/TLRPCmessages_getDialogs.m \
../../Telegraph/TLRPCmessages_getInlineBotResults.m \
../../Telegraph/TLRPCmessages_markDialogUnread.m \
../../Telegraph/TLRPCmessages_report.m \
../../Telegraph/TLRPCmessages_saveDraft.m \
../../Telegraph/TLRPCmessages_search.m \
../../Telegraph/TLRPCmessages_searchStickerSets.m \
../../Telegraph/TLRPCmessages_sendInlineBotResult.m \
../../Telegraph/TLRPCmessages_sendMultiMedia.m \
../../Telegraph/TLSecureValue_secureValue.m \
../../Telegraph/TLStickerSet_stickerSet.m \
../../Telegraph/TLUpdate_updateChannelTooLong.m \
../../Telegraph/TLUpdate_updatePinnedDialogs.m \
../../Telegraph/TLUpdate_updateReadFeed.m \
../../Telegraph/TLUpdate_updateServiceNotification.m \
../../Telegraph/TLUpdates_modernUpdateShortChatMessage.m \
../../Telegraph/TLUpdates_modernUpdateShortMessage.m \
../../Telegraph/TLUpdates_updateShortSentMessage.m \
../../Telegraph/TLUpdates+TG.m \
../../Telegraph/TLUpdates_ChannelDifference_manual.m \
../../Telegraph/TLUser_modernUser.m \
../../Telegraph/TLUserFull_userFull.m \
../../Telegraph/TLWebPage_webPageExternal.m \
../../Telegraph/TLWebPage_manual.m \
../../Telegraph/TLaccount_AuthorizationForm_account_authorizationForm.m \
../../Telegraph/TLaccount_Password_account_password.m \
../../Telegraph/TLaccount_PasswordSettings_account_passwordSettings.m \
../../Telegraph/TLaccount_updateProfile_updateProfile.m \
../../Telegraph/TLauth_Authorization_auth_authorization.m \
../../Telegraph/TLauth_SentCode_auth_sentCode.m \
../../Telegraph/TLchannelDifferenceTooLong.m \
../../Telegraph/TLchannels_FeedSources_channels_feedSources.m \
../../Telegraph/TLhelp_AppUpdate_help_appUpdate.m \
../../Telegraph/TLhelp_DeepLinkInfo_help_deepLinkInfo.m \
../../Telegraph/TLhelp_ProxyData.m \
../../Telegraph/TLhelp_TermsOfService_help_termsOfService.m \
../../Telegraph/TLmessages_BotCallbackAnswer_botCallbackAnswer.m \
../../Telegraph/TLmessages_FeedMessages_messages_feedMessages.m \
../../Telegraph/TLmessages_Messages_modernChannelMessages.m \
../../Telegraph/TLpayments_PaymentForm_payments_paymentForm.m \
../../Telegraph/TLpayments_SavedInfo_payments_savedInfo.m \
../../Telegraph/TLpayments_ValidatedRequestedInfo_payments_validatedRequestedInfo.m \
../../Telegraph/TransformImageView.m \
../../Telegraph/UIViewController+Proxy.m \
../../Telegraph/emoji_suggestions.c \
../../Telegraph/emoji_suggestions_data.c \
../../Telegraph/quaternion.c \
../../Telegraph/thirdparty/diag_range.c \
../../Telegraph/thirdparty/ogg/ogg/bitwise.c \
../../Telegraph/thirdparty/ogg/ogg/framing.c \
../../Telegraph/thirdparty/opus_header.c \
../../Telegraph/thirdparty/opusenc.m \
../../Telegraph/thirdparty/opusenc/picture.c \
../../Telegraph/thirdparty/opusenc/wav_io.c \
../../Telegraph/thirdparty/opusfile/info.c \
../../Telegraph/thirdparty/opusfile/internal.c \
../../Telegraph/thirdparty/opusfile/opusfile.c \
../../Telegraph/thirdparty/opusfile/stream.c \
../../Watch/Bridge/TGBridgeActionMediaAttachment+TGActionMediaAttachment.m \
../../Watch/Bridge/TGBridgeActionMediaAttachment.m \
../../Watch/Bridge/TGBridgeAudioMediaAttachment+TGAudioMediaAttachment.m \
../../Watch/Bridge/TGBridgeAudioMediaAttachment.m \
../../Watch/Bridge/TGBridgeAudioSubscription.m \
../../Watch/Bridge/TGBridgeBotCommandInfo+TGBotCommandInfo.m \
../../Watch/Bridge/TGBridgeBotCommandInfo.m \
../../Watch/Bridge/TGBridgeBotInfo+TGBotInfo.m \
../../Watch/Bridge/TGBridgeBotInfo.m \
../../Watch/Bridge/TGBridgeBotReplyMarkup+TGBotReplyMarkup.m \
../../Watch/Bridge/TGBridgeBotReplyMarkup.m \
../../Watch/Bridge/TGBridgeChat+TGConversation.m \
../../Watch/Bridge/TGBridgeChat.m \
../../Watch/Bridge/TGBridgeChatListSubscription.m \
../../Watch/Bridge/TGBridgeChatMessageListSubscription.m \
../../Watch/Bridge/TGBridgeChatMessageListView+TGChatMessageListView.m \
../../Watch/Bridge/TGBridgeChatMessageListView.m \
../../Watch/Bridge/TGBridgeCommon.m \
../../Watch/Bridge/TGBridgeContactMediaAttachment+TGContactMediaAttachment.m \
../../Watch/Bridge/TGBridgeContactMediaAttachment.m \
../../Watch/Bridge/TGBridgeContactsSubscription.m \
../../Watch/Bridge/TGBridgeContext.m \
../../Watch/Bridge/TGBridgeConversationSubscription.m \
../../Watch/Bridge/TGBridgeDocumentMediaAttachment+TGDocumentMediaAttachment.m \
../../Watch/Bridge/TGBridgeDocumentMediaAttachment.m \
../../Watch/Bridge/TGBridgeForwardedMessageMediaAttachment+TGForwardedMessageMediaAttachment.m \
../../Watch/Bridge/TGBridgeForwardedMessageMediaAttachment.m \
../../Watch/Bridge/TGBridgeImageInfo+TGImageInfo.m \
../../Watch/Bridge/TGBridgeImageInfo.m \
../../Watch/Bridge/TGBridgeImageMediaAttachment+TGImageMediaAttachment.m \
../../Watch/Bridge/TGBridgeImageMediaAttachment.m \
../../Watch/Bridge/TGBridgeLocationMediaAttachment+TGLocationMediaAttachment.m \
../../Watch/Bridge/TGBridgeLocationMediaAttachment.m \
../../Watch/Bridge/TGBridgeLocationSubscription.m \
../../Watch/Bridge/TGBridgeLocationVenue+TGLocationVenue.m \
../../Watch/Bridge/TGBridgeLocationVenue.m \
../../Watch/Bridge/TGBridgeMediaAttachment+TGMediaAttachment.m \
../../Watch/Bridge/TGBridgeMediaAttachment.m \
../../Watch/Bridge/TGBridgeMediaSubscription.m \
../../Watch/Bridge/TGBridgeMessage+TGMessage.m \
../../Watch/Bridge/TGBridgeMessage.m \
../../Watch/Bridge/TGBridgeMessageEntities.m \
../../Watch/Bridge/TGBridgeMessageEntitiesAttachment+TGMessageEntitiesAttachment.m \
../../Watch/Bridge/TGBridgeMessageEntitiesAttachment.m \
../../Watch/Bridge/TGBridgeMessageEntity+TGMessageEntity.m \
../../Watch/Bridge/TGBridgePeerNotificationSettings+TGPeerNotificationSettings.m \
../../Watch/Bridge/TGBridgePeerNotificationSettings.m \
../../Watch/Bridge/TGBridgePeerSettingsSubscription.m \
../../Watch/Bridge/TGBridgeRemoteSubscription.m \
../../Watch/Bridge/TGBridgeReplyMarkupMediaAttachment+TGReplyMarkupAttachment.m \
../../Watch/Bridge/TGBridgeReplyMarkupMediaAttachment.m \
../../Watch/Bridge/TGBridgeReplyMessageMediaAttachment+TGReplyMessageMediaAttachment.m \
../../Watch/Bridge/TGBridgeReplyMessageMediaAttachment.m \
../../Watch/Bridge/TGBridgeResponse.m \
../../Watch/Bridge/TGBridgeSendMessageSubscription.m \
../../Watch/Bridge/TGBridgeStateSubscription.m \
../../Watch/Bridge/TGBridgeStickerPack+TGStickerPack.m \
../../Watch/Bridge/TGBridgeStickerPack.m \
../../Watch/Bridge/TGBridgeStickersSubscription.m \
../../Watch/Bridge/TGBridgeSubscription.m \
../../Watch/Bridge/TGBridgeUnsupportedMediaAttachment+TGUnsupportedMediaAttachment.m \
../../Watch/Bridge/TGBridgeUnsupportedMediaAttachment.m \
../../Watch/Bridge/TGBridgeUser+TGUser.m \
../../Watch/Bridge/TGBridgeUser.m \
../../Watch/Bridge/TGBridgeUserInfoSubscription.m \
../../Watch/Bridge/TGBridgeVideoMediaAttachment+TGVideoMediaAttachment.m \
../../Watch/Bridge/TGBridgeVideoMediaAttachment.m \
../../Watch/Bridge/TGBridgeWebPageMediaAttachment+TGWebPageMediaAttachment.m \
../../Watch/Bridge/TGBridgeWebPageMediaAttachment.m \
../../legacy/TL/MtProtoKit_Legacy.m \
../../legacy/TL/NSData+GZip.m \
../../legacy/TL/NSInputStream+TL.m \
../../legacy/TL/NSOutputStream+TL.m \
../../legacy/TL/TGZeroOutputStream.m \
../../legacy/TL/TL/NSArray_Authorization.m \
../../legacy/TL/TL/NSArray_BotCommand.m \
../../legacy/TL/TL/NSArray_BotInfo.m \
../../legacy/TL/TL/NSArray_BotInlineResult.m \
../../legacy/TL/TL/NSArray_CdnPublicKey.m \
../../legacy/TL/TL/NSArray_ChannelAdminLogEvent.m \
../../legacy/TL/TL/NSArray_ChannelParticipant.m \
../../legacy/TL/TL/NSArray_Chat.m \
../../legacy/TL/TL/NSArray_ChatParticipant.m \
../../legacy/TL/TL/NSArray_Contact.m \
../../legacy/TL/TL/NSArray_ContactBlocked.m \
../../legacy/TL/TL/NSArray_ContactLocated.m \
../../legacy/TL/TL/NSArray_ContactRequest.m \
../../legacy/TL/TL/NSArray_ContactStatus.m \
../../legacy/TL/TL/NSArray_ContactSuggested.m \
../../legacy/TL/TL/NSArray_DcNetworkStats.m \
../../legacy/TL/TL/NSArray_DcOption.m \
../../legacy/TL/TL/NSArray_DestroySessionRes.m \
../../legacy/TL/TL/NSArray_Dialog.m \
../../legacy/TL/TL/NSArray_DisabledFeature.m \
../../legacy/TL/TL/NSArray_Document.m \
../../legacy/TL/TL/NSArray_DocumentAttribute.m \
../../legacy/TL/TL/NSArray_EncryptedMessage.m \
../../legacy/TL/TL/NSArray_FileHash.m \
../../legacy/TL/TL/NSArray_FoundGif.m \
../../legacy/TL/TL/NSArray_HighScore.m \
../../legacy/TL/TL/NSArray_ImportedContact.m \
../../legacy/TL/TL/NSArray_InputChannel.m \
../../legacy/TL/TL/NSArray_InputContact.m \
../../legacy/TL/TL/NSArray_InputDocument.m \
../../legacy/TL/TL/NSArray_InputPeer.m \
../../legacy/TL/TL/NSArray_InputPhoto.m \
../../legacy/TL/TL/NSArray_InputPrivacyRule.m \
../../legacy/TL/TL/NSArray_InputUser.m \
../../legacy/TL/TL/NSArray_KeyboardButton.m \
../../legacy/TL/TL/NSArray_KeyboardButtonRow.m \
../../legacy/TL/TL/NSArray_LabeledPrice.m \
../../legacy/TL/TL/NSArray_LangPackLanguage.m \
../../legacy/TL/TL/NSArray_LangPackString.m \
../../legacy/TL/TL/NSArray_Message.m \
../../legacy/TL/TL/NSArray_MessageEntity.m \
../../legacy/TL/TL/NSArray_MessageRange.m \
../../legacy/TL/TL/NSArray_PageBlock.m \
../../legacy/TL/TL/NSArray_Peer.m \
../../legacy/TL/TL/NSArray_PhoneConnection.m \
../../legacy/TL/TL/NSArray_Photo.m \
../../legacy/TL/TL/NSArray_PhotoSize.m \
../../legacy/TL/TL/NSArray_PopularContact.m \
../../legacy/TL/TL/NSArray_PrivacyRule.m \
../../legacy/TL/TL/NSArray_ReceivedNotifyMessage.m \
../../legacy/TL/TL/NSArray_RichText.m \
../../legacy/TL/TL/NSArray_SchemeMethod.m \
../../legacy/TL/TL/NSArray_SchemeParam.m \
../../legacy/TL/TL/NSArray_SchemeType.m \
../../legacy/TL/TL/NSArray_SecureValue.m \
../../legacy/TL/TL/NSArray_ShippingOption.m \
../../legacy/TL/TL/NSArray_StickerPack.m \
../../legacy/TL/TL/NSArray_StickerSet.m \
../../legacy/TL/TL/NSArray_StickerSetCovered.m \
../../legacy/TL/TL/NSArray_TopPeer.m \
../../legacy/TL/TL/NSArray_TopPeerCategoryPeers.m \
../../legacy/TL/TL/NSArray_Update.m \
../../legacy/TL/TL/NSArray_User.m \
../../legacy/TL/TL/NSArray_WallPaper.m \
../../legacy/TL/TL/NSArray_int.m \
../../legacy/TL/TL/NSArray_long.m \
../../legacy/TL/TL/NSArray_string.m \
../../legacy/TL/TL/TLAccountDaysTTL.m \
../../legacy/TL/TL/TLAuthorization.m \
../../legacy/TL/TL/TLBadMsgNotification.m \
../../legacy/TL/TL/TLBotCommand.m \
../../legacy/TL/TL/TLBotInfo.m \
../../legacy/TL/TL/TLBotInlineMessage.m \
../../legacy/TL/TL/TLBotInlineResult.m \
../../legacy/TL/TL/TLCdnConfig.m \
../../legacy/TL/TL/TLCdnPublicKey.m \
../../legacy/TL/TL/TLChannelAdminLogEvent.m \
../../legacy/TL/TL/TLChannelAdminLogEventAction.m \
../../legacy/TL/TL/TLChannelAdminLogEventsFilter.m \
../../legacy/TL/TL/TLChannelAdminRights.m \
../../legacy/TL/TL/TLChannelBannedRights.m \
../../legacy/TL/TL/TLChannelMessagesFilter.m \
../../legacy/TL/TL/TLChannelParticipant.m \
../../legacy/TL/TL/TLChannelParticipantsFilter.m \
../../legacy/TL/TL/TLChat.m \
../../legacy/TL/TL/TLChatFull.m \
../../legacy/TL/TL/TLChatInvite.m \
../../legacy/TL/TL/TLChatLocated.m \
../../legacy/TL/TL/TLChatParticipant.m \
../../legacy/TL/TL/TLChatParticipants.m \
../../legacy/TL/TL/TLChatPhoto.m \
../../legacy/TL/TL/TLClient_DH_Inner_Data.m \
../../legacy/TL/TL/TLConfig.m \
../../legacy/TL/TL/TLContact.m \
../../legacy/TL/TL/TLContactBlocked.m \
../../legacy/TL/TL/TLContactLink.m \
../../legacy/TL/TL/TLContactLocated.m \
../../legacy/TL/TL/TLContactRequest.m \
../../legacy/TL/TL/TLContactStatus.m \
../../legacy/TL/TL/TLContactSuggested.m \
../../legacy/TL/TL/TLDataJSON.m \
../../legacy/TL/TL/TLDcNetworkStats.m \
../../legacy/TL/TL/TLDcOption.m \
../../legacy/TL/TL/TLDestroySessionRes.m \
../../legacy/TL/TL/TLDestroySessionsRes.m \
../../legacy/TL/TL/TLDialog.m \
../../legacy/TL/TL/TLDialogPeer.m \
../../legacy/TL/TL/TLDisabledFeature.m \
../../legacy/TL/TL/TLDocument.m \
../../legacy/TL/TL/TLDocumentAttribute.m \
../../legacy/TL/TL/TLDraftMessage.m \
../../legacy/TL/TL/TLEmbedPostMedia.m \
../../legacy/TL/TL/TLEncryptedChat.m \
../../legacy/TL/TL/TLEncryptedFile.m \
../../legacy/TL/TL/TLEncryptedMessage.m \
../../legacy/TL/TL/TLError.m \
../../legacy/TL/TL/TLExportedChatInvite.m \
../../legacy/TL/TL/TLExportedMessageLink.m \
../../legacy/TL/TL/TLFeedBroadcasts.m \
../../legacy/TL/TL/TLFeedPosition.m \
../../legacy/TL/TL/TLFileHash.m \
../../legacy/TL/TL/TLFileLocation.m \
../../legacy/TL/TL/TLFoundGif.m \
../../legacy/TL/TL/TLFutureSalt.m \
../../legacy/TL/TL/TLGame.m \
../../legacy/TL/TL/TLGeoPlaceName.m \
../../legacy/TL/TL/TLGeoPoint.m \
../../legacy/TL/TL/TLGlobalPrivacySettings.m \
../../legacy/TL/TL/TLHighScore.m \
../../legacy/TL/TL/TLHttpWait.m \
../../legacy/TL/TL/TLImportedContact.m \
../../legacy/TL/TL/TLInitConnection.m \
../../legacy/TL/TL/TLInlineBotSwitchPM.m \
../../legacy/TL/TL/TLInputBotInlineMessage.m \
../../legacy/TL/TL/TLInputBotInlineResult.m \
../../legacy/TL/TL/TLInputChannel.m \
../../legacy/TL/TL/TLInputChatPhoto.m \
../../legacy/TL/TL/TLInputCheckPasswordSRP.m \
../../legacy/TL/TL/TLInputContact.m \
../../legacy/TL/TL/TLInputDialogPeer.m \
../../legacy/TL/TL/TLInputDocument.m \
../../legacy/TL/TL/TLInputEncryptedChat.m \
../../legacy/TL/TL/TLInputEncryptedFile.m \
../../legacy/TL/TL/TLInputFile.m \
../../legacy/TL/TL/TLInputFileLocation.m \
../../legacy/TL/TL/TLInputGame.m \
../../legacy/TL/TL/TLInputGeoPlaceName.m \
../../legacy/TL/TL/TLInputGeoPoint.m \
../../legacy/TL/TL/TLInputMedia.m \
../../legacy/TL/TL/TLInputNotifyPeer.m \
../../legacy/TL/TL/TLInputPaymentCredentials.m \
../../legacy/TL/TL/TLInputPeer.m \
../../legacy/TL/TL/TLInputPeerNotifySettings.m \
../../legacy/TL/TL/TLInputPhoneCall.m \
../../legacy/TL/TL/TLInputPhoto.m \
../../legacy/TL/TL/TLInputPhotoCrop.m \
../../legacy/TL/TL/TLInputPrivacyKey.m \
../../legacy/TL/TL/TLInputPrivacyRule.m \
../../legacy/TL/TL/TLInputSecureFile.m \
../../legacy/TL/TL/TLInputSecureValue.m \
../../legacy/TL/TL/TLInputSingleMedia.m \
../../legacy/TL/TL/TLInputStickerSet.m \
../../legacy/TL/TL/TLInputStickeredMedia.m \
../../legacy/TL/TL/TLInputUser.m \
../../legacy/TL/TL/TLInputWebDocument.m \
../../legacy/TL/TL/TLInputWebFileLocation.m \
../../legacy/TL/TL/TLInvoice.m \
../../legacy/TL/TL/TLInvokeAfterMsg.m \
../../legacy/TL/TL/TLKeyboardButton.m \
../../legacy/TL/TL/TLKeyboardButtonRow.m \
../../legacy/TL/TL/TLLabeledPrice.m \
../../legacy/TL/TL/TLLangPackDifference.m \
../../legacy/TL/TL/TLLangPackLanguage.m \
../../legacy/TL/TL/TLLangPackString.m \
../../legacy/TL/TL/TLMaskCoords.m \
../../legacy/TL/TL/TLMessage.m \
../../legacy/TL/TL/TLMessageAction.m \
../../legacy/TL/TL/TLMessageEntity.m \
../../legacy/TL/TL/TLMessageFwdHeader.m \
../../legacy/TL/TL/TLMessageGroup.m \
../../legacy/TL/TL/TLMessageMedia.m \
../../legacy/TL/TL/TLMessageRange.m \
../../legacy/TL/TL/TLMessagesFilter.m \
../../legacy/TL/TL/TLMetaClassStore.m \
../../legacy/TL/TL/TLMetaScheme.m \
../../legacy/TL/TL/TLMetaSchemeData.m \
../../legacy/TL/TL/TLMsgDetailedInfo.m \
../../legacy/TL/TL/TLMsgResendReq.m \
../../legacy/TL/TL/TLMsgsAck.m \
../../legacy/TL/TL/TLMsgsAllInfo.m \
../../legacy/TL/TL/TLMsgsStateInfo.m \
../../legacy/TL/TL/TLMsgsStateReq.m \
../../legacy/TL/TL/TLNearestDc.m \
../../legacy/TL/TL/TLNewSession.m \
../../legacy/TL/TL/TLNotifyPeer.m \
../../legacy/TL/TL/TLP_Q_inner_data.m \
../../legacy/TL/TL/TLPage.m \
../../legacy/TL/TL/TLPageBlock.m \
../../legacy/TL/TL/TLPasswordKdfAlgo.m \
../../legacy/TL/TL/TLPaymentRequestedInfo.m \
../../legacy/TL/TL/TLPaymentSavedCredentials.m \
../../legacy/TL/TL/TLPeer.m \
../../legacy/TL/TL/TLPeerNotifySettings.m \
../../legacy/TL/TL/TLPeerSettings.m \
../../legacy/TL/TL/TLPhoneCall.m \
../../legacy/TL/TL/TLPhoneCallDiscardReason.m \
../../legacy/TL/TL/TLPhoneCallProtocol.m \
../../legacy/TL/TL/TLPhoneConnection.m \
../../legacy/TL/TL/TLPhoto.m \
../../legacy/TL/TL/TLPhotoSize.m \
../../legacy/TL/TL/TLPong.m \
../../legacy/TL/TL/TLPopularContact.m \
../../legacy/TL/TL/TLPostAddress.m \
../../legacy/TL/TL/TLPrivacyKey.m \
../../legacy/TL/TL/TLPrivacyRule.m \
../../legacy/TL/TL/TLProtoMessage.m \
../../legacy/TL/TL/TLProtoMessageCopy.m \
../../legacy/TL/TL/TLRPCaccount_changePhone.m \
../../legacy/TL/TL/TLRPCaccount_checkUsername.m \
../../legacy/TL/TL/TLRPCaccount_confirmPhone.m \
../../legacy/TL/TL/TLRPCaccount_deleteAccount.m \
../../legacy/TL/TL/TLRPCaccount_getAccountTTL.m \
../../legacy/TL/TL/TLRPCaccount_getAuthorizations.m \
../../legacy/TL/TL/TLRPCaccount_getNotifySettings.m \
../../legacy/TL/TL/TLRPCaccount_getPassword.m \
../../legacy/TL/TL/TLRPCaccount_getPasswordSettings.m \
../../legacy/TL/TL/TLRPCaccount_getPrivacy.m \
../../legacy/TL/TL/TLRPCaccount_getTmpPassword.m \
../../legacy/TL/TL/TLRPCaccount_getWallPapers.m \
../../legacy/TL/TL/TLRPCaccount_getWebAuthorizations.m \
../../legacy/TL/TL/TLRPCaccount_registerDevice.m \
../../legacy/TL/TL/TLRPCaccount_reportPeer.m \
../../legacy/TL/TL/TLRPCaccount_resetAuthorization.m \
../../legacy/TL/TL/TLRPCaccount_resetNotifySettings.m \
../../legacy/TL/TL/TLRPCaccount_resetWebAuthorization.m \
../../legacy/TL/TL/TLRPCaccount_resetWebAuthorizations.m \
../../legacy/TL/TL/TLRPCaccount_setAccountTTL.m \
../../legacy/TL/TL/TLRPCaccount_setPassword.m \
../../legacy/TL/TL/TLRPCaccount_setPrivacy.m \
../../legacy/TL/TL/TLRPCaccount_unregisterDevice.m \
../../legacy/TL/TL/TLRPCaccount_updateDeviceLocked.m \
../../legacy/TL/TL/TLRPCaccount_updateNotifySettings.m \
../../legacy/TL/TL/TLRPCaccount_updatePasswordSettings.m \
../../legacy/TL/TL/TLRPCaccount_updateStatus.m \
../../legacy/TL/TL/TLRPCaccount_updateUsername.m \
../../legacy/TL/TL/TLRPCauth_cancelCode.m \
../../legacy/TL/TL/TLRPCauth_checkPassword.m \
../../legacy/TL/TL/TLRPCauth_checkPhone.m \
../../legacy/TL/TL/TLRPCauth_exportAuthorization.m \
../../legacy/TL/TL/TLRPCauth_importAuthorization.m \
../../legacy/TL/TL/TLRPCauth_logOut.m \
../../legacy/TL/TL/TLRPCauth_recoverPassword.m \
../../legacy/TL/TL/TLRPCauth_requestPasswordRecovery.m \
../../legacy/TL/TL/TLRPCauth_resendCode.m \
../../legacy/TL/TL/TLRPCauth_resetAccountPassword.m \
../../legacy/TL/TL/TLRPCauth_resetAuthorizations.m \
../../legacy/TL/TL/TLRPCauth_sendInvites.m \
../../legacy/TL/TL/TLRPCauth_signIn.m \
../../legacy/TL/TL/TLRPCauth_signUp.m \
../../legacy/TL/TL/TLRPCchannels_checkUsername.m \
../../legacy/TL/TL/TLRPCchannels_createChannel.m \
../../legacy/TL/TL/TLRPCchannels_deleteChannel.m \
../../legacy/TL/TL/TLRPCchannels_deleteHistory.m \
../../legacy/TL/TL/TLRPCchannels_deleteMessages.m \
../../legacy/TL/TL/TLRPCchannels_deleteUserHistory.m \
../../legacy/TL/TL/TLRPCchannels_editAbout.m \
../../legacy/TL/TL/TLRPCchannels_editAdmin.m \
../../legacy/TL/TL/TLRPCchannels_editBanned.m \
../../legacy/TL/TL/TLRPCchannels_editPhoto.m \
../../legacy/TL/TL/TLRPCchannels_editTitle.m \
../../legacy/TL/TL/TLRPCchannels_exportInvite.m \
../../legacy/TL/TL/TLRPCchannels_exportMessageLink.m \
../../legacy/TL/TL/TLRPCchannels_getAdminLogMeta.m \
../../legacy/TL/TL/TLRPCchannels_getAdminedPublicChannels.m \
../../legacy/TL/TL/TLRPCchannels_getChannels.m \
../../legacy/TL/TL/TLRPCchannels_getFullChannel.m \
../../legacy/TL/TL/TLRPCchannels_getMessages.m \
../../legacy/TL/TL/TLRPCchannels_getParticipant.m \
../../legacy/TL/TL/TLRPCchannels_getParticipants.m \
../../legacy/TL/TL/TLRPCchannels_inviteToChannel.m \
../../legacy/TL/TL/TLRPCchannels_joinChannel.m \
../../legacy/TL/TL/TLRPCchannels_leaveChannel.m \
../../legacy/TL/TL/TLRPCchannels_readHistory.m \
../../legacy/TL/TL/TLRPCchannels_readMessageContents.m \
../../legacy/TL/TL/TLRPCchannels_reportSpam.m \
../../legacy/TL/TL/TLRPCchannels_searchFeed.m \
../../legacy/TL/TL/TLRPCchannels_setStickers.m \
../../legacy/TL/TL/TLRPCchannels_toggleInvites.m \
../../legacy/TL/TL/TLRPCchannels_togglePreHistoryHidden.m \
../../legacy/TL/TL/TLRPCchannels_toggleSignatures.m \
../../legacy/TL/TL/TLRPCchannels_updatePinnedMessage.m \
../../legacy/TL/TL/TLRPCchannels_updateUsername.m \
../../legacy/TL/TL/TLRPCcontacts_acceptRequest.m \
../../legacy/TL/TL/TLRPCcontacts_block.m \
../../legacy/TL/TL/TLRPCcontacts_clearContact.m \
../../legacy/TL/TL/TLRPCcontacts_declineRequest.m \
../../legacy/TL/TL/TLRPCcontacts_deleteContact.m \
../../legacy/TL/TL/TLRPCcontacts_deleteContacts.m \
../../legacy/TL/TL/TLRPCcontacts_getBlocked.m \
../../legacy/TL/TL/TLRPCcontacts_getContactIDs.m \
../../legacy/TL/TL/TLRPCcontacts_getContacts.m \
../../legacy/TL/TL/TLRPCcontacts_getLink.m \
../../legacy/TL/TL/TLRPCcontacts_getLocated.m \
../../legacy/TL/TL/TLRPCcontacts_getRequests.m \
../../legacy/TL/TL/TLRPCcontacts_getStatuses.m \
../../legacy/TL/TL/TLRPCcontacts_getSuggested.m \
../../legacy/TL/TL/TLRPCcontacts_getTopPeers.m \
../../legacy/TL/TL/TLRPCcontacts_importContacts.m \
../../legacy/TL/TL/TLRPCcontacts_resetSaved.m
