libuofs4_FILES = ../../legacy/TL/TL/TLRPCmessages_sendBroadcast.mm \
../../legacy/TL/TL/TLRPCmessages_sendEncrypted.mm \
../../legacy/TL/TL/TLRPCmessages_sendEncryptedFile.mm \
../../legacy/TL/TL/TLRPCmessages_sendEncryptedService.mm \
../../legacy/TL/TL/TLRPCmessages_sendScreenshotNotification.mm \
../../legacy/TL/TL/TLRPCmessages_setEncryptedTyping.mm \
../../legacy/TL/TL/TLRPCmessages_setTyping.mm \
../../legacy/TL/TL/TLRPCmessages_startBot.mm \
../../legacy/TL/TL/TLRPCmessages_toggleChatAdmins.mm \
../../legacy/TL/TL/TLRPCmessages_toggleDialogPin.mm \
../../legacy/TL/TL/TLRPCmessages_uninstallStickerSet.mm \
../../legacy/TL/TL/TLRPCmessages_uploadMedia.mm \
../../legacy/TL/TL/TLRPCpayments_clearSavedInfo.mm \
../../legacy/TL/TL/TLRPCpayments_getPaymentForm.mm \
../../legacy/TL/TL/TLRPCpayments_getPaymentReceipt.mm \
../../legacy/TL/TL/TLRPCpayments_getSavedInfo.mm \
../../legacy/TL/TL/TLRPCpayments_validateRequestedInfo.mm \
../../legacy/TL/TL/TLRPCphone_acceptCall.mm \
../../legacy/TL/TL/TLRPCphone_confirmCall.mm \
../../legacy/TL/TL/TLRPCphone_declineCall.mm \
../../legacy/TL/TL/TLRPCphone_discardCall.mm \
../../legacy/TL/TL/TLRPCphone_getCallConfig.mm \
../../legacy/TL/TL/TLRPCphone_getDhConfig.mm \
../../legacy/TL/TL/TLRPCphone_receivedCall.mm \
../../legacy/TL/TL/TLRPCphone_requestCall.mm \
../../legacy/TL/TL/TLRPCphone_saveCallDebug.mm \
../../legacy/TL/TL/TLRPCphone_setCallRating.mm \
../../legacy/TL/TL/TLRPCphotos_deletePhotos.mm \
../../legacy/TL/TL/TLRPCphotos_editPhoto.mm \
../../legacy/TL/TL/TLRPCphotos_getPhotos.mm \
../../legacy/TL/TL/TLRPCphotos_getUserPhotos.mm \
../../legacy/TL/TL/TLRPCphotos_getWall.mm \
../../legacy/TL/TL/TLRPCphotos_readWall.mm \
../../legacy/TL/TL/TLRPCphotos_restorePhotos.mm \
../../legacy/TL/TL/TLRPCphotos_updateProfilePhoto.mm \
../../legacy/TL/TL/TLRPCphotos_uploadPhoto.mm \
../../legacy/TL/TL/TLRPCphotos_uploadProfilePhoto.mm \
../../legacy/TL/TL/TLRPCping.mm \
../../legacy/TL/TL/TLRPCping_delay_disconnect.mm \
../../legacy/TL/TL/TLRPCreq_DH_params.mm \
../../legacy/TL/TL/TLRPCreq_pq.mm \
../../legacy/TL/TL/TLRPCrpc_drop_answer.mm \
../../legacy/TL/TL/TLRPCset_client_DH_params.mm \
../../legacy/TL/TL/TLRPCupdates_getChannelDifference.mm \
../../legacy/TL/TL/TLRPCupdates_getDifference.mm \
../../legacy/TL/TL/TLRPCupdates_getState.mm \
../../legacy/TL/TL/TLRPCupdates_subscribe.mm \
../../legacy/TL/TL/TLRPCupdates_unsubscribe.mm \
../../legacy/TL/TL/TLRPCupload_getCdnFile.mm \
../../legacy/TL/TL/TLRPCupload_getCdnFileHashes.mm \
../../legacy/TL/TL/TLRPCupload_getFile.mm \
../../legacy/TL/TL/TLRPCupload_getWebFile.mm \
../../legacy/TL/TL/TLRPCupload_reuploadCdnFile.mm \
../../legacy/TL/TL/TLRPCupload_saveBigFilePart.mm \
../../legacy/TL/TL/TLRPCupload_saveFilePart.mm \
../../legacy/TL/TL/TLRPCusers_getFullUser.mm \
../../legacy/TL/TL/TLRPCusers_getUsers.mm \
../../legacy/TL/TL/TLReceivedNotifyMessage.mm \
../../legacy/TL/TL/TLReplyMarkup.mm \
../../legacy/TL/TL/TLReportReason.mm \
../../legacy/TL/TL/TLResPQ.mm \
../../legacy/TL/TL/TLResponseIndirect.mm \
../../legacy/TL/TL/TLRichText.mm \
../../legacy/TL/TL/TLRpcDropAnswer.mm \
../../legacy/TL/TL/TLRpcError.mm \
../../legacy/TL/TL/TLScheme.mm \
../../legacy/TL/TL/TLSchemeMethod.mm \
../../legacy/TL/TL/TLSchemeParam.mm \
../../legacy/TL/TL/TLSchemeType.mm \
../../legacy/TL/TL/TLSecureCredentialsEncrypted.mm \
../../legacy/TL/TL/TLSecureData.mm \
../../legacy/TL/TL/TLSecureFile.mm \
../../legacy/TL/TL/TLSecurePasswordKdfAlgo.mm \
../../legacy/TL/TL/TLSecurePlainData.mm \
../../legacy/TL/TL/TLSecureRequiredType.mm \
../../legacy/TL/TL/TLSecureSecretSettings.mm \
../../legacy/TL/TL/TLSecureValue.mm \
../../legacy/TL/TL/TLSecureValueError.mm \
../../legacy/TL/TL/TLSecureValueHash.mm \
../../legacy/TL/TL/TLSecureValueType.mm \
../../legacy/TL/TL/TLSendMessageAction.mm \
../../legacy/TL/TL/TLServer_DH_Params.mm \
../../legacy/TL/TL/TLServer_DH_inner_data.mm \
../../legacy/TL/TL/TLSet_client_DH_params_answer.mm \
../../legacy/TL/TL/TLShippingOption.mm \
../../legacy/TL/TL/TLStickerPack.mm \
../../legacy/TL/TL/TLStickerSet.mm \
../../legacy/TL/TL/TLStickerSetCovered.mm \
../../legacy/TL/TL/TLTopPeer.mm \
../../legacy/TL/TL/TLTopPeerCategory.mm \
../../legacy/TL/TL/TLTopPeerCategoryPeers.mm \
../../legacy/TL/TL/TLUpdate.mm \
../../legacy/TL/TL/TLUpdates.mm \
../../legacy/TL/TL/TLUser.mm \
../../legacy/TL/TL/TLUserFull.mm \
../../legacy/TL/TL/TLUserProfilePhoto.mm \
../../legacy/TL/TL/TLUserStatus.mm \
../../legacy/TL/TL/TLWallPaper.mm \
../../legacy/TL/TL/TLWebAuthorization.mm \
../../legacy/TL/TL/TLWebDocument.mm \
../../legacy/TL/TL/TLWebPage.mm \
../../legacy/TL/TL/TLaccount_AuthorizationForm.mm \
../../legacy/TL/TL/TLaccount_Authorizations.mm \
../../legacy/TL/TL/TLaccount_Password.mm \
../../legacy/TL/TL/TLaccount_PasswordInputSettings.mm \
../../legacy/TL/TL/TLaccount_PasswordSettings.mm \
../../legacy/TL/TL/TLaccount_PrivacyRules.mm \
../../legacy/TL/TL/TLaccount_SentEmailCode.mm \
../../legacy/TL/TL/TLaccount_TmpPassword.mm \
../../legacy/TL/TL/TLaccount_WebAuthorizations.mm \
../../legacy/TL/TL/TLauth_Authorization.mm \
../../legacy/TL/TL/TLauth_CheckedPhone.mm \
../../legacy/TL/TL/TLauth_CodeType.mm \
../../legacy/TL/TL/TLauth_ExportedAuthorization.mm \
../../legacy/TL/TL/TLauth_PasswordRecovery.mm \
../../legacy/TL/TL/TLauth_SentCode.mm \
../../legacy/TL/TL/TLauth_SentCodeType.mm \
../../legacy/TL/TL/TLchannels_AdminLogResults.mm \
../../legacy/TL/TL/TLchannels_ChannelParticipant.mm \
../../legacy/TL/TL/TLchannels_ChannelParticipants.mm \
../../legacy/TL/TL/TLchannels_FeedSources.mm \
../../legacy/TL/TL/TLcontacts_Blocked.mm \
../../legacy/TL/TL/TLcontacts_Contacts.mm \
../../legacy/TL/TL/TLcontacts_ForeignLink.mm \
../../legacy/TL/TL/TLcontacts_Found.mm \
../../legacy/TL/TL/TLcontacts_ImportedContacts.mm \
../../legacy/TL/TL/TLcontacts_Link.mm \
../../legacy/TL/TL/TLcontacts_Located.mm \
../../legacy/TL/TL/TLcontacts_MyLink.mm \
../../legacy/TL/TL/TLcontacts_Requests.mm \
../../legacy/TL/TL/TLcontacts_ResolvedPeer.mm \
../../legacy/TL/TL/TLcontacts_SentLink.mm \
../../legacy/TL/TL/TLcontacts_Suggested.mm \
../../legacy/TL/TL/TLcontacts_TopPeers.mm \
../../legacy/TL/TL/TLhelp_AppChangelog.mm \
../../legacy/TL/TL/TLhelp_AppPrefs.mm \
../../legacy/TL/TL/TLhelp_AppUpdate.mm \
../../legacy/TL/TL/TLhelp_DeepLinkInfo.mm \
../../legacy/TL/TL/TLhelp_InviteText.mm \
../../legacy/TL/TL/TLhelp_PassportConfig.mm \
../../legacy/TL/TL/TLhelp_Support.mm \
../../legacy/TL/TL/TLhelp_TermsOfService.mm \
../../legacy/TL/TL/TLhelp_TermsOfServiceUpdate.mm \
../../legacy/TL/TL/TLmessages_AffectedHistory.mm \
../../legacy/TL/TL/TLmessages_AffectedMessages.mm \
../../legacy/TL/TL/TLmessages_AllStickers.mm \
../../legacy/TL/TL/TLmessages_ArchivedStickers.mm \
../../legacy/TL/TL/TLmessages_BotCallbackAnswer.mm \
../../legacy/TL/TL/TLmessages_BotResults.mm \
../../legacy/TL/TL/TLmessages_Chat.mm \
../../legacy/TL/TL/TLmessages_ChatFull.mm \
../../legacy/TL/TL/TLmessages_Chats.mm \
../../legacy/TL/TL/TLmessages_DhConfig.mm \
../../legacy/TL/TL/TLmessages_Dialogs.mm \
../../legacy/TL/TL/TLmessages_FavedStickers.mm \
../../legacy/TL/TL/TLmessages_FeaturedStickers.mm \
../../legacy/TL/TL/TLmessages_FeedMessages.mm \
../../legacy/TL/TL/TLmessages_FoundGifs.mm \
../../legacy/TL/TL/TLmessages_FoundStickerSets.mm \
../../legacy/TL/TL/TLmessages_HighScores.mm \
../../legacy/TL/TL/TLmessages_Message.mm \
../../legacy/TL/TL/TLmessages_MessageEditData.mm \
../../legacy/TL/TL/TLmessages_Messages.mm \
../../legacy/TL/TL/TLmessages_PeerDialogs.mm \
../../legacy/TL/TL/TLmessages_RecentStickers.mm \
../../legacy/TL/TL/TLmessages_SavedGifs.mm \
../../legacy/TL/TL/TLmessages_SentEncryptedMessage.mm \
../../legacy/TL/TL/TLmessages_StickerSet.mm \
../../legacy/TL/TL/TLmessages_StickerSetInstallResult.mm \
../../legacy/TL/TL/TLmessages_Stickers.mm \
../../legacy/TL/TL/TLpayments_PaymentForm.mm \
../../legacy/TL/TL/TLpayments_PaymentReceipt.mm \
../../legacy/TL/TL/TLpayments_PaymentResult.mm \
../../legacy/TL/TL/TLpayments_SavedInfo.mm \
../../legacy/TL/TL/TLpayments_ValidatedRequestedInfo.mm \
../../legacy/TL/TL/TLphone_DhConfig.mm \
../../legacy/TL/TL/TLphone_DiscardedCall.mm \
../../legacy/TL/TL/TLphone_PhoneCall.mm \
../../legacy/TL/TL/TLphotos_Photo.mm \
../../legacy/TL/TL/TLphotos_Photos.mm \
../../legacy/TL/TL/TLstorage_FileType.mm \
../../legacy/TL/TL/TLupdates_ChannelDifference.mm \
../../legacy/TL/TL/TLupdates_Difference.mm \
../../legacy/TL/TL/TLupdates_State.mm \
../../legacy/TL/TL/TLupload_CdnFile.mm \
../../legacy/TL/TL/TLupload_File.mm \
../../legacy/TL/TL/TLupload_WebFile.mm \
../../legacy/TL/TLBool.m \
../../legacy/TL/TLCompressedObject.mm \
../../legacy/TL/TLDestroySessionsRes_manual.mm \
../../legacy/TL/TLFutureSalts.mm \
../../legacy/TL/TLMessageContainer.mm \
../../legacy/TL/TLMetaConstructor.mm \
../../legacy/TL/TLMetaObject.mm \
../../legacy/TL/TLMetaRpc.mm \
../../legacy/TL/TLMetaType.mm \
../../legacy/TL/TLMsgsAck_msgs_ack_manual.m \
../../legacy/TL/TLObject.mm \
../../legacy/TL/TLRPCmessages_sendMedia_manual.mm \
../../legacy/TL/TLRPCmessages_sendMessage_manual.mm \
../../legacy/TL/TLResPQ_resPQ_manual.m \
../../legacy/TL/TLRpcResult.mm \
../../legacy/TL/TLSerializationContext.m \
../../legacy/TL/TLUpdate_updateChangePts.m \
../../legacy/TL/TLaccount_PasswordInputSettings_manual.mm \
../../legacy/TelegraphKit/TGAcceptEncryptionFutureAction.m \
../../legacy/TelegraphKit/TGActionTableView.m \
../../legacy/TelegraphKit/TGAlertView.m \
../../legacy/TelegraphKit/TGAudioInfo.m \
../../legacy/TelegraphKit/TGButton.m \
../../legacy/TelegraphKit/TGButtonGroupView.m \
../../legacy/TelegraphKit/TGChangeNotificationSettingsFutureAction.m \
../../legacy/TelegraphKit/TGChangePasslockSettingsFutureAction.m \
../../legacy/TelegraphKit/TGChangePeerBlockStatusFutureAction.m \
../../legacy/TelegraphKit/TGChangePrivacySettingsFutureAction.m \
../../legacy/TelegraphKit/TGCircularProgressView.m \
../../legacy/TelegraphKit/TGClearNotificationsFutureAction.m \
../../legacy/TelegraphKit/TGCommon.m \
../../legacy/TelegraphKit/TGContactBinding.m \
../../legacy/TelegraphKit/TGDatabase.mm \
../../legacy/TelegraphKit/TGDateLabel.m \
../../legacy/TelegraphKit/TGDeleteProfilePhotoFutureAction.m \
../../legacy/TelegraphKit/TGDialogListBroadcastsMenuCell.m \
../../legacy/TelegraphKit/TGDialogListCell.m \
../../legacy/TelegraphKit/TGDialogListCompanion.m \
../../legacy/TelegraphKit/TGDialogListController.mm \
../../legacy/TelegraphKit/TGDialogListMessageSearchCell.m \
../../legacy/TelegraphKit/TGDialogListSearchCell.m \
../../legacy/TelegraphKit/TGDownloadManager.mm \
../../legacy/TelegraphKit/TGEncryptedChatServiceAction.m \
../../legacy/TelegraphKit/TGExportContactFutureAction.m \
../../legacy/TelegraphKit/TGFutureAction.m \
../../legacy/TelegraphKit/TGHighlightableButton.m \
../../legacy/TelegraphKit/TGImageTransitionHelper.m \
../../legacy/TelegraphKit/TGIndexSet.mm \
../../legacy/TelegraphKit/TGLinearProgressView.m \
../../legacy/TelegraphKit/TGMimeTypeMap.m \
../../legacy/TelegraphKit/TGPagerView.m \
../../legacy/TelegraphKit/TGPhonebookContact.mm \
../../legacy/TelegraphKit/TGRemoveContactFutureAction.m \
../../legacy/TelegraphKit/TGReusableLabel.mm \
../../legacy/TelegraphKit/TGSharedPtrWrapper.mm \
../../legacy/TelegraphKit/TGSwitchView.m \
../../legacy/TelegraphKit/TGSynchronizeEncryptedChatSettingsFutureAction.m \
../../legacy/TelegraphKit/TGTableView.m \
../../legacy/TelegraphKit/TGTableViewCell.m \
../../legacy/TelegraphKit/TGToolbar.m \
../../legacy/TelegraphKit/TGTransitionableImageView.m \
../../legacy/TelegraphKit/TGUpdatePeerLayerFutureAction.m \
../../legacy/TelegraphKit/TGUploadAvatarFutureAction.m \
../../legacy/TelegraphKit/TGView.m \
../../legacy/TelegraphKit/TelegraphKit.m \
../../legacy/TelegraphKit/Third-Party/FMDB/FMDatabase.m \
../../legacy/TelegraphKit/Third-Party/FMDB/FMDatabaseAdditions.m \
../../legacy/TelegraphKit/Third-Party/FMDB/FMResultSet.m \
../../legacy/TelegraphKit/UIImage+ImageEffects.m \
../../thirdparty/RMIntro/core/animations.c \
../../thirdparty/RMIntro/core/buffer.c \
../../thirdparty/RMIntro/core/objects.c \
../../thirdparty/RMIntro/core/program.c \
../../thirdparty/RMIntro/core/rngs.c \
../../thirdparty/RMIntro/core/shader.c \
../../thirdparty/RMIntro/core/timing.c \
../../thirdparty/RMIntro/platform/common/platform_log.c \
../../thirdparty/RMIntro/platform/ios/RMGeometry.m \
../../thirdparty/RMIntro/platform/ios/RMIntroPageView.m \
../../thirdparty/RMIntro/platform/ios/RMIntroViewController.m \
../../thirdparty/RMIntro/platform/ios/texture_helper.m \
../../thirdparty/Reachability.m \
../../thirdparty/Stripe/NSArray+Stripe_BoundSafe.m \
../../thirdparty/Stripe/NSBundle+Stripe_AppName.m \
../../thirdparty/Stripe/NSDecimalNumber+Stripe_Currency.m \
../../thirdparty/Stripe/NSDictionary+Stripe.m \
../../thirdparty/Stripe/NSMutableURLRequest+Stripe.m \
../../thirdparty/Stripe/NSString+Stripe.m \
../../thirdparty/Stripe/NSString+Stripe_CardBrands.m \
../../thirdparty/Stripe/PKPayment+Stripe.m \
../../thirdparty/Stripe/PKPaymentAuthorizationViewController+Stripe_Blocks.m \
../../thirdparty/Stripe/STPAPIClient+ApplePay.m \
../../thirdparty/Stripe/STPAPIClient.m \
../../thirdparty/Stripe/STPAPIPostRequest.m \
../../thirdparty/Stripe/STPAddCardViewController.m \
../../thirdparty/Stripe/STPAddress.m \
../../thirdparty/Stripe/STPAddressFieldTableViewCell.m \
../../thirdparty/Stripe/STPAddressViewModel.m \
../../thirdparty/Stripe/STPAnalyticsClient.m \
../../thirdparty/Stripe/STPApplePayPaymentMethod.m \
../../thirdparty/Stripe/STPAspects.m \
../../thirdparty/Stripe/STPBINRange.m \
../../thirdparty/Stripe/STPBankAccount.m \
../../thirdparty/Stripe/STPBankAccountParams.m \
../../thirdparty/Stripe/STPBundleLocator.m \
../../thirdparty/Stripe/STPCard.m \
../../thirdparty/Stripe/STPCardParams.m \
../../thirdparty/Stripe/STPCardTuple.m \
../../thirdparty/Stripe/STPCardValidator.m \
../../thirdparty/Stripe/STPCategoryLoader.m \
../../thirdparty/Stripe/STPCheckoutAPIClient.m \
../../thirdparty/Stripe/STPCheckoutAPIVerification.m \
../../thirdparty/Stripe/STPCheckoutAccount.m \
../../thirdparty/Stripe/STPCheckoutAccountLookup.m \
../../thirdparty/Stripe/STPCheckoutBootstrapResponse.m \
../../thirdparty/Stripe/STPColorUtils.m \
../../thirdparty/Stripe/STPCustomer.m \
../../thirdparty/Stripe/STPDelegateProxy.m \
../../thirdparty/Stripe/STPDispatchFunctions.m \
../../thirdparty/Stripe/STPEmailAddressValidator.m \
../../thirdparty/Stripe/STPFormEncoder.m \
../../thirdparty/Stripe/STPFormTextField.m \
../../thirdparty/Stripe/STPImageLibrary.m \
../../thirdparty/Stripe/STPLocalizationUtils.m \
../../thirdparty/Stripe/STPObscuredCardView.m \
../../thirdparty/Stripe/STPPaymentActivityIndicatorView.m \
../../thirdparty/Stripe/STPPaymentCardTextField.m \
../../thirdparty/Stripe/STPPaymentCardTextFieldViewModel.m \
../../thirdparty/Stripe/STPPaymentConfiguration.m \
../../thirdparty/Stripe/STPPaymentContext.m \
../../thirdparty/Stripe/STPPaymentContextAmountModel.m \
../../thirdparty/Stripe/STPPaymentMethodTableViewCell.m \
../../thirdparty/Stripe/STPPaymentMethodTuple.m \
../../thirdparty/Stripe/STPPaymentMethodsInternalViewController.m \
../../thirdparty/Stripe/STPPaymentMethodsViewController.m \
../../thirdparty/Stripe/STPPaymentResult.m \
../../thirdparty/Stripe/STPPhoneNumberValidator.m \
../../thirdparty/Stripe/STPPostalCodeValidator.m \
../../thirdparty/Stripe/STPPromise.m \
../../thirdparty/Stripe/STPRememberMeEmailCell.m \
../../thirdparty/Stripe/STPRememberMePaymentCell.m \
../../thirdparty/Stripe/STPRememberMeTermsView.m \
../../thirdparty/Stripe/STPSMSCodeTextField.m \
../../thirdparty/Stripe/STPSMSCodeViewController.m \
../../thirdparty/Stripe/STPStringUtils.m \
../../thirdparty/Stripe/STPSwitchTableViewCell.m \
../../thirdparty/Stripe/STPTheme.m \
../../thirdparty/Stripe/STPToken.m \
../../thirdparty/Stripe/STPUserInformation.m \
../../thirdparty/Stripe/STPWebViewController.m \
../../thirdparty/Stripe/StripeError.m \
../../thirdparty/Stripe/UIBarButtonItem+Stripe.m \
../../thirdparty/Stripe/UINavigationBar+Stripe_Theme.m \
../../thirdparty/Stripe/UINavigationController+Stripe_Completion.m \
../../thirdparty/Stripe/UITableViewCell+Stripe_Borders.m \
../../thirdparty/Stripe/UIToolbar+Stripe_InputAccessory.m \
../../thirdparty/Stripe/UIView+Stripe_FirstResponder.m \
../../thirdparty/UIImage+WebP.m \
../../thirdparty/VideoEncoder/MP4Atom.m \
../../thirdparty/lz4/lz4.c \
../../thirdparty/lz4/lz4frame.c \
../../thirdparty/lz4/lz4hc.c \
../../thirdparty/lz4/xxhash.c \
../../thirdparty/sqlcipher/sqlite3.c \
../../submodules/MtProtoKit/MTProtoKit/MTApiEnvironment.m \
../../submodules/MtProtoKit/MTProtoKit/MTBadMsgNotificationMessage.m \
../../submodules/MtProtoKit/MTProtoKit/MTBuffer.m \
../../submodules/MtProtoKit/MTProtoKit/MTBufferReader.m \
../../submodules/MtProtoKit/MTProtoKit/MTContext.m \
../../submodules/MtProtoKit/MTProtoKit/MTDatacenterAddress.m \
../../submodules/MtProtoKit/MTProtoKit/MTDatacenterAddressListData.m \
../../submodules/MtProtoKit/MTProtoKit/MTDatacenterAddressSet.m \
../../submodules/MtProtoKit/MTProtoKit/MTDatacenterAuthAction.m \
../../submodules/MtProtoKit/MTProtoKit/MTDatacenterAuthInfo.m \
../../submodules/MtProtoKit/MTProtoKit/MTDatacenterAuthMessageService.m \
../../submodules/MtProtoKit/MTProtoKit/MTDatacenterSaltInfo.m \
../../submodules/MtProtoKit/MTProtoKit/MTDatacenterTransferAuthAction.m \
../../submodules/MtProtoKit/MTProtoKit/MTDestroySessionResponseMessage.m \
../../submodules/MtProtoKit/MTProtoKit/MTDiscoverDatacenterAddressAction.m \
../../submodules/MtProtoKit/MTProtoKit/MTDropResponseContext.m \
../../submodules/MtProtoKit/MTProtoKit/MTDropRpcResultMessage.m \
../../submodules/MtProtoKit/MTProtoKit/MTEncryption.m \
../../submodules/MtProtoKit/MTProtoKit/MTExportedAuthorizationData.m \
../../submodules/MtProtoKit/MTProtoKit/MTFileBasedKeychain.m \
../../submodules/MtProtoKit/MTProtoKit/MTFutureSaltsMessage.m \
../../submodules/MtProtoKit/MTProtoKit/MTHttpRequestOperation.m \
../../submodules/MtProtoKit/MTProtoKit/MTHttpTransport.m \
../../submodules/MtProtoKit/MTProtoKit/MTHttpWorker.m \
../../submodules/MtProtoKit/MTProtoKit/MTHttpWorkerBehaviour.m \
../../submodules/MtProtoKit/MTProtoKit/MTIncomingMessage.m \
../../submodules/MtProtoKit/MTProtoKit/MTInputStream.m \
../../submodules/MtProtoKit/MTProtoKit/MTInternalMessageParser.m \
../../submodules/MtProtoKit/MTProtoKit/MTKeychain.m \
../../submodules/MtProtoKit/MTProtoKit/MTLogging.m \
../../submodules/MtProtoKit/MTProtoKit/MTMessage.m \
../../submodules/MtProtoKit/MTProtoKit/MTMessageEncryptionKey.m \
../../submodules/MtProtoKit/MTProtoKit/MTMessageTransaction.m \
../../submodules/MtProtoKit/MTProtoKit/MTMsgAllInfoMessage.m \
../../submodules/MtProtoKit/MTProtoKit/MTMsgContainerMessage.m \
../../submodules/MtProtoKit/MTProtoKit/MTMsgDetailedInfoMessage.m \
../../submodules/MtProtoKit/MTProtoKit/MTMsgResendReqMessage.m \
../../submodules/MtProtoKit/MTProtoKit/MTMsgsAckMessage.m \
../../submodules/MtProtoKit/MTProtoKit/MTMsgsStateInfoMessage.m \
../../submodules/MtProtoKit/MTProtoKit/MTMsgsStateReqMessage.m \
../../submodules/MtProtoKit/MTProtoKit/MTNetworkAvailability.m \
../../submodules/MtProtoKit/MTProtoKit/MTNewSessionCreatedMessage.m \
../../submodules/MtProtoKit/MTProtoKit/MTOutgoingMessage.m \
../../submodules/MtProtoKit/MTProtoKit/MTOutputStream.m \
../../submodules/MtProtoKit/MTProtoKit/MTPingMessage.m \
../../submodules/MtProtoKit/MTProtoKit/MTPongMessage.m \
../../submodules/MtProtoKit/MTProtoKit/MTPreparedMessage.m \
../../submodules/MtProtoKit/MTProtoKit/MTProto.m \
../../submodules/MtProtoKit/MTProtoKit/MTQueue.m \
../../submodules/MtProtoKit/MTProtoKit/MTRequest.m \
../../submodules/MtProtoKit/MTProtoKit/MTRequestContext.m \
../../submodules/MtProtoKit/MTProtoKit/MTRequestErrorContext.m \
../../submodules/MtProtoKit/MTProtoKit/MTRequestMessageService.m \
../../submodules/MtProtoKit/MTProtoKit/MTResendMessageService.m \
../../submodules/MtProtoKit/MTProtoKit/MTResPqMessage.m \
../../submodules/MtProtoKit/MTProtoKit/MTRpcError.m \
../../submodules/MtProtoKit/MTProtoKit/MTRpcResultMessage.m \
../../submodules/MtProtoKit/MTProtoKit/MTServerDhInnerDataMessage.m \
../../submodules/MtProtoKit/MTProtoKit/MTServerDhParamsMessage.m \
../../submodules/MtProtoKit/MTProtoKit/MTSessionInfo.m \
../../submodules/MtProtoKit/MTProtoKit/MTSetClientDhParamsResponseMessage.m \
../../submodules/MtProtoKit/MTProtoKit/MTTcpConnection.m \
../../submodules/MtProtoKit/MTProtoKit/MTTcpConnectionBehaviour.m \
../../submodules/MtProtoKit/MTProtoKit/MTTcpTransport.m \
../../submodules/MtProtoKit/MTProtoKit/MTTime.m \
../../submodules/MtProtoKit/MTProtoKit/MTTimeFixContext.m \
../../submodules/MtProtoKit/MTProtoKit/MTTimer.m \
../../submodules/MtProtoKit/MTProtoKit/MTTimeSyncMessageService.m \
../../submodules/MtProtoKit/MTProtoKit/MTTransport.m \
../../submodules/MtProtoKit/MTProtoKit/MTTransportScheme.m \
../../submodules/MtProtoKit/MTProtoKit/MTTransportTransaction.m \
../../submodules/LegacyComponents/LegacyComponents/ActionStage.mm \
../../submodules/LegacyComponents/LegacyComponents/ASActor.m \
../../submodules/LegacyComponents/LegacyComponents/ASHandle.m \
../../submodules/LegacyComponents/LegacyComponents/ASQueue.m \
../../submodules/LegacyComponents/LegacyComponents/AVAsset+CBExtension.m \
../../submodules/LegacyComponents/LegacyComponents/AVURLAsset+TGMediaItem.m \
../../submodules/LegacyComponents/LegacyComponents/CBAssetDownloadManager.m \
../../submodules/LegacyComponents/LegacyComponents/CBChunkDownloadOperation.m \
../../submodules/LegacyComponents/LegacyComponents/CBConstance.m \
../../submodules/LegacyComponents/LegacyComponents/CBCoubAudioSource.m \
../../submodules/LegacyComponents/LegacyComponents/CBCoubAuthorVO.m \
../../submodules/LegacyComponents/LegacyComponents/CBCoubDownloadOperation.m \
../../submodules/LegacyComponents/LegacyComponents/CBCoubLoopCompositionMaker.m \
../../submodules/LegacyComponents/LegacyComponents/CBCoubNew.m \
../../submodules/LegacyComponents/LegacyComponents/CBCoubPlayer.m \
../../submodules/LegacyComponents/LegacyComponents/CBCoubPlayerContance.m \
../../submodules/LegacyComponents/LegacyComponents/CBCoubVideoSource.m \
../../submodules/LegacyComponents/LegacyComponents/CBGenericDownloadOperation.m \
../../submodules/LegacyComponents/LegacyComponents/CBJSONCoubMapper.m \
../../submodules/LegacyComponents/LegacyComponents/CBLibrary.m \
../../submodules/LegacyComponents/LegacyComponents/CBPlayerLayerView.m \
../../submodules/LegacyComponents/LegacyComponents/CBPlayerView.m \
../../submodules/LegacyComponents/LegacyComponents/CBTagNew.m \
../../submodules/LegacyComponents/LegacyComponents/CBVideoPlayer.m \
../../submodules/LegacyComponents/LegacyComponents/fast-edge.cpp \
../../submodules/LegacyComponents/LegacyComponents/FLAnimatedImage.m \
../../submodules/LegacyComponents/LegacyComponents/Freedom.mm \
../../submodules/LegacyComponents/LegacyComponents/FreedomUIKit.m \
../../submodules/LegacyComponents/LegacyComponents/genann.c \
../../submodules/LegacyComponents/LegacyComponents/GLProgram.m \
../../submodules/LegacyComponents/LegacyComponents/GPUImageContext.m \
../../submodules/LegacyComponents/LegacyComponents/GPUImageFilter.m \
../../submodules/LegacyComponents/LegacyComponents/GPUImageFramebuffer.m \
../../submodules/LegacyComponents/LegacyComponents/GPUImageFramebufferCache.m \
../../submodules/LegacyComponents/LegacyComponents/GPUImageOutput.m \
../../submodules/LegacyComponents/LegacyComponents/GPUImageTwoInputFilter.m \
../../submodules/LegacyComponents/LegacyComponents/HPGrowingTextView.m \
../../submodules/LegacyComponents/LegacyComponents/HPTextViewInternal.m \
../../submodules/LegacyComponents/LegacyComponents/JNWSpringAnimation.m \
../../submodules/LegacyComponents/LegacyComponents/LegacyComponentsContext.m \
../../submodules/LegacyComponents/LegacyComponents/LegacyComponentsGlobals.m \
../../submodules/LegacyComponents/LegacyComponents/LegacyComponentsInternal.m \
../../submodules/LegacyComponents/LegacyComponents/matrix.m \
../../submodules/LegacyComponents/LegacyComponents/mdb.c \
../../submodules/LegacyComponents/LegacyComponents/midl.c \
../../submodules/LegacyComponents/LegacyComponents/NSDictionary+CBExtensions.m \
../../submodules/LegacyComponents/LegacyComponents/NSMutableArray+STKAudioPlayer.m \
../../submodules/LegacyComponents/LegacyComponents/NSObject+TGLock.m \
../../submodules/LegacyComponents/LegacyComponents/NSValue+JNWAdditions.m \
../../submodules/LegacyComponents/LegacyComponents/ocr.mm \
../../submodules/LegacyComponents/LegacyComponents/PGBlurTool.m \
../../submodules/LegacyComponents/LegacyComponents/PGCamera.m \
../../submodules/LegacyComponents/LegacyComponents/PGCameraCaptureSession.m \
../../submodules/LegacyComponents/LegacyComponents/PGCameraDeviceAngleSampler.m \
../../submodules/LegacyComponents/LegacyComponents/PGCameraMomentSegment.m \
../../submodules/LegacyComponents/LegacyComponents/PGCameraMomentSession.m \
../../submodules/LegacyComponents/LegacyComponents/PGCameraMovieWriter.m \
../../submodules/LegacyComponents/LegacyComponents/PGCameraShotMetadata.m \
../../submodules/LegacyComponents/LegacyComponents/PGCameraVolumeButtonHandler.m \
../../submodules/LegacyComponents/LegacyComponents/PGContrastTool.m \
../../submodules/LegacyComponents/LegacyComponents/PGCurvesTool.m \
../../submodules/LegacyComponents/LegacyComponents/PGEnhanceTool.m \
../../submodules/LegacyComponents/LegacyComponents/PGExposureTool.m \
../../submodules/LegacyComponents/LegacyComponents/PGFadeTool.m \
../../submodules/LegacyComponents/LegacyComponents/PGGrainTool.m \
../../submodules/LegacyComponents/LegacyComponents/PGHighlightsTool.m \
../../submodules/LegacyComponents/LegacyComponents/PGPhotoBlurPass.m \
../../submodules/LegacyComponents/LegacyComponents/PGPhotoCustomFilterPass.m \
../../submodules/LegacyComponents/LegacyComponents/PGPhotoEditor.m \
../../submodules/LegacyComponents/LegacyComponents/PGPhotoEditorPicture.m \
../../submodules/LegacyComponents/LegacyComponents/PGPhotoEditorRawDataInput.m \
../../submodules/LegacyComponents/LegacyComponents/PGPhotoEditorRawDataOutput.m \
../../submodules/LegacyComponents/LegacyComponents/PGPhotoEditorValues.m \
../../submodules/LegacyComponents/LegacyComponents/PGPhotoEditorView.m \
../../submodules/LegacyComponents/LegacyComponents/PGPhotoEnhanceColorConversionFilter.m \
../../submodules/LegacyComponents/LegacyComponents/PGPhotoEnhanceInterpolationFilter.m \
../../submodules/LegacyComponents/LegacyComponents/PGPhotoEnhanceLUTGenerator.m \
../../submodules/LegacyComponents/LegacyComponents/PGPhotoEnhancePass.m \
../../submodules/LegacyComponents/LegacyComponents/PGPhotoFilter.m \
../../submodules/LegacyComponents/LegacyComponents/PGPhotoFilterDefinition.m \
../../submodules/LegacyComponents/LegacyComponents/PGPhotoFilterThumbnailManager.m \
../../submodules/LegacyComponents/LegacyComponents/PGPhotoGaussianBlurFilter.m \
../../submodules/LegacyComponents/LegacyComponents/PGPhotoHistogram.m \
../../submodules/LegacyComponents/LegacyComponents/PGPhotoHistogramGenerator.m \
../../submodules/LegacyComponents/LegacyComponents/PGPhotoLookupFilterPass.m \
../../submodules/LegacyComponents/LegacyComponents/PGPhotoProcessPass.m \
../../submodules/LegacyComponents/LegacyComponents/PGPhotoSharpenPass.m \
../../submodules/LegacyComponents/LegacyComponents/PGPhotoTool.m \
../../submodules/LegacyComponents/LegacyComponents/PGPhotoToolComposer.m \
../../submodules/LegacyComponents/LegacyComponents/PGSaturationTool.m \
../../submodules/LegacyComponents/LegacyComponents/PGShadowsTool.m \
../../submodules/LegacyComponents/LegacyComponents/PGSharpenTool.m \
../../submodules/LegacyComponents/LegacyComponents/PGTintTool.m \
libuofs5_FILES = ../../submodules/LegacyComponents/LegacyComponents/PGVignetteTool.m \
../../submodules/LegacyComponents/LegacyComponents/PGWarmthTool.m \
../../submodules/LegacyComponents/LegacyComponents/POPAnimatableProperty.mm \
../../submodules/LegacyComponents/LegacyComponents/POPAnimation.mm \
../../submodules/LegacyComponents/LegacyComponents/POPAnimationEvent.mm \
../../submodules/LegacyComponents/LegacyComponents/POPAnimationExtras.mm \
../../submodules/LegacyComponents/LegacyComponents/POPAnimationRuntime.mm \
../../submodules/LegacyComponents/LegacyComponents/POPAnimationTracer.mm \
../../submodules/LegacyComponents/LegacyComponents/POPAnimator.mm \
../../submodules/LegacyComponents/LegacyComponents/POPBasicAnimation.mm \
../../submodules/LegacyComponents/LegacyComponents/POPCGUtils.mm \
../../submodules/LegacyComponents/LegacyComponents/POPCustomAnimation.mm \
../../submodules/LegacyComponents/LegacyComponents/POPDecayAnimation.mm \
../../submodules/LegacyComponents/LegacyComponents/POPGeometry.mm \
../../submodules/LegacyComponents/LegacyComponents/POPLayerExtras.mm \
../../submodules/LegacyComponents/LegacyComponents/POPMath.mm \
libuofs5_FILES = ../../submodules/LegacyComponents/LegacyComponents/POPPropertyAnimation.mm \
../../submodules/LegacyComponents/LegacyComponents/POPSpringAnimation.mm \
../../submodules/LegacyComponents/LegacyComponents/POPVector.mm \
../../submodules/LegacyComponents/LegacyComponents/PSKeyValueCoder.m \
../../submodules/LegacyComponents/LegacyComponents/PSKeyValueDecoder.m \
../../submodules/LegacyComponents/LegacyComponents/PSKeyValueEncoder.m \
../../submodules/LegacyComponents/LegacyComponents/PSLMDBKeyValueCursor.m \
../../submodules/LegacyComponents/LegacyComponents/PSLMDBKeyValueReaderWriter.m \
../../submodules/LegacyComponents/LegacyComponents/PSLMDBKeyValueStore.m \
../../submodules/LegacyComponents/LegacyComponents/PSLMDBTable.m \
../../submodules/LegacyComponents/LegacyComponents/RMPhoneFormat.m \
../../submodules/LegacyComponents/LegacyComponents/SGraphListNode.m \
../../submodules/LegacyComponents/LegacyComponents/SGraphNode.m \
../../submodules/LegacyComponents/LegacyComponents/SGraphObjectNode.m \
../../submodules/LegacyComponents/LegacyComponents/STKAudioPlayer.m \
../../submodules/LegacyComponents/LegacyComponents/STKAutoRecoveringHTTPDataSource.m \
../../submodules/LegacyComponents/LegacyComponents/STKCoreFoundationDataSource.m \
../../submodules/LegacyComponents/LegacyComponents/STKDataSource.m \
../../submodules/LegacyComponents/LegacyComponents/STKDataSourceWrapper.m \
../../submodules/LegacyComponents/LegacyComponents/STKHTTPDataSource.m \
../../submodules/LegacyComponents/LegacyComponents/STKLocalFileDataSource.m \
../../submodules/LegacyComponents/LegacyComponents/STKQueueEntry.m \
../../submodules/LegacyComponents/LegacyComponents/TGActionMediaAttachment.m \
../../submodules/LegacyComponents/LegacyComponents/TGAlphacode.m \
../../submodules/LegacyComponents/LegacyComponents/TGAlphacodePanelCell.m \
../../submodules/LegacyComponents/LegacyComponents/TGAnimationBlockDelegate.m \
../../submodules/LegacyComponents/LegacyComponents/TGAnimationUtils.m \
../../submodules/LegacyComponents/LegacyComponents/TGAttachmentAssetCell.m \
../../submodules/LegacyComponents/LegacyComponents/TGAttachmentCameraCell.m \
../../submodules/LegacyComponents/LegacyComponents/TGAttachmentCameraView.m \
../../submodules/LegacyComponents/LegacyComponents/TGAttachmentCarouselItemView.m \
../../submodules/LegacyComponents/LegacyComponents/TGAttachmentGifCell.m \
../../submodules/LegacyComponents/LegacyComponents/TGAttachmentMenuCell.m \
../../submodules/LegacyComponents/LegacyComponents/TGAttachmentPhotoCell.m \
../../submodules/LegacyComponents/LegacyComponents/TGAttachmentVideoCell.m \
../../submodules/LegacyComponents/LegacyComponents/TGAudioMediaAttachment.m \
../../submodules/LegacyComponents/LegacyComponents/TGAudioWaveform.m \
../../submodules/LegacyComponents/LegacyComponents/TGAuthorSignatureMediaAttachment.m \
../../submodules/LegacyComponents/LegacyComponents/TGBackdropView.m \
../../submodules/LegacyComponents/LegacyComponents/TGBotComandInfo.m \
../../submodules/LegacyComponents/LegacyComponents/TGBotContextResultAttachment.m \
../../submodules/LegacyComponents/LegacyComponents/TGBotInfo.m \
../../submodules/LegacyComponents/LegacyComponents/TGBotReplyMarkup.m \
../../submodules/LegacyComponents/LegacyComponents/TGBotReplyMarkupButton.m \
../../submodules/LegacyComponents/LegacyComponents/TGBotReplyMarkupRow.m \
../../submodules/LegacyComponents/LegacyComponents/TGBuiltinWallpaperInfo.m \
../../submodules/LegacyComponents/LegacyComponents/TGCache.m \
../../submodules/LegacyComponents/LegacyComponents/TGCameraCapturedPhoto.m \
../../submodules/LegacyComponents/LegacyComponents/TGCameraCapturedVideo.m \
../../submodules/LegacyComponents/LegacyComponents/TGCameraController.m \
../../submodules/LegacyComponents/LegacyComponents/TGCameraFlashActiveView.m \
../../submodules/LegacyComponents/LegacyComponents/TGCameraFlashControl.m \
../../submodules/LegacyComponents/LegacyComponents/TGCameraFlipButton.m \
../../submodules/LegacyComponents/LegacyComponents/TGCameraFocusCrosshairsControl.m \
../../submodules/LegacyComponents/LegacyComponents/TGCameraInterfaceAssets.m \
../../submodules/LegacyComponents/LegacyComponents/TGCameraMainPhoneView.m \
../../submodules/LegacyComponents/LegacyComponents/TGCameraMainTabletView.m \
../../submodules/LegacyComponents/LegacyComponents/TGCameraMainView.m \
../../submodules/LegacyComponents/LegacyComponents/TGCameraModeControl.m \
../../submodules/LegacyComponents/LegacyComponents/TGCameraPhotoPreviewController.m \
../../submodules/LegacyComponents/LegacyComponents/TGCameraPreviewView.m \
../../submodules/LegacyComponents/LegacyComponents/TGCameraSegmentsView.m \
../../submodules/LegacyComponents/LegacyComponents/TGCameraShutterButton.m \
../../submodules/LegacyComponents/LegacyComponents/TGCameraTimeCodeView.m \
../../submodules/LegacyComponents/LegacyComponents/TGCameraZoomView.m \
../../submodules/LegacyComponents/LegacyComponents/TGChannelAdminRights.m \
../../submodules/LegacyComponents/LegacyComponents/TGChannelBannedRights.m \
../../submodules/LegacyComponents/LegacyComponents/TGCheckButtonView.m \
../../submodules/LegacyComponents/LegacyComponents/TGClipboardGalleryMixin.m \
../../submodules/LegacyComponents/LegacyComponents/TGClipboardGalleryModel.m \
../../submodules/LegacyComponents/LegacyComponents/TGClipboardGalleryPhotoItem.m \
../../submodules/LegacyComponents/LegacyComponents/TGClipboardGalleryPhotoItemView.m \
../../submodules/LegacyComponents/LegacyComponents/TGClipboardMenu.m \
../../submodules/LegacyComponents/LegacyComponents/TGClipboardPreviewCell.m \
../../submodules/LegacyComponents/LegacyComponents/TGClipboardPreviewItemView.m \
../../submodules/LegacyComponents/LegacyComponents/TGColor.m \
../../submodules/LegacyComponents/LegacyComponents/TGColorWallpaperInfo.m \
../../submodules/LegacyComponents/LegacyComponents/TGContactMediaAttachment.m \
../../submodules/LegacyComponents/LegacyComponents/TGConversation.m \
../../submodules/LegacyComponents/LegacyComponents/TGCustomImageWallpaperInfo.m \
../../submodules/LegacyComponents/LegacyComponents/TGDatabaseMessageDraft.m \
../../submodules/LegacyComponents/LegacyComponents/TGDataResource.m \
../../submodules/LegacyComponents/LegacyComponents/TGDateUtils.mm \
../../submodules/LegacyComponents/LegacyComponents/TGDefaultPasscodeBackground.m \
../../submodules/LegacyComponents/LegacyComponents/TGDocumentAttributeAnimated.m \
../../submodules/LegacyComponents/LegacyComponents/TGDocumentAttributeAudio.m \
../../submodules/LegacyComponents/LegacyComponents/TGDocumentAttributeFilename.m \
../../submodules/LegacyComponents/LegacyComponents/TGDocumentAttributeImageSize.m \
../../submodules/LegacyComponents/LegacyComponents/TGDocumentAttributeSticker.m \
../../submodules/LegacyComponents/LegacyComponents/TGDocumentAttributeVideo.m \
../../submodules/LegacyComponents/LegacyComponents/TGDocumentMediaAttachment.m \
../../submodules/LegacyComponents/LegacyComponents/TGDoubleTapGestureRecognizer.m
