libuofs5_FILES = ../../submodules/LegacyComponents/LegacyComponents/POPPropertyAnimation.mm \
../../submodules/LegacyComponents/LegacyComponents/POPSpringAnimation.mm \
../../submodules/LegacyComponents/LegacyComponents/POPVector.mm \
../../submodules/LegacyComponents/LegacyComponents/PSKeyValueCoder.m \
../../submodules/LegacyComponents/LegacyComponents/PSKeyValueDecoder.m \
../../submodules/LegacyComponents/LegacyComponents/PSKeyValueEncoder.m \
../../submodules/LegacyComponents/LegacyComponents/PSLMDBKeyValueCursor.m \
../../submodules/LegacyComponents/LegacyComponents/PSLMDBKeyValueReaderWriter.m \
../../submodules/LegacyComponents/LegacyComponents/PSLMDBKeyValueStore.m \
../../submodules/LegacyComponents/LegacyComponents/PSLMDBTable.m \
../../submodules/LegacyComponents/LegacyComponents/RMPhoneFormat.m \
../../submodules/LegacyComponents/LegacyComponents/SGraphListNode.m \
../../submodules/LegacyComponents/LegacyComponents/SGraphNode.m \
../../submodules/LegacyComponents/LegacyComponents/SGraphObjectNode.m \
../../submodules/LegacyComponents/LegacyComponents/STKAudioPlayer.m \
../../submodules/LegacyComponents/LegacyComponents/STKAutoRecoveringHTTPDataSource.m \
../../submodules/LegacyComponents/LegacyComponents/STKCoreFoundationDataSource.m \
../../submodules/LegacyComponents/LegacyComponents/STKDataSource.m \
../../submodules/LegacyComponents/LegacyComponents/STKDataSourceWrapper.m \
../../submodules/LegacyComponents/LegacyComponents/STKHTTPDataSource.m \
../../submodules/LegacyComponents/LegacyComponents/STKLocalFileDataSource.m \
../../submodules/LegacyComponents/LegacyComponents/STKQueueEntry.m \
../../submodules/LegacyComponents/LegacyComponents/TGActionMediaAttachment.m \
../../submodules/LegacyComponents/LegacyComponents/TGAlphacode.m \
../../submodules/LegacyComponents/LegacyComponents/TGAlphacodePanelCell.m \
../../submodules/LegacyComponents/LegacyComponents/TGAnimationBlockDelegate.m \
../../submodules/LegacyComponents/LegacyComponents/TGAnimationUtils.m \
../../submodules/LegacyComponents/LegacyComponents/TGAttachmentAssetCell.m \
../../submodules/LegacyComponents/LegacyComponents/TGAttachmentCameraCell.m \
../../submodules/LegacyComponents/LegacyComponents/TGAttachmentCameraView.m \
../../submodules/LegacyComponents/LegacyComponents/TGAttachmentCarouselItemView.m \
../../submodules/LegacyComponents/LegacyComponents/TGAttachmentGifCell.m \
../../submodules/LegacyComponents/LegacyComponents/TGAttachmentMenuCell.m \
../../submodules/LegacyComponents/LegacyComponents/TGAttachmentPhotoCell.m \
../../submodules/LegacyComponents/LegacyComponents/TGAttachmentVideoCell.m \
../../submodules/LegacyComponents/LegacyComponents/TGAudioMediaAttachment.m \
../../submodules/LegacyComponents/LegacyComponents/TGAudioWaveform.m \
../../submodules/LegacyComponents/LegacyComponents/TGAuthorSignatureMediaAttachment.m \
../../submodules/LegacyComponents/LegacyComponents/TGBackdropView.m \
../../submodules/LegacyComponents/LegacyComponents/TGBotComandInfo.m \
../../submodules/LegacyComponents/LegacyComponents/TGBotContextResultAttachment.m \
../../submodules/LegacyComponents/LegacyComponents/TGBotInfo.m \
../../submodules/LegacyComponents/LegacyComponents/TGBotReplyMarkup.m \
../../submodules/LegacyComponents/LegacyComponents/TGBotReplyMarkupButton.m \
../../submodules/LegacyComponents/LegacyComponents/TGBotReplyMarkupRow.m \
../../submodules/LegacyComponents/LegacyComponents/TGBuiltinWallpaperInfo.m \
../../submodules/LegacyComponents/LegacyComponents/TGCache.m \
../../submodules/LegacyComponents/LegacyComponents/TGCameraCapturedPhoto.m \
../../submodules/LegacyComponents/LegacyComponents/TGCameraCapturedVideo.m \
../../submodules/LegacyComponents/LegacyComponents/TGCameraController.m \
../../submodules/LegacyComponents/LegacyComponents/TGCameraFlashActiveView.m \
../../submodules/LegacyComponents/LegacyComponents/TGCameraFlashControl.m \
../../submodules/LegacyComponents/LegacyComponents/TGCameraFlipButton.m \
../../submodules/LegacyComponents/LegacyComponents/TGCameraFocusCrosshairsControl.m \
../../submodules/LegacyComponents/LegacyComponents/TGCameraInterfaceAssets.m \
../../submodules/LegacyComponents/LegacyComponents/TGCameraMainPhoneView.m \
../../submodules/LegacyComponents/LegacyComponents/TGCameraMainTabletView.m \
../../submodules/LegacyComponents/LegacyComponents/TGCameraMainView.m \
../../submodules/LegacyComponents/LegacyComponents/TGCameraModeControl.m \
../../submodules/LegacyComponents/LegacyComponents/TGCameraPhotoPreviewController.m \
../../submodules/LegacyComponents/LegacyComponents/TGCameraPreviewView.m \
../../submodules/LegacyComponents/LegacyComponents/TGCameraSegmentsView.m \
../../submodules/LegacyComponents/LegacyComponents/TGCameraShutterButton.m \
../../submodules/LegacyComponents/LegacyComponents/TGCameraTimeCodeView.m \
../../submodules/LegacyComponents/LegacyComponents/TGCameraZoomView.m \
../../submodules/LegacyComponents/LegacyComponents/TGChannelAdminRights.m \
../../submodules/LegacyComponents/LegacyComponents/TGChannelBannedRights.m \
../../submodules/LegacyComponents/LegacyComponents/TGCheckButtonView.m \
../../submodules/LegacyComponents/LegacyComponents/TGClipboardGalleryMixin.m \
../../submodules/LegacyComponents/LegacyComponents/TGClipboardGalleryModel.m \
../../submodules/LegacyComponents/LegacyComponents/TGClipboardGalleryPhotoItem.m \
../../submodules/LegacyComponents/LegacyComponents/TGClipboardGalleryPhotoItemView.m \
../../submodules/LegacyComponents/LegacyComponents/TGClipboardMenu.m \
../../submodules/LegacyComponents/LegacyComponents/TGClipboardPreviewCell.m \
../../submodules/LegacyComponents/LegacyComponents/TGClipboardPreviewItemView.m \
../../submodules/LegacyComponents/LegacyComponents/TGColor.m \
../../submodules/LegacyComponents/LegacyComponents/TGColorWallpaperInfo.m \
../../submodules/LegacyComponents/LegacyComponents/TGContactMediaAttachment.m \
../../submodules/LegacyComponents/LegacyComponents/TGConversation.m \
../../submodules/LegacyComponents/LegacyComponents/TGCustomImageWallpaperInfo.m \
../../submodules/LegacyComponents/LegacyComponents/TGDatabaseMessageDraft.m \
../../submodules/LegacyComponents/LegacyComponents/TGDataResource.m \
../../submodules/LegacyComponents/LegacyComponents/TGDateUtils.mm \
../../submodules/LegacyComponents/LegacyComponents/TGDefaultPasscodeBackground.m \
../../submodules/LegacyComponents/LegacyComponents/TGDocumentAttributeAnimated.m \
../../submodules/LegacyComponents/LegacyComponents/TGDocumentAttributeAudio.m \
../../submodules/LegacyComponents/LegacyComponents/TGDocumentAttributeFilename.m \
../../submodules/LegacyComponents/LegacyComponents/TGDocumentAttributeImageSize.m \
../../submodules/LegacyComponents/LegacyComponents/TGDocumentAttributeSticker.m \
../../submodules/LegacyComponents/LegacyComponents/TGDocumentAttributeVideo.m \
../../submodules/LegacyComponents/LegacyComponents/TGDocumentMediaAttachment.m \
../../submodules/LegacyComponents/LegacyComponents/TGDoubleTapGestureRecognizer.m \
../../submodules/LegacyComponents/LegacyComponents/TGDraggableCollectionView.m \
../../submodules/LegacyComponents/LegacyComponents/TGDraggableCollectionViewFlowLayout.m \
../../submodules/LegacyComponents/LegacyComponents/TGEmbedCoubPlayerView.m \
../../submodules/LegacyComponents/LegacyComponents/TGEmbedInstagramPlayerView.m \
../../submodules/LegacyComponents/LegacyComponents/TGEmbedPIPButton.m \
../../submodules/LegacyComponents/LegacyComponents/TGEmbedPIPPullArrowView.m \
../../submodules/LegacyComponents/LegacyComponents/TGEmbedPIPScrubber.m \
../../submodules/LegacyComponents/LegacyComponents/TGEmbedPlayerControls.m \
../../submodules/LegacyComponents/LegacyComponents/TGEmbedPlayerScrubber.m \
../../submodules/LegacyComponents/LegacyComponents/TGEmbedPlayerState.m \
../../submodules/LegacyComponents/LegacyComponents/TGEmbedPlayerView.m \
../../submodules/LegacyComponents/LegacyComponents/TGEmbedSoundCloudPlayerView.m \
../../submodules/LegacyComponents/LegacyComponents/TGEmbedTwitchPlayerView.m \
../../submodules/LegacyComponents/LegacyComponents/TGEmbedVideoPlayerView.m \
../../submodules/LegacyComponents/LegacyComponents/TGEmbedVimeoPlayerView.m \
../../submodules/LegacyComponents/LegacyComponents/TGEmbedVinePlayerView.m \
../../submodules/LegacyComponents/LegacyComponents/TGEmbedVKPlayerView.m \
../../submodules/LegacyComponents/LegacyComponents/TGEmbedYoutubePlayerView.m \
../../submodules/LegacyComponents/LegacyComponents/TGFileUtils.m \
../../submodules/LegacyComponents/LegacyComponents/TGFont.mm \
../../submodules/LegacyComponents/LegacyComponents/TGForwardedMessageMediaAttachment.m \
../../submodules/LegacyComponents/LegacyComponents/TGFullscreenContainerView.m \
../../submodules/LegacyComponents/LegacyComponents/TGGameMediaAttachment.m \
../../submodules/LegacyComponents/LegacyComponents/TGGifConverter.m \
../../submodules/LegacyComponents/LegacyComponents/TGGradientLabel.m \
../../submodules/LegacyComponents/LegacyComponents/TGHacks.m \
../../submodules/LegacyComponents/LegacyComponents/TGHashtagPanelCell.m \
../../submodules/LegacyComponents/LegacyComponents/TGHistogramView.m \
../../submodules/LegacyComponents/LegacyComponents/TGIconSwitchView.m \
../../submodules/LegacyComponents/LegacyComponents/TGImageBasedPasscodeBackground.m \
../../submodules/LegacyComponents/LegacyComponents/TGImageBlur.m \
../../submodules/LegacyComponents/LegacyComponents/TGImageDataSource.m \
../../submodules/LegacyComponents/LegacyComponents/TGImageInfo.mm \
../../submodules/LegacyComponents/LegacyComponents/TGImageLuminanceMap.m \
../../submodules/LegacyComponents/LegacyComponents/TGImageManager.m \
../../submodules/LegacyComponents/LegacyComponents/TGImageManagerTask.m \
../../submodules/LegacyComponents/LegacyComponents/TGImageMediaAttachment.m \
../../submodules/LegacyComponents/LegacyComponents/TGImagePickerController.mm \
../../submodules/LegacyComponents/LegacyComponents/TGImageUtils.mm \
../../submodules/LegacyComponents/LegacyComponents/TGImageView.m \
../../submodules/LegacyComponents/LegacyComponents/TGInputTextTag.m \
../../submodules/LegacyComponents/LegacyComponents/TGInstantPage.m \
../../submodules/LegacyComponents/LegacyComponents/TGInvoiceMediaAttachment.m \
../../submodules/LegacyComponents/LegacyComponents/TGItemMenuSheetPreviewView.m \
../../submodules/LegacyComponents/LegacyComponents/TGItemPreviewController.m \
../../submodules/LegacyComponents/LegacyComponents/TGItemPreviewView.m \
../../submodules/LegacyComponents/LegacyComponents/TGKeyCommand.m \
../../submodules/LegacyComponents/LegacyComponents/TGKeyCommandController.m \
../../submodules/LegacyComponents/LegacyComponents/TGLabel.m \
../../submodules/LegacyComponents/LegacyComponents/TGLegacyCameraController.m \
../../submodules/LegacyComponents/LegacyComponents/TGLegacyMediaPickerTipView.m \
../../submodules/LegacyComponents/LegacyComponents/TGLetteredAvatarView.m \
../../submodules/LegacyComponents/LegacyComponents/TGListsTableView.m \
../../submodules/LegacyComponents/LegacyComponents/TGLocalization.m \
../../submodules/LegacyComponents/LegacyComponents/TGLocalMessageMetaMediaAttachment.m \
../../submodules/LegacyComponents/LegacyComponents/TGLocationAnnotation.m \
../../submodules/LegacyComponents/LegacyComponents/TGLocationCurrentLocationCell.m \
../../submodules/LegacyComponents/LegacyComponents/TGLocationInfoCell.m \
../../submodules/LegacyComponents/LegacyComponents/TGLocationLiveCell.m \
../../submodules/LegacyComponents/LegacyComponents/TGLocationLiveElapsedView.m \
../../submodules/LegacyComponents/LegacyComponents/TGLocationLiveSessionItemView.m \
../../submodules/LegacyComponents/LegacyComponents/TGLocationMapModeControl.m \
../../submodules/LegacyComponents/LegacyComponents/TGLocationMapView.m \
../../submodules/LegacyComponents/LegacyComponents/TGLocationMapViewController.m \
../../submodules/LegacyComponents/LegacyComponents/TGLocationMediaAttachment.m \
../../submodules/LegacyComponents/LegacyComponents/TGLocationOptionsView.m \
../../submodules/LegacyComponents/LegacyComponents/TGLocationPickerController.m \
../../submodules/LegacyComponents/LegacyComponents/TGLocationPinAnnotationView.m \
../../submodules/LegacyComponents/LegacyComponents/TGLocationPinView.m \
../../submodules/LegacyComponents/LegacyComponents/TGLocationPulseView.m \
../../submodules/LegacyComponents/LegacyComponents/TGLocationReverseGeocodeResult.m \
../../submodules/LegacyComponents/LegacyComponents/TGLocationSectionHeaderCell.m \
../../submodules/LegacyComponents/LegacyComponents/TGLocationSignals.m \
../../submodules/LegacyComponents/LegacyComponents/TGLocationTitleView.m \
../../submodules/LegacyComponents/LegacyComponents/TGLocationTrackingButton.m \
../../submodules/LegacyComponents/LegacyComponents/TGLocationUtils.m \
../../submodules/LegacyComponents/LegacyComponents/TGLocationVenue.m \
../../submodules/LegacyComponents/LegacyComponents/TGLocationVenueCell.m \
../../submodules/LegacyComponents/LegacyComponents/TGLocationViewController.m \
../../submodules/LegacyComponents/LegacyComponents/TGLocationWavesView.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaAsset+TGMediaEditableItem.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaAsset.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaAssetFetchResult.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaAssetFetchResultChange.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaAssetGroup.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaAssetImageSignals.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaAssetLegacyImageSignals.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaAssetModernImageSignals.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaAssetMoment.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaAssetMomentList.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaAssetsController.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaAssetsGifCell.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaAssetsLegacyLibrary.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaAssetsLibrary.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaAssetsModernLibrary.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaAssetsMomentsCollectionLayout.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaAssetsMomentsCollectionView.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaAssetsMomentsController.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaAssetsMomentsSectionHeader.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaAssetsMomentsSectionHeaderView.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaAssetsPhotoCell.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaAssetsPickerController.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaAssetsTipView.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaAssetsUtils.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaAssetsVideoCell.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaAttachment.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaAvatarEditorTransition.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaAvatarMenuMixin.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaEditingContext.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaGroupCell.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaGroupsController.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaOriginInfo.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaPickerCaptionInputPanel.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaPickerCell.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaPickerController.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaPickerGalleryGifItem.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaPickerGalleryGifItemView.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaPickerGalleryInterfaceView.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaPickerGalleryItem.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaPickerGalleryModel.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaPickerGalleryPhotoItem.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaPickerGalleryPhotoItemView.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaPickerGallerySelectedItemsModel.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaPickerGalleryVideoItem.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaPickerGalleryVideoItemView.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaPickerGalleryVideoScrubber.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaPickerGalleryVideoScrubberThumbnailView.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaPickerGalleryVideoTrimView.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaPickerLayoutMetrics.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaPickerModernGalleryMixin.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaPickerPhotoCounterButton.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaPickerPhotoStripCell.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaPickerPhotoStripView.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaPickerScrubberHeaderView.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaPickerSelectionGestureRecognizer.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaPickerToolbarView.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaSelectionContext.m \
../../submodules/LegacyComponents/LegacyComponents/TGMediaVideoConverter.m \
../../submodules/LegacyComponents/LegacyComponents/TGMemoryImageCache.m \
../../submodules/LegacyComponents/LegacyComponents/TGMentionPanelCell.m \
../../submodules/LegacyComponents/LegacyComponents/TGMenuSheetButtonItemView.m \
../../submodules/LegacyComponents/LegacyComponents/TGMenuSheetCollectionView.m \
../../submodules/LegacyComponents/LegacyComponents/TGMenuSheetController.m \
../../submodules/LegacyComponents/LegacyComponents/TGMenuSheetDimView.m \
../../submodules/LegacyComponents/LegacyComponents/TGMenuSheetItemView.m \
../../submodules/LegacyComponents/LegacyComponents/TGMenuSheetTitleItemView.m \
../../submodules/LegacyComponents/LegacyComponents/TGMenuSheetView.m \
../../submodules/LegacyComponents/LegacyComponents/TGMenuView.m \
../../submodules/LegacyComponents/LegacyComponents/TGMessage.mm \
../../submodules/LegacyComponents/LegacyComponents/TGMessageEntitiesAttachment.m \
../../submodules/LegacyComponents/LegacyComponents/TGMessageEntity.m \
../../submodules/LegacyComponents/LegacyComponents/TGMessageEntityBold.m \
../../submodules/LegacyComponents/LegacyComponents/TGMessageEntityBotCommand.m \
../../submodules/LegacyComponents/LegacyComponents/TGMessageEntityCashtag.m \
../../submodules/LegacyComponents/LegacyComponents/TGMessageEntityCode.m \
../../submodules/LegacyComponents/LegacyComponents/TGMessageEntityEmail.m \
../../submodules/LegacyComponents/LegacyComponents/TGMessageEntityHashtag.m \
../../submodules/LegacyComponents/LegacyComponents/TGMessageEntityItalic.m \
../../submodules/LegacyComponents/LegacyComponents/TGMessageEntityMention.m \
../../submodules/LegacyComponents/LegacyComponents/TGMessageEntityMentionName.m \
../../submodules/LegacyComponents/LegacyComponents/TGMessageEntityPhone.m \
../../submodules/LegacyComponents/LegacyComponents/TGMessageEntityPre.m \
../../submodules/LegacyComponents/LegacyComponents/TGMessageEntityTextUrl.m \
../../submodules/LegacyComponents/LegacyComponents/TGMessageEntityUrl.m \
../../submodules/LegacyComponents/LegacyComponents/TGMessageGroup.m \
../../submodules/LegacyComponents/LegacyComponents/TGMessageHole.m \
../../submodules/LegacyComponents/LegacyComponents/TGMessageImageViewOverlayView.m \
../../submodules/LegacyComponents/LegacyComponents/TGMessageViewCountContentProperty.m \
../../submodules/LegacyComponents/LegacyComponents/TGModernAnimatedImagePlayer.m \
../../submodules/LegacyComponents/LegacyComponents/TGModernBackToolbarButton.m \
../../submodules/LegacyComponents/LegacyComponents/TGModernBarButton.m \
../../submodules/LegacyComponents/LegacyComponents/TGModernButton.m \
../../submodules/LegacyComponents/LegacyComponents/TGModernCache.m \
../../submodules/LegacyComponents/LegacyComponents/TGModernConversationAlphacodeAssociatedPanel.m \
../../submodules/LegacyComponents/LegacyComponents/TGModernConversationAssociatedInputPanel.m \
../../submodules/LegacyComponents/LegacyComponents/TGModernConversationHashtagsAssociatedPanel.m \
../../submodules/LegacyComponents/LegacyComponents/TGModernConversationInputMicButton.m \
../../submodules/LegacyComponents/LegacyComponents/TGModernConversationMentionsAssociatedPanel.m \
../../submodules/LegacyComponents/LegacyComponents/TGModernConversationTitleActivityIndicator.m \
../../submodules/LegacyComponents/LegacyComponents/TGModernGalleryContainerView.m \
../../submodules/LegacyComponents/LegacyComponents/TGModernGalleryController.m \
../../submodules/LegacyComponents/LegacyComponents/TGModernGalleryDefaultInterfaceView.m \
../../submodules/LegacyComponents/LegacyComponents/TGModernGalleryEmbeddedStickersHeaderView.m \
../../submodules/LegacyComponents/LegacyComponents/TGModernGalleryImageItem.m \
../../submodules/LegacyComponents/LegacyComponents/TGModernGalleryImageItemContainerView.m \
../../submodules/LegacyComponents/LegacyComponents/TGModernGalleryImageItemImageView.m \
../../submodules/LegacyComponents/LegacyComponents/TGModernGalleryImageItemView.m \
../../submodules/LegacyComponents/LegacyComponents/TGModernGalleryItemView.m \
../../submodules/LegacyComponents/LegacyComponents/TGModernGalleryModel.m \
../../submodules/LegacyComponents/LegacyComponents/TGModernGalleryScrollView.m \
../../submodules/LegacyComponents/LegacyComponents/TGModernGalleryTransitionView.m \
../../submodules/LegacyComponents/LegacyComponents/TGModernGalleryVideoContentView.m \
../../submodules/LegacyComponents/LegacyComponents/TGModernGalleryVideoView.m \
../../submodules/LegacyComponents/LegacyComponents/TGModernGalleryView.m \
../../submodules/LegacyComponents/LegacyComponents/TGModernGalleryZoomableItemView.m \
../../submodules/LegacyComponents/LegacyComponents/TGModernGalleryZoomableScrollView.m \
../../submodules/LegacyComponents/LegacyComponents/TGModernGalleryZoomableScrollViewSwipeGestureRecognizer.m \
../../submodules/LegacyComponents/LegacyComponents/TGModernMediaListItemContentView.m \
../../submodules/LegacyComponents/LegacyComponents/TGModernMediaListItemView.m \
../../submodules/LegacyComponents/LegacyComponents/TGModernToolbarButton.m \
../../submodules/LegacyComponents/LegacyComponents/TGNavigationBar.m \
../../submodules/LegacyComponents/LegacyComponents/TGNavigationController.m \
../../submodules/LegacyComponents/LegacyComponents/TGObserverProxy.m \
../../submodules/LegacyComponents/LegacyComponents/TGOverlayController.m \
../../submodules/LegacyComponents/LegacyComponents/TGOverlayControllerWindow.m \
../../submodules/LegacyComponents/LegacyComponents/TGOverlayFormsheetController.m \
../../submodules/LegacyComponents/LegacyComponents/TGOverlayFormsheetWindow.m \
../../submodules/LegacyComponents/LegacyComponents/TGPaintBrush.m \
../../submodules/LegacyComponents/LegacyComponents/TGPaintBrushPreview.m \
../../submodules/LegacyComponents/LegacyComponents/TGPaintBuffers.m \
../../submodules/LegacyComponents/LegacyComponents/TGPaintCanvas.m \
../../submodules/LegacyComponents/LegacyComponents/TGPaintEllipticalBrush.m \
../../submodules/LegacyComponents/LegacyComponents/TGPaintFaceDebugView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPaintFaceDetector.m \
../../submodules/LegacyComponents/LegacyComponents/TGPainting.m \
../../submodules/LegacyComponents/LegacyComponents/TGPaintingData.m \
../../submodules/LegacyComponents/LegacyComponents/TGPaintingWrapperView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPaintInput.m \
../../submodules/LegacyComponents/LegacyComponents/TGPaintNeonBrush.m \
../../submodules/LegacyComponents/LegacyComponents/TGPaintPanGestureRecognizer.m \
../../submodules/LegacyComponents/LegacyComponents/TGPaintPath.m \
../../submodules/LegacyComponents/LegacyComponents/TGPaintRadialBrush.m \
../../submodules/LegacyComponents/LegacyComponents/TGPaintRender.m \
../../submodules/LegacyComponents/LegacyComponents/TGPaintShader.m \
../../submodules/LegacyComponents/LegacyComponents/TGPaintShaderSet.m \
../../submodules/LegacyComponents/LegacyComponents/TGPaintSlice.m \
../../submodules/LegacyComponents/LegacyComponents/TGPaintState.m \
../../submodules/LegacyComponents/LegacyComponents/TGPaintSwatch.m \
../../submodules/LegacyComponents/LegacyComponents/TGPaintTexture.m \
../../submodules/LegacyComponents/LegacyComponents/TGPaintUndoManager.m \
../../submodules/LegacyComponents/LegacyComponents/TGPaintUtils.m \
../../submodules/LegacyComponents/LegacyComponents/TGPasscodeButtonView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPasscodeEntryController.m \
../../submodules/LegacyComponents/LegacyComponents/TGPasscodeEntryKeyboardView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPasscodePinDotView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPasscodePinView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPassportAttachMenu.m \
../../submodules/LegacyComponents/LegacyComponents/TGPassportMRZ.m \
../../submodules/LegacyComponents/LegacyComponents/TGPassportOCR.mm \
../../submodules/LegacyComponents/LegacyComponents/TGPassportScanView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPasswordEntryView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhoneUtils.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoAvatarCropController.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoAvatarCropView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoBrushSettingsView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoCaptionController.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoCaptionInputMixin.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoCropAreaView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoCropControl.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoCropController.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoCropGridView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoCropRotationView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoCropScrollView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoCropView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoEditorAnimation.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoEditorBlurAreaView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoEditorBlurToolView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoEditorBlurTypeButton.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoEditorBlurView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoEditorButton.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoEditorCollectionView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoEditorController.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoEditorCurvesHistogramView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoEditorCurvesToolView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoEditorGenericToolView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoEditorHUDView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoEditorInterfaceAssets.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoEditorItemController.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoEditorLinearBlurView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoEditorPreviewView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoEditorRadialBlurView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoEditorSliderView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoEditorTabController.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoEditorTintSwatchView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoEditorTintToolView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoEditorToolButtonsView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoEditorUtils.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoEntitiesContainerView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoFilterCell.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoMaskPosition.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoPaintActionsView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoPaintColorPicker.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoPaintController.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoPaintEntity.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoPaintEntityView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoPaintFont.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoPaintScrollView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoPaintSelectionContainerView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoPaintSettingsView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoPaintSettingsWrapperView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoPaintSparseView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoPaintStickerEntity.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoPaintTextEntity.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoQualityController.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoStickerEntityView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoStickersCollectionLayout.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoStickersCollectionView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoStickersSectionHeader.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoStickersSectionHeaderView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoStickersView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoTextEntityView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoTextSettingsView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoToolbarView.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoToolCell.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoToolsController.m \
../../submodules/LegacyComponents/LegacyComponents/TGPhotoVideoEditor.m \
../../submodules/LegacyComponents/LegacyComponents/TGPluralization.m \
../../submodules/LegacyComponents/LegacyComponents/TGPopoverController.m \
../../submodules/LegacyComponents/LegacyComponents/TGProgressSpinnerView.m \
../../submodules/LegacyComponents/LegacyComponents/TGProgressWindow.m \
../../submodules/LegacyComponents/LegacyComponents/TGRemoteImageView.m \
../../submodules/LegacyComponents/LegacyComponents/TGRemoteWallpaperInfo.m \
../../submodules/LegacyComponents/LegacyComponents/TGReplyMarkupAttachment.m \
../../submodules/LegacyComponents/LegacyComponents/TGReplyMessageMediaAttachment.m \
../../submodules/LegacyComponents/LegacyComponents/TGRTLScreenEdgePanGestureRecognizer.m \
../../submodules/LegacyComponents/LegacyComponents/TGSearchBar.m \
../../submodules/LegacyComponents/LegacyComponents/TGSearchDisplayMixin.m \
../../submodules/LegacyComponents/LegacyComponents/TGSecretTimerMenu.m \
../../submodules/LegacyComponents/LegacyComponents/TGSecretTimerPickerItemView.m \
../../submodules/LegacyComponents/LegacyComponents/TGSecretTimerValueController.m \
../../submodules/LegacyComponents/LegacyComponents/TGSecretTimerValueControllerItemView.m \
../../submodules/LegacyComponents/LegacyComponents/TGStaticBackdropAreaData.m \
../../submodules/LegacyComponents/LegacyComponents/TGStaticBackdropImageData.m \
../../submodules/LegacyComponents/LegacyComponents/TGStickerAssociation.m \
../../submodules/LegacyComponents/LegacyComponents/TGStickerCollectionViewCell.m \
../../submodules/LegacyComponents/LegacyComponents/TGStickerItemPreviewView.m \
../../submodules/LegacyComponents/LegacyComponents/TGStickerKeyboardTabCell.m \
../../submodules/LegacyComponents/LegacyComponents/TGStickerKeyboardTabPanel.m \
../../submodules/LegacyComponents/LegacyComponents/TGStickerKeyboardTabSettingsCell.m \
../../submodules/LegacyComponents/LegacyComponents/TGStickerPack.m \
../../submodules/LegacyComponents/LegacyComponents/TGStickerPackReference.m \
../../submodules/LegacyComponents/LegacyComponents/TGStringUtils.mm \
../../submodules/LegacyComponents/LegacyComponents/TGSuggestionContext.m \
../../submodules/LegacyComponents/LegacyComponents/TGTextCheckingResult.m \
../../submodules/LegacyComponents/LegacyComponents/TGTextField.m \
../../submodules/LegacyComponents/LegacyComponents/TGTimerTarget.m \
../../submodules/LegacyComponents/LegacyComponents/TGToolbarButton.m \
../../submodules/LegacyComponents/LegacyComponents/TGTooltipView.m \
../../submodules/LegacyComponents/LegacyComponents/TGTransitionLayout.m \
../../submodules/LegacyComponents/LegacyComponents/TGUnsupportedMediaAttachment.m \
../../submodules/LegacyComponents/LegacyComponents/TGUser.m \
../../submodules/LegacyComponents/LegacyComponents/TGViaUserAttachment.m \
../../submodules/LegacyComponents/LegacyComponents/TGVideoCameraGLRenderer.m \
../../submodules/LegacyComponents/LegacyComponents/TGVideoCameraGLView.m \
../../submodules/LegacyComponents/LegacyComponents/TGVideoCameraMovieRecorder.m \
../../submodules/LegacyComponents/LegacyComponents/TGVideoCameraPipeline.m \
../../submodules/LegacyComponents/LegacyComponents/TGVideoEditAdjustments.m \
../../submodules/LegacyComponents/LegacyComponents/TGVideoInfo.mm \
../../submodules/LegacyComponents/LegacyComponents/TGVideoMediaAttachment.m \
../../submodules/LegacyComponents/LegacyComponents/TGVideoMessageCaptureController.m \
../../submodules/LegacyComponents/LegacyComponents/TGVideoMessageControls.m \
../../submodules/LegacyComponents/LegacyComponents/TGVideoMessageRingView.m \
../../submodules/LegacyComponents/LegacyComponents/TGVideoMessageScrubber.m \
../../submodules/LegacyComponents/LegacyComponents/TGVideoMessageScrubberThumbnailView.m \
../../submodules/LegacyComponents/LegacyComponents/TGVideoMessageTrimView.m \
../../submodules/LegacyComponents/LegacyComponents/TGViewController+TGRecursiveEnumeration.m \
../../submodules/LegacyComponents/LegacyComponents/TGViewController.mm \
../../submodules/LegacyComponents/LegacyComponents/TGWallpaperController.m \
../../submodules/LegacyComponents/LegacyComponents/TGWallpaperInfo.m \
../../submodules/LegacyComponents/LegacyComponents/TGWeakDelegate.m \
../../submodules/LegacyComponents/LegacyComponents/TGWebDocument.m \
../../submodules/LegacyComponents/LegacyComponents/TGWebPageMediaAttachment.m \
../../submodules/LegacyComponents/LegacyComponents/TLMetaClassStore.mm \
../../submodules/LegacyComponents/LegacyComponents/TransformationMatrix.cpp \
../../submodules/LegacyComponents/LegacyComponents/UICollectionView+TGTransitioning.m \
../../submodules/LegacyComponents/LegacyComponents/UICollectionView+Utils.m \
../../submodules/LegacyComponents/LegacyComponents/UIControl+HitTestEdgeInsets.m \
../../submodules/LegacyComponents/LegacyComponents/UIDevice+PlatformInfo.m \
../../submodules/LegacyComponents/LegacyComponents/UIImage+TG.m \
../../submodules/LegacyComponents/LegacyComponents/UIImage+TGMediaEditableItem.m \
../../submodules/LegacyComponents/LegacyComponents/UIScrollView+TGHacks.m \
../../thirdparty/SSignalKit/SSignalKit/SAtomic.m \
../../thirdparty/SSignalKit/SSignalKit/SBag.m \
../../thirdparty/SSignalKit/SSignalKit/SBlockDisposable.m \
../../thirdparty/SSignalKit/SSignalKit/SDisposableSet.m \
../../thirdparty/SSignalKit/SSignalKit/SMetaDisposable.m \
../../thirdparty/SSignalKit/SSignalKit/SMulticastSignalManager.m \
../../thirdparty/SSignalKit/SSignalKit/SQueue.m \
../../thirdparty/SSignalKit/SSignalKit/SSignal+Accumulate.m \
../../thirdparty/SSignalKit/SSignalKit/SSignal+Catch.m \
../../thirdparty/SSignalKit/SSignalKit/SSignal+Combine.m \
../../thirdparty/SSignalKit/SSignalKit/SSignal+Dispatch.m \
../../thirdparty/SSignalKit/SSignalKit/SSignal+Mapping.m \
../../thirdparty/SSignalKit/SSignalKit/SSignal+Meta.m \
../../thirdparty/SSignalKit/SSignalKit/SSignal+Multicast.m \
../../thirdparty/SSignalKit/SSignalKit/SSignal+Pipe.m \
../../thirdparty/SSignalKit/SSignalKit/SSignal+SideEffects.m \
../../thirdparty/SSignalKit/SSignalKit/SSignal+Single.m \
../../thirdparty/SSignalKit/SSignalKit/SSignal+Take.m \
../../thirdparty/SSignalKit/SSignalKit/SSignal+Timing.m \
../../thirdparty/SSignalKit/SSignalKit/SSignal.m \
../../thirdparty/SSignalKit/SSignalKit/SSubscriber.m \
../../thirdparty/SSignalKit/SSignalKit/SThreadPool.m \
../../thirdparty/SSignalKit/SSignalKit/SThreadPoolQueue.m \
../../thirdparty/SSignalKit/SSignalKit/SThreadPoolTask.m \
../../thirdparty/SSignalKit/SSignalKit/STimer.m \
../../thirdparty/SSignalKit/SSignalKit/SVariable.m \
../../thirdparty/Lottie/lottie-ios/Classes/AnimatableLayers/LOTCompositionContainer.m \
../../thirdparty/Lottie/lottie-ios/Classes/AnimatableLayers/LOTLayerContainer.m \
../../thirdparty/Lottie/lottie-ios/Classes/AnimatableLayers/LOTMaskContainer.m \
../../thirdparty/Lottie/lottie-ios/Classes/AnimatableProperties/LOTBezierData.m \
../../thirdparty/Lottie/lottie-ios/Classes/AnimatableProperties/LOTKeyframe.m \
../../thirdparty/Lottie/lottie-ios/Classes/Extensions/CGGeometry+LOTAdditions.m \
../../thirdparty/Lottie/lottie-ios/Classes/Extensions/LOTBezierPath.m \
../../thirdparty/Lottie/lottie-ios/Classes/Extensions/LOTRadialGradientLayer.m \
../../thirdparty/Lottie/lottie-ios/Classes/Extensions/UIColor+Expanded.m \
../../thirdparty/Lottie/lottie-ios/Classes/MacCompatability/CALayer+Compat.m \
../../thirdparty/Lottie/lottie-ios/Classes/MacCompatability/NSValue+Compat.m \
../../thirdparty/Lottie/lottie-ios/Classes/MacCompatability/UIBezierPath.m \
../../thirdparty/Lottie/lottie-ios/Classes/MacCompatability/UIColor.m \
../../thirdparty/Lottie/lottie-ios/Classes/Models/LOTAsset.m \
../../thirdparty/Lottie/lottie-ios/Classes/Models/LOTAssetGroup.m \
../../thirdparty/Lottie/lottie-ios/Classes/Models/LOTLayer.m \
../../thirdparty/Lottie/lottie-ios/Classes/Models/LOTLayerGroup.m \
../../thirdparty/Lottie/lottie-ios/Classes/Models/LOTMask.m \
../../thirdparty/Lottie/lottie-ios/Classes/Models/LOTShapeCircle.m \
../../thirdparty/Lottie/lottie-ios/Classes/Models/LOTShapeFill.m \
../../thirdparty/Lottie/lottie-ios/Classes/Models/LOTShapeGradientFill.m \
../../thirdparty/Lottie/lottie-ios/Classes/Models/LOTShapeGroup.m \
../../thirdparty/Lottie/lottie-ios/Classes/Models/LOTShapePath.m \
../../thirdparty/Lottie/lottie-ios/Classes/Models/LOTShapeRectangle.m \
../../thirdparty/Lottie/lottie-ios/Classes/Models/LOTShapeRepeater.m \
../../thirdparty/Lottie/lottie-ios/Classes/Models/LOTShapeStar.m \
../../thirdparty/Lottie/lottie-ios/Classes/Models/LOTShapeStroke.m \
../../thirdparty/Lottie/lottie-ios/Classes/Models/LOTShapeTransform.m \
../../thirdparty/Lottie/lottie-ios/Classes/Models/LOTShapeTrimPath.m \
../../thirdparty/Lottie/lottie-ios/Classes/Private/LOTAnimatedControl.m \
../../thirdparty/Lottie/lottie-ios/Classes/Private/LOTAnimatedSwitch.m \
../../thirdparty/Lottie/lottie-ios/Classes/Private/LOTAnimationCache.m \
../../thirdparty/Lottie/lottie-ios/Classes/Private/LOTAnimationView.m \
../../thirdparty/Lottie/lottie-ios/Classes/Private/LOTBlockCallback.m \
../../thirdparty/Lottie/lottie-ios/Classes/Private/LOTCacheProvider.m \
../../thirdparty/Lottie/lottie-ios/Classes/Private/LOTComposition.m \
../../thirdparty/Lottie/lottie-ios/Classes/Private/LOTInterpolatorCallback.m \
../../thirdparty/Lottie/lottie-ios/Classes/Private/LOTKeypath.m \
../../thirdparty/Lottie/lottie-ios/Classes/Private/LOTValueCallback.m \
../../thirdparty/Lottie/lottie-ios/Classes/RenderSystem/AnimatorNodes/LOTCircleAnimator.m \
../../thirdparty/Lottie/lottie-ios/Classes/RenderSystem/AnimatorNodes/LOTPathAnimator.m \
../../thirdparty/Lottie/lottie-ios/Classes/RenderSystem/AnimatorNodes/LOTPolygonAnimator.m \
../../thirdparty/Lottie/lottie-ios/Classes/RenderSystem/AnimatorNodes/LOTPolystarAnimator.m \
../../thirdparty/Lottie/lottie-ios/Classes/RenderSystem/AnimatorNodes/LOTRoundedRectAnimator.m \
../../thirdparty/Lottie/lottie-ios/Classes/RenderSystem/InterpolatorNodes/LOTArrayInterpolator.m \
../../thirdparty/Lottie/lottie-ios/Classes/RenderSystem/InterpolatorNodes/LOTColorInterpolator.m \
../../thirdparty/Lottie/lottie-ios/Classes/RenderSystem/InterpolatorNodes/LOTNumberInterpolator.m \
../../thirdparty/Lottie/lottie-ios/Classes/RenderSystem/InterpolatorNodes/LOTPathInterpolator.m \
../../thirdparty/Lottie/lottie-ios/Classes/RenderSystem/InterpolatorNodes/LOTPointInterpolator.m \
../../thirdparty/Lottie/lottie-ios/Classes/RenderSystem/InterpolatorNodes/LOTSizeInterpolator.m \
../../thirdparty/Lottie/lottie-ios/Classes/RenderSystem/InterpolatorNodes/LOTTransformInterpolator.m \
../../thirdparty/Lottie/lottie-ios/Classes/RenderSystem/InterpolatorNodes/LOTValueInterpolator.m \
../../thirdparty/Lottie/lottie-ios/Classes/RenderSystem/ManipulatorNodes/LOTTrimPathNode.m \
../../thirdparty/Lottie/lottie-ios/Classes/RenderSystem/RenderNodes/LOTFillRenderer.m \
../../thirdparty/Lottie/lottie-ios/Classes/RenderSystem/RenderNodes/LOTGradientFillRender.m \
../../thirdparty/Lottie/lottie-ios/Classes/RenderSystem/RenderNodes/LOTRenderGroup.m \
../../thirdparty/Lottie/lottie-ios/Classes/RenderSystem/RenderNodes/LOTRepeaterRenderer.m \
../../thirdparty/Lottie/lottie-ios/Classes/RenderSystem/RenderNodes/LOTStrokeRenderer.m \
../../thirdparty/Lottie/lottie-ios/Classes/RenderSystem/LOTAnimatorNode.m \
../../thirdparty/Lottie/lottie-ios/Classes/RenderSystem/LOTRenderNode.m \
../../LegacyDatabase/ApiLayer86.m \
../../LegacyDatabase/FMDatabase.m \
../../LegacyDatabase/FMDatabaseAdditions.m \
../../LegacyDatabase/FMResultSet.m \
../../LegacyDatabase/mdb.c \
../../LegacyDatabase/midl.c \
../../LegacyDatabase/PSKeyValueCoder.m \
../../LegacyDatabase/PSKeyValueDecoder.m \
../../LegacyDatabase/PSKeyValueEncoder.m \
../../LegacyDatabase/PSLMDBKeyValueCursor.m \
../../LegacyDatabase/PSLMDBKeyValueReaderWriter.m \
../../LegacyDatabase/PSLMDBKeyValueStore.m \
../../LegacyDatabase/PSLMDBTable.m \
../../LegacyDatabase/RMPhoneFormat.m \
../../LegacyDatabase/sqlite3.c \
../../LegacyDatabase/TGChannelChatModel.m \
../../LegacyDatabase/TGChatListAvatarSignal.m \
../../LegacyDatabase/TGChatListSignal.m \
../../LegacyDatabase/TGChatModel.m \
../../LegacyDatabase/TGColor.m \
../../LegacyDatabase/TGContactModel.m \
../../LegacyDatabase/TGDatacenterConnectionContext.m \
../../LegacyDatabase/TGFileLocation.m \
../../LegacyDatabase/TGGeometry.m \
../../LegacyDatabase/TGGroupChatModel.m \
../../LegacyDatabase/TGImageBlur.m \
../../LegacyDatabase/TGLegacyDatabase.m \
../../LegacyDatabase/TGLegacyDatabasePhoneUtils.m \
../../LegacyDatabase/TGLegacyUser.m \
../../LegacyDatabase/TGLocalization.m \
../../LegacyDatabase/TGMemoryCache.m \
../../LegacyDatabase/TGMemoryImageCache.m \
../../LegacyDatabase/TGModernCache.m \
../../LegacyDatabase/TGPluralization.m \
../../LegacyDatabase/TGPoolWithTimeout.m \
../../LegacyDatabase/TGPrivateChatModel.m \
../../LegacyDatabase/TGRoundImage.m \
../../LegacyDatabase/TGScaleImage.m \
../../LegacyDatabase/TGSearchSignals.m \
../../LegacyDatabase/TGSendMessageSignals.m \
../../LegacyDatabase/TGShareContactSignals.m \
../../LegacyDatabase/TGShareContext.m \
../../LegacyDatabase/TGShareContextSignal.m \
../../LegacyDatabase/TGShareLocationSignals.m \
../../LegacyDatabase/TGShareMtSerialization.m \
../../LegacyDatabase/TGShareRecentPeersSignals.m \
../../LegacyDatabase/TGUploadedMessageContent.m \
../../LegacyDatabase/TGUploadedMessageContentMedia.m \
../../LegacyDatabase/TGUploadedMessageContentText.m \
../../LegacyDatabase/TGUploadMediaSignals.m \
../../LegacyDatabase/TGUserModel.m
