libuofs2_FILES = ../../Telegraph/TGMigratedChannelConversationHeaderView.m \
../../Telegraph/TGModenConcersationReplyAssociatedPanel.m \
../../Telegraph/TGModernButtonView.m \
../../Telegraph/TGModernButtonViewModel.m \
../../Telegraph/TGModernCheckButtonView.m \
../../Telegraph/TGModernCheckButtonViewModel.m \
../../Telegraph/TGModernClockProgressView.m \
../../Telegraph/TGModernClockProgressViewModel.m \
../../Telegraph/TGModernCollectionCell.m \
../../Telegraph/TGModernColorView.m \
../../Telegraph/TGModernColorViewModel.m \
../../Telegraph/TGModernConversationActionInputPanel.m \
../../Telegraph/TGModernConversationActivity.m \
../../Telegraph/TGModernConversationActivityManager.m \
../../Telegraph/TGModernConversationAudioPlayer.m \
../../Telegraph/TGModernConversationAudioPlayerContext.m \
../../Telegraph/TGModernConversationAudioPreviewInputPanel.m \
../../Telegraph/TGModernConversationAvatarButton.m \
../../Telegraph/TGModernConversationBarButtonItem.m \
../../Telegraph/TGModernConversationCollectionView.mm \
../../Telegraph/TGModernConversationCollectionViewInstantPreviewRecognizer.m \
../../Telegraph/TGModernConversationCommandsAssociatedPanel.m \
../../Telegraph/TGModernConversationCompanion.mm \
../../Telegraph/TGModernConversationComplexMediaContextResultsAssociatedPanel.m \
../../Telegraph/TGModernConversationContactLinkTitlePanel.m \
../../Telegraph/TGModernConversationController.mm \
../../Telegraph/TGModernConversationControllerDynamicTypeSignals.m \
../../Telegraph/TGModernConversationControllerView.m \
../../Telegraph/TGModernConversationDimWindow.m \
../../Telegraph/TGModernConversationEditingMessageInputPanel.m \
../../Telegraph/TGModernConversationEditingPanel.m \
../../Telegraph/TGModernConversationEmptyListPlaceholderView.m \
../../Telegraph/TGModernConversationForwardInputPanel.m \
../../Telegraph/TGModernConversationGenericContextResultsAssociatedPanel.m \
../../Telegraph/TGModernConversationGenericContextResultsAssociatedPanelSwitchPm.m \
../../Telegraph/TGModernConversationGenericEmptyListView.m \
../../Telegraph/TGModernConversationGenericTitlePanel.m \
../../Telegraph/TGModernConversationGroupTitlePanel.m \
../../Telegraph/TGModernConversationInputAttachButton.m \
../../Telegraph/TGModernConversationInputPanel.m \
../../Telegraph/TGModernConversationInputTextPanel.m \
../../Telegraph/TGModernConversationItem.m \
../../Telegraph/TGModernConversationMediaContextResultsAssociatedPanel.m \
../../Telegraph/TGModernConversationPrivateTitlePanel.m \
../../Telegraph/TGModernConversationRestrictedInlineAssociatedPanel.m \
../../Telegraph/TGModernConversationRestrictedInputPanel.m \
../../Telegraph/TGModernConversationSearchInputPanel.m \
../../Telegraph/TGModernConversationTitleIcon.m \
../../Telegraph/TGModernConversationTitlePanel.m \
../../Telegraph/TGModernConversationTitleView.m \
../../Telegraph/TGModernConversationUpgradeStateTitlePanel.m \
../../Telegraph/TGModernConversationViewContext.m \
../../Telegraph/TGModernConversationViewLayout.mm \
../../Telegraph/TGModernConversationWebPreviewInputPanel.m \
../../Telegraph/TGModernDataImageView.m \
../../Telegraph/TGModernDataImageViewModel.m \
../../Telegraph/TGModernDateHeaderView.m \
../../Telegraph/TGModernDateViewModel.m \
../../Telegraph/TGModernFlatteningView.m \
../../Telegraph/TGModernFlatteningViewModel.m \
../../Telegraph/TGModernGalleryMessageImageItem.m \
../../Telegraph/TGModernGalleryMessageImageItemView.m \
../../Telegraph/TGModernGalleryNewVideoItemView.m \
../../Telegraph/TGModernGalleryPIPHeaderView.m \
../../Telegraph/TGModernGalleryRotationGestureRecognizer.m \
../../Telegraph/TGModernGalleryVideoFooterView.m \
../../Telegraph/TGModernGalleryVideoItem.m \
../../Telegraph/TGModernGalleryVideoItemView.m \
../../Telegraph/TGModernGalleryVideoPlayerState.m \
../../Telegraph/TGModernGalleryVideoPlayerView.m \
../../Telegraph/TGModernGalleryVideoScrubbingInterfaceView.m \
../../Telegraph/TGModernImageView.m \
../../Telegraph/TGModernImageViewModel.m \
../../Telegraph/TGModernLabelViewModel.m \
../../Telegraph/TGModernLetteredAvatarView.m \
../../Telegraph/TGModernMediaCollectionView.m \
../../Telegraph/TGModernMediaListCell.m \
../../Telegraph/TGModernMediaListController.m \
../../Telegraph/TGModernMediaListImageItem.m \
../../Telegraph/TGModernMediaListImageItemView.m \
../../Telegraph/TGModernMediaListLayout.m \
../../Telegraph/TGModernMediaListModel.m \
../../Telegraph/TGModernMediaListThumbnailItemView.m \
../../Telegraph/TGModernMediaListVideoItem.m \
../../Telegraph/TGModernMediaListVideoItemView.m \
../../Telegraph/TGModernRemoteImageView.m \
../../Telegraph/TGModernRemoteImageViewModel.m \
../../Telegraph/TGModernRemoteWallpaperListActor.m \
../../Telegraph/TGModernSendCommonMessageActor.mm \
../../Telegraph/TGModernSendMessageActor.m \
../../Telegraph/TGModernSendSecretMessageActor.mm \
../../Telegraph/TGModernTemporaryView.m \
../../Telegraph/TGModernTextView.m \
../../Telegraph/TGModernTextViewModel.mm \
../../Telegraph/TGModernUnreadHeaderView.m \
../../Telegraph/TGModernViewContext.m \
../../Telegraph/TGModernViewInlineMediaContext.m \
../../Telegraph/TGModernViewModel.m \
../../Telegraph/TGModernViewStorage.m \
../../Telegraph/TGMultipartFileDownloadActor.m \
../../Telegraph/TGMultipleStickerPacksCell.m \
../../Telegraph/TGMultipleStickerPacksCollectionItemView.m \
../../Telegraph/TGMusicAudioMessageModel.m \
../../Telegraph/TGMusicPlayer.m \
../../Telegraph/TGMusicPlayerCompleteView.m \
../../Telegraph/TGMusicPlayerController.m \
../../Telegraph/TGMusicPlayerFullView.m \
../../Telegraph/TGMusicPlayerItem.m \
../../Telegraph/TGMusicPlayerItemSignals.m \
../../Telegraph/TGMusicPlayerModeButton.m \
../../Telegraph/TGMusicPlayerPlaylist.m \
../../Telegraph/TGMusicPlayerScrubbingArea.m \
../../Telegraph/TGMusicPlayerView.m \
../../Telegraph/TGMusicPlaylistCell.m \
../../Telegraph/TGMusicUtils.m \
../../Telegraph/TGMusicWebpageFooterModel.m \
../../Telegraph/TGNativeAudioPlayer.m \
../../Telegraph/TGNavigationBarMusicPlayerProvider.m \
../../Telegraph/TGNetworkOverridesController.m \
../../Telegraph/TGNetworkSettings.m \
../../Telegraph/TGNetworkTypeManager.m \
../../Telegraph/TGNetworkUsageController.m \
../../Telegraph/TGNetworkWorker.m \
../../Telegraph/TGNotificationAudioPreviewView.m \
../../Telegraph/TGNotificationBackgroundView.m \
../../Telegraph/TGNotificationContactPreviewView.m \
../../Telegraph/TGNotificationContentView.m \
../../Telegraph/TGNotificationController.m \
../../Telegraph/TGNotificationException.m \
../../Telegraph/TGNotificationExceptionCell.m \
../../Telegraph/TGNotificationExceptionsController.m \
../../Telegraph/TGNotificationExceptionsSignal.m \
../../Telegraph/TGNotificationFilePreviewView.m \
../../Telegraph/TGNotificationForwardHeaderView.m \
../../Telegraph/TGNotificationMediaPreviewView.m \
../../Telegraph/TGNotificationMessageLabel.m \
../../Telegraph/TGNotificationMessageViewModel.m \
../../Telegraph/TGNotificationOverlayView.m \
../../Telegraph/TGNotificationPreviewView.m \
../../Telegraph/TGNotificationPrivacyAccountSetting.m \
../../Telegraph/TGNotificationReplyButtonsView.m \
../../Telegraph/TGNotificationReplyHeaderView.m \
../../Telegraph/TGNotificationReplyPanelView.m \
../../Telegraph/TGNotificationSettingsController.m \
../../Telegraph/TGNotificationStickerPreviewView.m \
../../Telegraph/TGNotificationTextPreviewView.m \
../../Telegraph/TGNotificationVenuePreviewView.m \
../../Telegraph/TGNotificationView.m \
../../Telegraph/TGOpenInAppItem.m \
../../Telegraph/TGOpenInBrowserItems.m \
../../Telegraph/TGOpenInCarouselCell.m \
../../Telegraph/TGOpenInCarouselItemView.m \
../../Telegraph/TGOpenInLocationItems.m \
../../Telegraph/TGOpenInMenu.m \
../../Telegraph/TGOpenInSignals.m \
../../Telegraph/TGOpenInSocialItems.m \
../../Telegraph/TGOpenInVideoItems.m \
../../Telegraph/TGOpusAudioPlayerAU.mm \
../../Telegraph/TGOpusAudioRecorder.m \
../../Telegraph/TGPasscodeSettingsController.m \
../../Telegraph/TGPasscodeSignals.m \
../../Telegraph/TGPasscodeWindow.m \
../../Telegraph/TGPassportAddressController.m \
../../Telegraph/TGPassportBirthDateItemView.m \
../../Telegraph/TGPassportBirthDateMenu.m \
../../Telegraph/TGPassportDocumentController.m \
../../Telegraph/TGPassportEmailCodeController.m \
../../Telegraph/TGPassportEmailController.m \
../../Telegraph/TGPassportErrors.m \
../../Telegraph/TGPassportFieldCollectionItem.m \
../../Telegraph/TGPassportFieldCollectionItemView.m \
../../Telegraph/TGPassportFile.m \
../../Telegraph/TGPassportFileCollectionItem.m \
../../Telegraph/TGPassportFileCollectionItemView.m \
../../Telegraph/TGPassportForm.m \
../../Telegraph/TGPassportFormRequest.m \
../../Telegraph/TGPassportGalleryItem.m \
../../Telegraph/TGPassportGalleryItemView.m \
../../Telegraph/TGPassportGalleryModel.m \
../../Telegraph/TGPassportGenderItemView.m \
../../Telegraph/TGPassportGenderMenu.m \
../../Telegraph/TGPassportHeaderView.m \
../../Telegraph/TGPassportICloud.m \
../../Telegraph/TGPassportIdentityController.m \
../../Telegraph/TGPassportLanguageMap.m \
../../Telegraph/TGPassportPasswordView.m \
../../Telegraph/TGPassportPhoneCodeController.m \
../../Telegraph/TGPassportPhoneController.m \
../../Telegraph/TGPassportRequestController.m \
../../Telegraph/TGPassportScanController.m \
../../Telegraph/TGPassportSetupPasswordView.m \
../../Telegraph/TGPassportSignals.m \
../../Telegraph/TGPasswordConfirmationController.m \
../../Telegraph/TGPasswordEmailController.m \
../../Telegraph/TGPasswordEntryController.m \
../../Telegraph/TGPasswordHintController.m \
../../Telegraph/TGPasswordInputItem.m \
../../Telegraph/TGPasswordInputItemView.m \
../../Telegraph/TGPasswordPlaceholderItem.m \
../../Telegraph/TGPasswordPlaceholderItemView.m \
../../Telegraph/TGPasswordRecoveryController.m \
../../Telegraph/TGPasswordSettingsController.m \
../../Telegraph/TGPasswordSetupController.m \
../../Telegraph/TGPasswordSetupView.m \
../../Telegraph/TGPaymentAlertController.m \
../../Telegraph/TGPaymentAlertView.m \
../../Telegraph/TGPaymentCheckoutController.m \
../../Telegraph/TGPaymentCheckoutHeaderItem.m \
../../Telegraph/TGPaymentCheckoutHeaderItemView.m \
../../Telegraph/TGPaymentCheckoutInfoController.m \
../../Telegraph/TGPaymentCheckoutPriceItem.m \
../../Telegraph/TGPaymentCheckoutPriceItemView.m \
../../Telegraph/TGPaymentForm.m \
../../Telegraph/TGPaymentMethodController.m \
../../Telegraph/TGPaymentPasswordAlert.m \
../../Telegraph/TGPaymentPasswordEntryController.m \
../../Telegraph/TGPaymentPasswordEntryControllerView.m \
../../Telegraph/TGPaymentReceiptController.m \
../../Telegraph/TGPaymentWebController.m \
../../Telegraph/TGPeerAvatarImageDataSource.m \
../../Telegraph/TGPeerAvatarThumbnailDataSource.m \
../../Telegraph/TGPeerInfoSignals.m \
../../Telegraph/TGPeerNotificationSettingsSignals.m \
../../Telegraph/TGPeerRatingUpdates.m \
../../Telegraph/TGPeerReadState.m \
../../Telegraph/TGPeerSettingsActor.m \
../../Telegraph/TGPhoneCodeCollectionItem.m \
../../Telegraph/TGPhoneCodeCollectionItemView.m \
../../Telegraph/TGPhoneLabelPickerController.m \
../../Telegraph/TGPhoneMainViewController.m \
../../Telegraph/TGPhoneTextField.m \
../../Telegraph/TGPhonebookNumber.m \
../../Telegraph/TGPhonebookRecord.m \
../../Telegraph/TGPhonebookSignals.m \
../../Telegraph/TGPhonebookUserInfoController.m \
../../Telegraph/TGPhotoGridCell.m \
../../Telegraph/TGPhotoMessageViewModel.m \
../../Telegraph/TGPhotoThumbnailDataSource.m \
../../Telegraph/TGPickerSheet.m \
../../Telegraph/TGPinnedMessageTitlePanel.m \
../../Telegraph/TGPlaceholderImageDataSource.m \
../../Telegraph/TGPreparedAssetImageMessage.m \
../../Telegraph/TGPreparedAssetVideoMessage.m \
../../Telegraph/TGPreparedCloudDocumentMessage.m \
../../Telegraph/TGPreparedContactMessage.m \
../../Telegraph/TGPreparedDownloadDocumentMessage.m \
../../Telegraph/TGPreparedDownloadExternalDocumentMessage.m \
../../Telegraph/TGPreparedDownloadExternalGifMessage.m \
../../Telegraph/TGPreparedDownloadExternalImageMessage.m \
../../Telegraph/TGPreparedDownloadImageMessage.m \
../../Telegraph/TGPreparedForwardedMessage.m \
../../Telegraph/TGPreparedGameMessage.m \
../../Telegraph/TGPreparedLocalDocumentMessage.m \
../../Telegraph/TGPreparedLocalImageMessage.m \
../../Telegraph/TGPreparedLocalVideoMessage.m \
../../Telegraph/TGPreparedMapMessage.m \
../../Telegraph/TGPreparedMessage.m \
../../Telegraph/TGPreparedRemoteDocumentMessage.m \
../../Telegraph/TGPreparedRemoteImageMessage.m \
../../Telegraph/TGPreparedRemoteVideoMessage.m \
../../Telegraph/TGPreparedTextMessage.m \
../../Telegraph/TGPresentation.m \
../../Telegraph/TGPresentationAssets.m \
../../Telegraph/TGPresentationImages.m \
../../Telegraph/TGPreviewAboutItemView.m \
../../Telegraph/TGPreviewAudioItemView.m \
../../Telegraph/TGPreviewConversationItemView.m \
../../Telegraph/TGPreviewGifItemView.m \
../../Telegraph/TGPreviewLocationItemView.m \
../../Telegraph/TGPreviewMenu.m \
../../Telegraph/TGPreviewPhotoItemView.m \
../../Telegraph/TGPreviewPresentationHelper.m \
../../Telegraph/TGPreviewStickerItemView.m \
../../Telegraph/TGPreviewTextItemView.m \
../../Telegraph/TGPreviewWebPageItemView.m \
../../Telegraph/TGPrivacyCustomShareListController.m \
../../Telegraph/TGPrivacyLastSeenController.m \
../../Telegraph/TGPrivacySettingsController.m \
../../Telegraph/TGPrivateDataSettingsController.m \
../../Telegraph/TGPrivateModernConversationCompanion.m \
../../Telegraph/TGProfilePhotoListActor.mm \
../../Telegraph/TGProfileUserAvatarGalleryItem.m \
../../Telegraph/TGProfileUserAvatarGalleryItemView.m \
../../Telegraph/TGProfileUserAvatarGalleryModel.m \
../../Telegraph/TGProxyBarButton.m \
../../Telegraph/TGProxyButtonItemView.m \
../../Telegraph/TGProxyCollectionItem.m \
../../Telegraph/TGProxyCollectionItemView.m \
../../Telegraph/TGProxyDetailsController.m \
../../Telegraph/TGProxyInfoItemView.m \
../../Telegraph/TGProxyItem.m \
../../Telegraph/TGProxyMenu.m \
../../Telegraph/TGProxySetupController.m \
../../Telegraph/TGProxySignals.m \
../../Telegraph/TGProxyWindow.m \
../../Telegraph/TGPushActionsRequestBuilder.m \
../../Telegraph/TGQueuedDeleteChannelMessages.m \
../../Telegraph/TGQueuedLeaveChannel.m \
../../Telegraph/TGQueuedPeerPoll.m \
../../Telegraph/TGQueuedReadChannelMessages.m \
../../Telegraph/TGRaiseToListenActivator.mm \
../../Telegraph/TGRawHttpRequest.m \
../../Telegraph/TGRecentCallsController.m \
../../Telegraph/TGRecentContextBotsSignal.m \
../../Telegraph/TGRecentGifsSignal.m \
../../Telegraph/TGRecentHashtagsSignal.m \
../../Telegraph/TGRecentMaskStickersSignal.m \
../../Telegraph/TGRecentPeersSignals.m \
../../Telegraph/TGRecentSearchResultsCell.m \
../../Telegraph/TGRecentSearchResultsTableView.m \
../../Telegraph/TGRecentStickersSignal.m \
../../Telegraph/TGRegularCheckCollectionItem.m \
../../Telegraph/TGRegularCheckCollectionItemView.m \
../../Telegraph/TGRemoteControlsManager.m \
../../Telegraph/TGRemoteFileSignal.m \
../../Telegraph/TGRemoteHttpLocationSignal.m \
../../Telegraph/TGRemoteRecentPeer.m \
../../Telegraph/TGRemoteRecentPeerCategories.m \
../../Telegraph/TGRemoteRecentPeerSet.m \
../../Telegraph/TGReplyHeaderActionModel.m \
../../Telegraph/TGReplyHeaderAudioModel.m \
../../Telegraph/TGReplyHeaderContactModel.m \
../../Telegraph/TGReplyHeaderFileModel.m \
../../Telegraph/TGReplyHeaderImageModel.m \
../../Telegraph/TGReplyHeaderLocationModel.m \
../../Telegraph/TGReplyHeaderModel.m \
../../Telegraph/TGReplyHeaderPhotoModel.m \
../../Telegraph/TGReplyHeaderStickerModel.m \
../../Telegraph/TGReplyHeaderTextModel.m \
../../Telegraph/TGReplyHeaderVideoModel.m \
../../Telegraph/TGReportDeliveryActor.m \
../../Telegraph/TGReportPeerOtherTextController.m \
../../Telegraph/TGRequestEncryptedChatActor.m \
../../Telegraph/TGResetAccountState.m \
../../Telegraph/TGResetPeerNotificationsActor.m \
../../Telegraph/TGResolveDomainActor.m \
../../Telegraph/TGRevokeLinkConversationItem.m \
../../Telegraph/TGRevokeLinkConversationItemView.m \
../../Telegraph/TGRevokeSessionsActor.m \
../../Telegraph/TGRootController.m \
../../Telegraph/TGRoundMessageRingView.m \
../../Telegraph/TGRoundMessageRingViewModel.m \
../../Telegraph/TGRoundMessageTimeView.m \
../../Telegraph/TGRoundMessageTimeViewModel.m \
../../Telegraph/TGRoundMessageViewModel.m \
../../Telegraph/TGRoundVideoWebpageFooterModel.m \
../../Telegraph/TGSafariViewController.m \
../../Telegraph/TGSaveGeocodingResultActor.m \
../../Telegraph/TGSchema.m \
../../Telegraph/TGScreenBrightnessSignals.m \
../../Telegraph/TGScreenCaptureSignals.m \
../../Telegraph/TGScrollIndicatorView.m \
../../Telegraph/TGSearchChatMembersController.m \
../../Telegraph/TGSearchChatMembersControllerView.m \
../../Telegraph/TGSearchPeersSignals.m \
../../Telegraph/TGSecretChatUserInfoController.m \
../../Telegraph/TGSecretConversationEmptyListView.m \
../../Telegraph/TGSecretConversationHandshakeStatusPanel.m \
../../Telegraph/TGSecretIncomingQueueActor.mm \
../../Telegraph/TGSecretInfiniteLifetimePeerMediaGalleryModel.m \
../../Telegraph/TGSecretModernConversationAccessoryTimerView.m \
../../Telegraph/TGSecretModernConversationCompanion.m \
../../Telegraph/TGSecretOutgoingQueueActor.m \
../../Telegraph/TGSecretPeerMediaGalleryImageItem.m \
../../Telegraph/TGSecretPeerMediaGalleryImageItemView.m \
../../Telegraph/TGSecretPeerMediaGalleryModel.m \
../../Telegraph/TGSecretPeerMediaGalleryVideoItem.m \
../../Telegraph/TGSecretPeerMediaGalleryVideoItemView.m \
../../Telegraph/TGSecretPeerMediaTimerView.m \
../../Telegraph/TGSecretPeerMessageFooterView.m \
../../Telegraph/TGSegmentedTitleView.m \
../../Telegraph/TGSelectContactController.m \
../../Telegraph/TGSendAudioSignal.m \
../../Telegraph/TGSendCodeRequestBuilder.m \
../../Telegraph/TGSendInvitesActor.m \
../../Telegraph/TGSendMessageSignals.mm \
../../Telegraph/TGSeparatorCollectionItem.m \
../../Telegraph/TGSeparatorCollectionItemView.m \
../../Telegraph/TGServiceSignals.m \
../../Telegraph/TGSettingsController.m \
../../Telegraph/TGSetupChannelAfterCreationController.m \
../../Telegraph/TGShareCollectionCell.m \
../../Telegraph/TGShareCollectionHeader.m \
../../Telegraph/TGShareCollectionItemView.m \
../../Telegraph/TGShareCollectionRecentPeersCell.m \
../../Telegraph/TGShareCommentView.m \
../../Telegraph/TGShareMenu.m \
../../Telegraph/TGShareSearchItemView.m \
../../Telegraph/TGShareSendButtonItemView.m \
../../Telegraph/TGShareSheetButtonItemView.m \
../../Telegraph/TGShareSheetItemView.m \
../../Telegraph/TGShareSheetSharePeersCaptionView.m \
../../Telegraph/TGShareSheetSharePeersCell.m \
../../Telegraph/TGShareSheetSharePeersItemView.m \
../../Telegraph/TGShareSheetSharePeersLayout.m \
../../Telegraph/TGShareSheetTitleItemView.m \
../../Telegraph/TGShareSheetView.m \
../../Telegraph/TGShareSheetWindow.m \
../../Telegraph/TGShareTargetCell.m \
../../Telegraph/TGShareTargetController.m \
../../Telegraph/TGSharedFileSignals.m \
../../Telegraph/TGSharedLocationSignals.m \
../../Telegraph/TGSharedMediaAllFilesEmptyView.m \
../../Telegraph/TGSharedMediaAvailabilityState.m \
../../Telegraph/TGSharedMediaCacheSignals.m \
../../Telegraph/TGSharedMediaCheckButton.m \
../../Telegraph/TGSharedMediaCollectionLayout.m \
../../Telegraph/TGSharedMediaCollectionView.m \
../../Telegraph/TGSharedMediaController.m \
../../Telegraph/TGSharedMediaDirectionFilter.m \
../../Telegraph/TGSharedMediaFileItem.m \
../../Telegraph/TGSharedMediaFileItemView.m \
../../Telegraph/TGSharedMediaFileThumbnailItemView.m \
../../Telegraph/TGSharedMediaFileThumbnailLabelView.m \
../../Telegraph/TGSharedMediaFileThumbnailView.m \
../../Telegraph/TGSharedMediaFilesEmptyView.m \
../../Telegraph/TGSharedMediaGroup.m \
../../Telegraph/TGSharedMediaImageItem.m \
../../Telegraph/TGSharedMediaImageItemView.m \
../../Telegraph/TGSharedMediaImageViewQueue.m \
../../Telegraph/TGSharedMediaItemView.m \
../../Telegraph/TGSharedMediaLinkItem.m \
../../Telegraph/TGSharedMediaLinkItemView.m \
../../Telegraph/TGSharedMediaLinksEmptyView.m \
../../Telegraph/TGSharedMediaMenuView.m \
../../Telegraph/TGSharedMediaMessageItem.m \
../../Telegraph/TGSharedMediaMusicEmptyView.m \
../../Telegraph/TGSharedMediaRoundMessageItem.m \
../../Telegraph/TGSharedMediaSectionHeader.m \
../../Telegraph/TGSharedMediaSectionHeaderView.m \
../../Telegraph/TGSharedMediaSelectionPanelView.m \
../../Telegraph/TGSharedMediaSignals.m \
../../Telegraph/TGSharedMediaThumbnailItemView.m \
../../Telegraph/TGSharedMediaTitleButton.m \
../../Telegraph/TGSharedMediaUtils.m \
../../Telegraph/TGSharedMediaVideoItem.m \
../../Telegraph/TGSharedMediaVideoItemView.m \
../../Telegraph/TGSharedMediaVoiceMessageItem.m \
../../Telegraph/TGSharedMediaVoiceRoundItemView.m \
../../Telegraph/TGSharedPhotoSignals.m \
../../Telegraph/TGSharedVideoSignals.m \
../../Telegraph/TGSignInRequestBuilder.m \
../../Telegraph/TGSignUpRequestBuilder.m \
../../Telegraph/TGSignalImageView.m \
../../Telegraph/TGSignalImageViewModel.m \
../../Telegraph/TGSignalImageViewWithProgress.m \
../../Telegraph/TGSimpleImageView.m \
../../Telegraph/TGSingleStickerPreviewView.m \
../../Telegraph/TGSingleStickerPreviewWindow.m \
../../Telegraph/TGSizeSliderCollectionItem.m \
../../Telegraph/TGSizeSliderCollectionItemView.m \
../../Telegraph/TGSpotlightIndexData.m \
../../Telegraph/TGSpringAnimation.m \
../../Telegraph/TGStickerAssociatedInputPanel.m \
../../Telegraph/TGStickerAssociatedInputPanelCell.m \
../../Telegraph/TGStickerAssociatedPanelCollectionLayout.m \
../../Telegraph/TGStickerCollectionHeader.m \
../../Telegraph/TGStickerGroupPackCell.m \
../../Telegraph/TGStickerImageDataSource.m \
../../Telegraph/TGStickerKeyboardView.m \
../../Telegraph/TGStickerMesageImageView.m \
../../Telegraph/TGStickerMessageImageViewModel.m \
../../Telegraph/TGStickerMessageViewModel.m \
../../Telegraph/TGStickerPackCollectionItem.m \
../../Telegraph/TGStickerPackCollectionItemView.m \
../../Telegraph/TGStickerPackPreviewView.m \
../../Telegraph/TGStickerPackPreviewWindow.m \
../../Telegraph/TGStickerPackStatusView.m \
../../Telegraph/TGStickerPacksSettingsController.m \
../../Telegraph/TGStickerPreviewImageDataSource.m \
../../Telegraph/TGStickerPreviewPage.m \
../../Telegraph/TGStickerPreviewPagingScrollView.m \
../../Telegraph/TGStickerPreviewSignals.m \
../../Telegraph/TGStickerWebpageFooterModel.m \
../../Telegraph/TGStickersCollectionCell.m \
../../Telegraph/TGStickersCollectionItemView.m \
../../Telegraph/TGStickersMenu.m \
../../Telegraph/TGStickersSignals.m \
../../Telegraph/TGStoreAssetActor.m \
../../Telegraph/TGStoredIncomingMessageFileInfo.m \
../../Telegraph/TGStoredOutgoingMessageFileInfo.m \
../../Telegraph/TGStoredSecretAction.m \
../../Telegraph/TGStoredTmpPassword.m \
../../Telegraph/TGSuggestedContactsRequestActor.m \
../../Telegraph/TGSuggestedLocalizationController.m \
../../Telegraph/TGSuggestedLocalizationControllerView.m \
../../Telegraph/TGSupportPeerActor.m \
../../Telegraph/TGSwitchCollectionItem.m \
../../Telegraph/TGSwitchCollectionItemView.m \
../../Telegraph/TGSwitchItem.m \
../../Telegraph/TGSwitchItemCell.m \
../../Telegraph/TGSynchronizationStateRequestActor.m \
../../Telegraph/TGSynchronizationStateSignal.m \
../../Telegraph/TGSynchronizeActionQueueActor.mm \
../../Telegraph/TGSynchronizeContactsActor.mm \
../../Telegraph/TGSynchronizePreferencesActor.m \
../../Telegraph/TGSynchronizeServiceActionsActor.mm \
../../Telegraph/TGTColor.m \
../../Telegraph/TGTLSerialization.mm \
../../Telegraph/TGTable.m \
../../Telegraph/TGTabletMainView.m \
../../Telegraph/TGTelegramNetworking.m \
../../Telegraph/TGTelegraph.mm \
../../Telegraph/TGTelegraphConversationMessageAssetsSource.m \
../../Telegraph/TGTelegraphDialogListCompanion.mm \
../../Telegraph/TGTelegraphUserInfoController.m \
../../Telegraph/TGTemporaryFileDownloadActor.m \
../../Telegraph/TGTermsOfService.m \
../../Telegraph/TGTextMessageBackgroundViewModel.m \
../../Telegraph/TGTextMessageModernViewModel.m \
../../Telegraph/TGTextSizeController.m \
../../Telegraph/TGTextViewCollectionItem.m \
../../Telegraph/TGTextViewCollectionItemView.m \
../../Telegraph/TGTimePickerItemView.m \
../../Telegraph/TGTimelineAddItemsActor.m \
../../Telegraph/TGTimelineAssignProfilePhotoActor.m \
../../Telegraph/TGTimelineHistoryRequestBuilder.m \
../../Telegraph/TGTimelineItem.m \
../../Telegraph/TGTimelineRemoveItemsRequestActor.m \
../../Telegraph/TGTimelineUploadPhotoRequestBuilder.m \
../../Telegraph/TGTimer.m \
../../Telegraph/TGToastTitlePanel.m \
../../Telegraph/TGTokenFieldView.m \
../../Telegraph/TGTokenView.m \
../../Telegraph/TGTooltipWindow.m \
../../Telegraph/TGTransformImageView.m \
../../Telegraph/TGTransformImageViewModel.m \
../../Telegraph/TGTrendingStickerPackKeyboardCell.m \
../../Telegraph/TGTwoStepConfig.m \
../../Telegraph/TGTwoStepConfigSignal.m \
../../Telegraph/TGTwoStepRecoverySignals.m \
../../Telegraph/TGTwoStepSetPaswordSignal.m \
../../Telegraph/TGTwoStepUtils.m \
../../Telegraph/TGTwoStepVerifyPasswordSignal.m \
../../Telegraph/TGUnseenPeerMentionsMessageIdsState.m \
../../Telegraph/TGUnseenPeerMentionsState.m \
../../Telegraph/TGUpdate.m \
../../Telegraph/TGUpdateAppController.m \
../../Telegraph/TGUpdateAppInfo.m \
../../Telegraph/TGUpdateAppInfoItem.m \
../../Telegraph/TGUpdateAppInfoItemView.m \
../../Telegraph/TGUpdateConfigActor.m \
../../Telegraph/TGUpdateMediaHistoryActor.m \
../../Telegraph/TGUpdateMessage.m \
../../Telegraph/TGUpdateMessageService.m \
../../Telegraph/TGUpdatePresenceActor.m \
../../Telegraph/TGUpdateStateRequestBuilder.mm \
../../Telegraph/TGUpdateUserStatusesActor.mm \
../../Telegraph/TGUpdatesWithDate.m \
../../Telegraph/TGUpdatesWithPts.m \
../../Telegraph/TGUpdatesWithQts.m \
../../Telegraph/TGUpdatesWithSeq.m \
../../Telegraph/TGUploadFileSignals.m \
../../Telegraph/TGUser+Telegraph.m \
../../Telegraph/TGUserAboutSetupController.m \
../../Telegraph/TGUserAvatarGalleryItem.m \
../../Telegraph/TGUserAvatarGalleryItemView.m \
../../Telegraph/TGUserAvatarGalleryModel.m \
../../Telegraph/TGUserCollectionItem.m \
../../Telegraph/TGUserCollectionItemView.m \
../../Telegraph/TGUserDataRequestBuilder.m \
../../Telegraph/TGUserDefaults.m \
../../Telegraph/TGUserInfoAddPhoneCollectionItem.m \
../../Telegraph/TGUserInfoAddPhoneCollectionItemView.m \
../../Telegraph/TGUserInfoAddressCollectionItem.m \
../../Telegraph/TGUserInfoAddressCollectionItemView.m \
../../Telegraph/TGUserInfoButtonCollectionItem.m \
../../Telegraph/TGUserInfoButtonCollectionItemView.m \
../../Telegraph/TGUserInfoCallsCollectionItem.m \
../../Telegraph/TGUserInfoCallsCollectionItemView.m \
../../Telegraph/TGUserInfoCollectionItem.m \
../../Telegraph/TGUserInfoCollectionItemView.m \
../../Telegraph/TGUserInfoController.m \
../../Telegraph/TGUserInfoEditingAboutCollectionItem.m \
../../Telegraph/TGUserInfoEditingAboutCollectionItemView.m \
../../Telegraph/TGUserInfoEditingPhoneCollectionItem.m \
../../Telegraph/TGUserInfoEditingPhoneCollectionItemView.m \
../../Telegraph/TGUserInfoEditingVariantCollectionItem.m \
../../Telegraph/TGUserInfoEditingVariantCollectionItemView.m \
../../Telegraph/TGUserInfoPhoneCollectionItem.m \
../../Telegraph/TGUserInfoPhoneCollectionItemView.m \
../../Telegraph/TGUserInfoTextCollectionItem.m \
../../Telegraph/TGUserInfoTextCollectionItemView.m \
../../Telegraph/TGUserInfoUsernameCollectionItem.m \
../../Telegraph/TGUserInfoUsernameCollectionItemView.m \
../../Telegraph/TGUserInfoVariantCollectionItem.m \
../../Telegraph/TGUserInfoVariantCollectionItemView.m \
../../Telegraph/TGUserListController.m \
../../Telegraph/TGUserNode.m \
../../Telegraph/TGUserSignal.m \
../../Telegraph/TGUsernameCollectionItemView.m \
../../Telegraph/TGUsernameController.m \
../../Telegraph/TGUsersSection.m \
../../Telegraph/TGVCard.m \
../../Telegraph/TGVCardUserInfoController.m \
../../Telegraph/TGVTAcceleratedVideoView.m \
../../Telegraph/TGVTPlayer.m \
../../Telegraph/TGVTPlayerView.m \
../../Telegraph/TGVariantCollectionItem.m \
../../Telegraph/TGVariantCollectionItemView.m
