libuofs5_FILES = ../../legacy/TL/TL/TLRPCcontacts_resetTopPeerRating.mm \
../../legacy/TL/TL/TLRPCcontacts_resolveUsername.mm \
../../legacy/TL/TL/TLRPCcontacts_search.mm \
../../legacy/TL/TL/TLRPCcontacts_sendRequest.mm \
../../legacy/TL/TL/TLRPCcontacts_unblock.mm \
../../legacy/TL/TL/TLRPCcontest_saveDeveloperInfo.mm \
../../legacy/TL/TL/TLRPCdestroy_session.mm \
../../legacy/TL/TL/TLRPCdestroy_sessions.mm \
../../legacy/TL/TL/TLRPCgeo_saveGeoPlace.mm \
../../legacy/TL/TL/TLRPCget_future_salts.mm \
../../legacy/TL/TL/TLRPChelp_getAppChangelog.mm \
../../legacy/TL/TL/TLRPChelp_getAppPrefs.mm \
../../legacy/TL/TL/TLRPChelp_getAppUpdate.mm \
../../legacy/TL/TL/TLRPChelp_getCdnConfig.mm \
../../legacy/TL/TL/TLRPChelp_getConfig.mm \
../../legacy/TL/TL/TLRPChelp_getInviteText.mm \
../../legacy/TL/TL/TLRPChelp_getNearestDc.mm \
../../legacy/TL/TL/TLRPChelp_getRecentMeUrls.mm \
../../legacy/TL/TL/TLRPChelp_getScheme.mm \
../../legacy/TL/TL/TLRPChelp_getSupport.mm \
../../legacy/TL/TL/TLRPChelp_saveNetworkStats.mm \
../../legacy/TL/TL/TLRPChelp_test.mm \
../../legacy/TL/TL/TLRPClangpack_getDifference.mm \
../../legacy/TL/TL/TLRPClangpack_getLangPack.mm \
../../legacy/TL/TL/TLRPClangpack_getLanguages.mm \
../../legacy/TL/TL/TLRPClangpack_getStrings.mm \
../../legacy/TL/TL/TLRPCmessages_acceptEncryption.mm \
../../legacy/TL/TL/TLRPCmessages_addChatUser.mm \
../../legacy/TL/TL/TLRPCmessages_checkChatInvite.mm \
../../legacy/TL/TL/TLRPCmessages_clearRecentStickers.mm \
../../legacy/TL/TL/TLRPCmessages_createChat.mm \
../../legacy/TL/TL/TLRPCmessages_deactivateChat.mm \
../../legacy/TL/TL/TLRPCmessages_deleteChatUser.mm \
../../legacy/TL/TL/TLRPCmessages_deleteHistory.mm \
../../legacy/TL/TL/TLRPCmessages_deleteMessages.mm \
../../legacy/TL/TL/TLRPCmessages_discardEncryption.mm \
../../legacy/TL/TL/TLRPCmessages_editChatAdmin.mm \
../../legacy/TL/TL/TLRPCmessages_editChatPhoto.mm \
../../legacy/TL/TL/TLRPCmessages_editChatTitle.mm \
../../legacy/TL/TL/TLRPCmessages_exportChatInvite.mm \
../../legacy/TL/TL/TLRPCmessages_faveSticker.mm \
../../legacy/TL/TL/TLRPCmessages_forwardMessagesMeta.mm \
../../legacy/TL/TL/TLRPCmessages_getAllChats.mm \
../../legacy/TL/TL/TLRPCmessages_getAllDrafts.mm \
../../legacy/TL/TL/TLRPCmessages_getAllStickers.mm \
../../legacy/TL/TL/TLRPCmessages_getArchivedStickers.mm \
../../legacy/TL/TL/TLRPCmessages_getAttachedStickers.mm \
../../legacy/TL/TL/TLRPCmessages_getChats.mm \
../../legacy/TL/TL/TLRPCmessages_getCommonChats.mm \
../../legacy/TL/TL/TLRPCmessages_getDhConfig.mm \
../../legacy/TL/TL/TLRPCmessages_getDialogsMeta.mm \
../../legacy/TL/TL/TLRPCmessages_getDocumentByHash.mm \
../../legacy/TL/TL/TLRPCmessages_getFavedStickers.mm \
../../legacy/TL/TL/TLRPCmessages_getFeaturedStickers.mm \
../../legacy/TL/TL/TLRPCmessages_getFullChat.mm \
../../legacy/TL/TL/TLRPCmessages_getHistory.mm \
../../legacy/TL/TL/TLRPCmessages_getMaskStickers.mm \
../../legacy/TL/TL/TLRPCmessages_getMessageEditData.mm \
../../legacy/TL/TL/TLRPCmessages_getMessages.mm \
../../legacy/TL/TL/TLRPCmessages_getMessagesViews.mm \
../../legacy/TL/TL/TLRPCmessages_getPeerDialogs.mm \
../../legacy/TL/TL/TLRPCmessages_getPeerSettings.mm \
../../legacy/TL/TL/TLRPCmessages_getPinnedDialogs.mm \
../../legacy/TL/TL/TLRPCmessages_getRecentLocations.mm \
../../legacy/TL/TL/TLRPCmessages_getRecentStickers.mm \
../../legacy/TL/TL/TLRPCmessages_getSavedGifs.mm \
../../legacy/TL/TL/TLRPCmessages_getStickerSet.mm \
../../legacy/TL/TL/TLRPCmessages_getStickers.mm \
../../legacy/TL/TL/TLRPCmessages_getUnreadMentions.mm \
../../legacy/TL/TL/TLRPCmessages_getUnusedStickers.mm \
../../legacy/TL/TL/TLRPCmessages_getWebPage.mm \
../../legacy/TL/TL/TLRPCmessages_getWebPagePreview.mm \
../../legacy/TL/TL/TLRPCmessages_hideReportSpam.mm \
../../legacy/TL/TL/TLRPCmessages_importChatInvite.mm \
../../legacy/TL/TL/TLRPCmessages_installStickerSet.mm \
../../legacy/TL/TL/TLRPCmessages_migrateChat.mm \
../../legacy/TL/TL/TLRPCmessages_readEncryptedHistory.mm \
../../legacy/TL/TL/TLRPCmessages_readFeaturedStickers.mm \
../../legacy/TL/TL/TLRPCmessages_readHistory.mm \
../../legacy/TL/TL/TLRPCmessages_readMentions.mm \
../../legacy/TL/TL/TLRPCmessages_readMessageContents.mm \
../../legacy/TL/TL/TLRPCmessages_receivedMessages.mm \
../../legacy/TL/TL/TLRPCmessages_receivedQueue.mm \
../../legacy/TL/TL/TLRPCmessages_reorderPinnedDialogs.mm \
../../legacy/TL/TL/TLRPCmessages_reorderStickerSets.mm \
../../legacy/TL/TL/TLRPCmessages_reportEncryptedSpam.mm \
../../legacy/TL/TL/TLRPCmessages_reportSpam.mm \
../../legacy/TL/TL/TLRPCmessages_requestEncryption.mm \
../../legacy/TL/TL/TLRPCmessages_restoreMessages.mm \
../../legacy/TL/TL/TLRPCmessages_saveGif.mm \
../../legacy/TL/TL/TLRPCmessages_saveRecentSticker.mm \
../../legacy/TL/TL/TLRPCmessages_searchGifs.mm \
../../legacy/TL/TL/TLRPCmessages_searchGlobal.mm \
../../legacy/TL/TL/TLRPCmessages_sendBroadcast.mm \
../../legacy/TL/TL/TLRPCmessages_sendEncrypted.mm \
../../legacy/TL/TL/TLRPCmessages_sendEncryptedFile.mm \
../../legacy/TL/TL/TLRPCmessages_sendEncryptedService.mm \
../../legacy/TL/TL/TLRPCmessages_sendScreenshotNotification.mm \
../../legacy/TL/TL/TLRPCmessages_setEncryptedTyping.mm \
../../legacy/TL/TL/TLRPCmessages_setTyping.mm \
../../legacy/TL/TL/TLRPCmessages_startBot.mm \
../../legacy/TL/TL/TLRPCmessages_toggleChatAdmins.mm \
../../legacy/TL/TL/TLRPCmessages_toggleDialogPin.mm \
../../legacy/TL/TL/TLRPCmessages_uninstallStickerSet.mm \
../../legacy/TL/TL/TLRPCmessages_uploadMedia.mm \
../../legacy/TL/TL/TLRPCpayments_clearSavedInfo.mm \
../../legacy/TL/TL/TLRPCpayments_getPaymentForm.mm \
../../legacy/TL/TL/TLRPCpayments_getPaymentReceipt.mm \
../../legacy/TL/TL/TLRPCpayments_getSavedInfo.mm \
../../legacy/TL/TL/TLRPCpayments_validateRequestedInfo.mm \
../../legacy/TL/TL/TLRPCphone_acceptCall.mm \
../../legacy/TL/TL/TLRPCphone_confirmCall.mm \
../../legacy/TL/TL/TLRPCphone_declineCall.mm \
../../legacy/TL/TL/TLRPCphone_discardCall.mm \
../../legacy/TL/TL/TLRPCphone_getCallConfig.mm \
../../legacy/TL/TL/TLRPCphone_getDhConfig.mm \
../../legacy/TL/TL/TLRPCphone_receivedCall.mm \
../../legacy/TL/TL/TLRPCphone_requestCall.mm \
../../legacy/TL/TL/TLRPCphone_saveCallDebug.mm \
../../legacy/TL/TL/TLRPCphone_setCallRating.mm \
../../legacy/TL/TL/TLRPCphotos_deletePhotos.mm \
../../legacy/TL/TL/TLRPCphotos_editPhoto.mm \
../../legacy/TL/TL/TLRPCphotos_getPhotos.mm \
../../legacy/TL/TL/TLRPCphotos_getUserPhotos.mm \
../../legacy/TL/TL/TLRPCphotos_getWall.mm \
../../legacy/TL/TL/TLRPCphotos_readWall.mm \
../../legacy/TL/TL/TLRPCphotos_restorePhotos.mm \
../../legacy/TL/TL/TLRPCphotos_updateProfilePhoto.mm \
../../legacy/TL/TL/TLRPCphotos_uploadPhoto.mm \
../../legacy/TL/TL/TLRPCphotos_uploadProfilePhoto.mm \
../../legacy/TL/TL/TLRPCping.mm \
../../legacy/TL/TL/TLRPCping_delay_disconnect.mm \
../../legacy/TL/TL/TLRPCreq_DH_params.mm \
../../legacy/TL/TL/TLRPCreq_pq.mm \
../../legacy/TL/TL/TLRPCrpc_drop_answer.mm \
../../legacy/TL/TL/TLRPCset_client_DH_params.mm \
../../legacy/TL/TL/TLRPCupdates_getChannelDifference.mm \
../../legacy/TL/TL/TLRPCupdates_getDifference.mm \
../../legacy/TL/TL/TLRPCupdates_getState.mm \
../../legacy/TL/TL/TLRPCupdates_subscribe.mm \
../../legacy/TL/TL/TLRPCupdates_unsubscribe.mm \
../../legacy/TL/TL/TLRPCupload_getCdnFile.mm \
../../legacy/TL/TL/TLRPCupload_getCdnFileHashes.mm \
../../legacy/TL/TL/TLRPCupload_getFile.mm \
../../legacy/TL/TL/TLRPCupload_getWebFile.mm \
../../legacy/TL/TL/TLRPCupload_reuploadCdnFile.mm \
../../legacy/TL/TL/TLRPCupload_saveBigFilePart.mm \
../../legacy/TL/TL/TLRPCupload_saveFilePart.mm \
../../legacy/TL/TL/TLRPCusers_getFullUser.mm \
../../legacy/TL/TL/TLRPCusers_getUsers.mm \
../../legacy/TL/TL/TLReceivedNotifyMessage.mm \
../../legacy/TL/TL/TLReplyMarkup.mm \
../../legacy/TL/TL/TLReportReason.mm \
../../legacy/TL/TL/TLResPQ.mm \
../../legacy/TL/TL/TLResponseIndirect.mm \
../../legacy/TL/TL/TLRichText.mm \
../../legacy/TL/TL/TLRpcDropAnswer.mm \
../../legacy/TL/TL/TLRpcError.mm \
../../legacy/TL/TL/TLScheme.mm \
../../legacy/TL/TL/TLSchemeMethod.mm \
../../legacy/TL/TL/TLSchemeParam.mm \
../../legacy/TL/TL/TLSchemeType.mm \
../../legacy/TL/TL/TLSecureCredentialsEncrypted.mm \
../../legacy/TL/TL/TLSecureData.mm \
../../legacy/TL/TL/TLSecureFile.mm \
../../legacy/TL/TL/TLSecurePasswordKdfAlgo.mm \
../../legacy/TL/TL/TLSecurePlainData.mm \
../../legacy/TL/TL/TLSecureRequiredType.mm \
../../legacy/TL/TL/TLSecureSecretSettings.mm \
../../legacy/TL/TL/TLSecureValue.mm \
../../legacy/TL/TL/TLSecureValueError.mm \
../../legacy/TL/TL/TLSecureValueHash.mm \
../../legacy/TL/TL/TLSecureValueType.mm \
../../legacy/TL/TL/TLSendMessageAction.mm \
../../legacy/TL/TL/TLServer_DH_Params.mm \
../../legacy/TL/TL/TLServer_DH_inner_data.mm \
../../legacy/TL/TL/TLSet_client_DH_params_answer.mm \
../../legacy/TL/TL/TLShippingOption.mm \
../../legacy/TL/TL/TLStickerPack.mm \
../../legacy/TL/TL/TLStickerSet.mm \
../../legacy/TL/TL/TLStickerSetCovered.mm \
../../legacy/TL/TL/TLTopPeer.mm \
../../legacy/TL/TL/TLTopPeerCategory.mm \
../../legacy/TL/TL/TLTopPeerCategoryPeers.mm \
../../legacy/TL/TL/TLUpdate.mm \
../../legacy/TL/TL/TLUpdates.mm \
../../legacy/TL/TL/TLUser.mm \
../../legacy/TL/TL/TLUserFull.mm \
../../legacy/TL/TL/TLUserProfilePhoto.mm \
../../legacy/TL/TL/TLUserStatus.mm \
../../legacy/TL/TL/TLWallPaper.mm \
../../legacy/TL/TL/TLWebAuthorization.mm \
../../legacy/TL/TL/TLWebDocument.mm \
../../legacy/TL/TL/TLWebPage.mm \
../../legacy/TL/TL/TLaccount_AuthorizationForm.mm \
../../legacy/TL/TL/TLaccount_Authorizations.mm \
../../legacy/TL/TL/TLaccount_Password.mm \
../../legacy/TL/TL/TLaccount_PasswordInputSettings.mm \
../../legacy/TL/TL/TLaccount_PasswordSettings.mm \
../../legacy/TL/TL/TLaccount_PrivacyRules.mm \
../../legacy/TL/TL/TLaccount_SentEmailCode.mm \
../../legacy/TL/TL/TLaccount_TmpPassword.mm \
../../legacy/TL/TL/TLaccount_WebAuthorizations.mm \
../../legacy/TL/TL/TLauth_Authorization.mm \
../../legacy/TL/TL/TLauth_CheckedPhone.mm \
../../legacy/TL/TL/TLauth_CodeType.mm \
../../legacy/TL/TL/TLauth_ExportedAuthorization.mm \
../../legacy/TL/TL/TLauth_PasswordRecovery.mm \
../../legacy/TL/TL/TLauth_SentCode.mm \
../../legacy/TL/TL/TLauth_SentCodeType.mm \
../../legacy/TL/TL/TLchannels_AdminLogResults.mm \
../../legacy/TL/TL/TLchannels_ChannelParticipant.mm \
../../legacy/TL/TL/TLchannels_ChannelParticipants.mm \
../../legacy/TL/TL/TLchannels_FeedSources.mm \
../../legacy/TL/TL/TLcontacts_Blocked.mm \
../../legacy/TL/TL/TLcontacts_Contacts.mm \
../../legacy/TL/TL/TLcontacts_ForeignLink.mm \
../../legacy/TL/TL/TLcontacts_Found.mm \
../../legacy/TL/TL/TLcontacts_ImportedContacts.mm \
../../legacy/TL/TL/TLcontacts_Link.mm \
../../legacy/TL/TL/TLcontacts_Located.mm \
../../legacy/TL/TL/TLcontacts_MyLink.mm \
../../legacy/TL/TL/TLcontacts_Requests.mm \
../../legacy/TL/TL/TLcontacts_ResolvedPeer.mm \
../../legacy/TL/TL/TLcontacts_SentLink.mm \
../../legacy/TL/TL/TLcontacts_Suggested.mm \
../../legacy/TL/TL/TLcontacts_TopPeers.mm \
../../legacy/TL/TL/TLhelp_AppChangelog.mm \
../../legacy/TL/TL/TLhelp_AppPrefs.mm \
../../legacy/TL/TL/TLhelp_AppUpdate.mm \
../../legacy/TL/TL/TLhelp_DeepLinkInfo.mm \
../../legacy/TL/TL/TLhelp_InviteText.mm \
../../legacy/TL/TL/TLhelp_PassportConfig.mm \
../../legacy/TL/TL/TLhelp_Support.mm \
../../legacy/TL/TL/TLhelp_TermsOfService.mm \
../../legacy/TL/TL/TLhelp_TermsOfServiceUpdate.mm \
../../legacy/TL/TL/TLmessages_AffectedHistory.mm \
../../legacy/TL/TL/TLmessages_AffectedMessages.mm \
../../legacy/TL/TL/TLmessages_AllStickers.mm \
../../legacy/TL/TL/TLmessages_ArchivedStickers.mm \
../../legacy/TL/TL/TLmessages_BotCallbackAnswer.mm \
../../legacy/TL/TL/TLmessages_BotResults.mm \
../../legacy/TL/TL/TLmessages_Chat.mm \
../../legacy/TL/TL/TLmessages_ChatFull.mm \
../../legacy/TL/TL/TLmessages_Chats.mm \
../../legacy/TL/TL/TLmessages_DhConfig.mm \
../../legacy/TL/TL/TLmessages_Dialogs.mm \
../../legacy/TL/TL/TLmessages_FavedStickers.mm \
../../legacy/TL/TL/TLmessages_FeaturedStickers.mm \
../../legacy/TL/TL/TLmessages_FeedMessages.mm \
../../legacy/TL/TL/TLmessages_FoundGifs.mm \
../../legacy/TL/TL/TLmessages_FoundStickerSets.mm \
../../legacy/TL/TL/TLmessages_HighScores.mm \
../../legacy/TL/TL/TLmessages_Message.mm \
../../legacy/TL/TL/TLmessages_MessageEditData.mm \
../../legacy/TL/TL/TLmessages_Messages.mm \
../../legacy/TL/TL/TLmessages_PeerDialogs.mm \
../../legacy/TL/TL/TLmessages_RecentStickers.mm \
../../legacy/TL/TL/TLmessages_SavedGifs.mm \
../../legacy/TL/TL/TLmessages_SentEncryptedMessage.mm \
../../legacy/TL/TL/TLmessages_StickerSet.mm \
../../legacy/TL/TL/TLmessages_StickerSetInstallResult.mm \
../../legacy/TL/TL/TLmessages_Stickers.mm \
../../legacy/TL/TL/TLpayments_PaymentForm.mm \
../../legacy/TL/TL/TLpayments_PaymentReceipt.mm \
../../legacy/TL/TL/TLpayments_PaymentResult.mm \
../../legacy/TL/TL/TLpayments_SavedInfo.mm \
../../legacy/TL/TL/TLpayments_ValidatedRequestedInfo.mm \
../../legacy/TL/TL/TLphone_DhConfig.mm \
../../legacy/TL/TL/TLphone_DiscardedCall.mm \
../../legacy/TL/TL/TLphone_PhoneCall.mm \
../../legacy/TL/TL/TLphotos_Photo.mm \
../../legacy/TL/TL/TLphotos_Photos.mm \
../../legacy/TL/TL/TLstorage_FileType.mm \
../../legacy/TL/TL/TLupdates_ChannelDifference.mm \
../../legacy/TL/TL/TLupdates_Difference.mm \
../../legacy/TL/TL/TLupdates_State.mm \
../../legacy/TL/TL/TLupload_CdnFile.mm \
../../legacy/TL/TL/TLupload_File.mm \
../../legacy/TL/TL/TLupload_WebFile.mm \
../../legacy/TL/TLBool.m \
../../legacy/TL/TLCompressedObject.mm \
../../legacy/TL/TLDestroySessionsRes_manual.mm \
../../legacy/TL/TLFutureSalts.mm \
../../legacy/TL/TLMessageContainer.mm \
../../legacy/TL/TLMetaConstructor.mm \
../../legacy/TL/TLMetaObject.mm \
../../legacy/TL/TLMetaRpc.mm \
../../legacy/TL/TLMetaType.mm \
../../legacy/TL/TLMsgsAck_msgs_ack_manual.m \
../../legacy/TL/TLObject.mm \
../../legacy/TL/TLRPCmessages_sendMedia_manual.mm \
../../legacy/TL/TLRPCmessages_sendMessage_manual.mm \
../../legacy/TL/TLResPQ_resPQ_manual.m \
../../legacy/TL/TLRpcResult.mm \
../../legacy/TL/TLSerializationContext.m \
../../legacy/TL/TLUpdate_updateChangePts.m \
../../legacy/TL/TLaccount_PasswordInputSettings_manual.mm \
../../legacy/TelegraphKit/TGAcceptEncryptionFutureAction.m \
../../legacy/TelegraphKit/TGActionTableView.m \
../../legacy/TelegraphKit/TGAlertView.m \
../../legacy/TelegraphKit/TGAudioInfo.m \
../../legacy/TelegraphKit/TGButton.m \
../../legacy/TelegraphKit/TGButtonGroupView.m \
../../legacy/TelegraphKit/TGChangeNotificationSettingsFutureAction.m \
../../legacy/TelegraphKit/TGChangePasslockSettingsFutureAction.m \
../../legacy/TelegraphKit/TGChangePeerBlockStatusFutureAction.m \
../../legacy/TelegraphKit/TGChangePrivacySettingsFutureAction.m \
../../legacy/TelegraphKit/TGCircularProgressView.m \
../../legacy/TelegraphKit/TGClearNotificationsFutureAction.m \
../../legacy/TelegraphKit/TGCommon.m \
../../legacy/TelegraphKit/TGContactBinding.m \
../../legacy/TelegraphKit/TGDatabase.mm \
../../legacy/TelegraphKit/TGDateLabel.m \
../../legacy/TelegraphKit/TGDeleteProfilePhotoFutureAction.m \
../../legacy/TelegraphKit/TGDialogListBroadcastsMenuCell.m \
../../legacy/TelegraphKit/TGDialogListCell.m \
../../legacy/TelegraphKit/TGDialogListCompanion.m \
../../legacy/TelegraphKit/TGDialogListController.mm \
../../legacy/TelegraphKit/TGDialogListMessageSearchCell.m \
../../legacy/TelegraphKit/TGDialogListSearchCell.m \
../../legacy/TelegraphKit/TGDownloadManager.mm \
../../legacy/TelegraphKit/TGEncryptedChatServiceAction.m \
../../legacy/TelegraphKit/TGExportContactFutureAction.m \
../../legacy/TelegraphKit/TGFutureAction.m \
../../legacy/TelegraphKit/TGHighlightableButton.m \
../../legacy/TelegraphKit/TGImageTransitionHelper.m \
../../legacy/TelegraphKit/TGIndexSet.mm \
../../legacy/TelegraphKit/TGLinearProgressView.m \
../../legacy/TelegraphKit/TGMimeTypeMap.m \
../../legacy/TelegraphKit/TGPagerView.m \
../../legacy/TelegraphKit/TGPhonebookContact.mm \
../../legacy/TelegraphKit/TGRemoveContactFutureAction.m \
../../legacy/TelegraphKit/TGReusableLabel.mm \
../../legacy/TelegraphKit/TGSharedPtrWrapper.mm \
../../legacy/TelegraphKit/TGSwitchView.m \
../../legacy/TelegraphKit/TGSynchronizeEncryptedChatSettingsFutureAction.m \
../../legacy/TelegraphKit/TGTableView.m \
../../legacy/TelegraphKit/TGTableViewCell.m \
../../legacy/TelegraphKit/TGToolbar.m \
../../legacy/TelegraphKit/TGTransitionableImageView.m \
../../legacy/TelegraphKit/TGUpdatePeerLayerFutureAction.m \
../../legacy/TelegraphKit/TGUploadAvatarFutureAction.m \
../../legacy/TelegraphKit/TGView.m \
../../legacy/TelegraphKit/TelegraphKit.m \
../../legacy/TelegraphKit/Third-Party/FMDB/FMDatabase.m \
../../legacy/TelegraphKit/Third-Party/FMDB/FMDatabaseAdditions.m \
../../legacy/TelegraphKit/Third-Party/FMDB/FMResultSet.m \
../../legacy/TelegraphKit/UIImage+ImageEffects.m \
../../thirdparty/RMIntro/core/animations.c \
../../thirdparty/RMIntro/core/buffer.c \
../../thirdparty/RMIntro/core/objects.c \
../../thirdparty/RMIntro/core/program.c \
../../thirdparty/RMIntro/core/rngs.c \
../../thirdparty/RMIntro/core/shader.c \
../../thirdparty/RMIntro/core/timing.c \
../../thirdparty/RMIntro/platform/common/platform_log.c \
../../thirdparty/RMIntro/platform/ios/RMGeometry.m \
../../thirdparty/RMIntro/platform/ios/RMIntroPageView.m \
../../thirdparty/RMIntro/platform/ios/RMIntroViewController.m \
../../thirdparty/RMIntro/platform/ios/texture_helper.m \
../../thirdparty/Reachability.m \
../../thirdparty/Stripe/NSArray+Stripe_BoundSafe.m \
../../thirdparty/Stripe/NSBundle+Stripe_AppName.m \
../../thirdparty/Stripe/NSDecimalNumber+Stripe_Currency.m \
../../thirdparty/Stripe/NSDictionary+Stripe.m \
../../thirdparty/Stripe/NSMutableURLRequest+Stripe.m \
../../thirdparty/Stripe/NSString+Stripe.m \
../../thirdparty/Stripe/NSString+Stripe_CardBrands.m \
../../thirdparty/Stripe/PKPayment+Stripe.m \
../../thirdparty/Stripe/PKPaymentAuthorizationViewController+Stripe_Blocks.m \
../../thirdparty/Stripe/STPAPIClient+ApplePay.m \
../../thirdparty/Stripe/STPAPIClient.m \
../../thirdparty/Stripe/STPAPIPostRequest.m \
../../thirdparty/Stripe/STPAddCardViewController.m \
../../thirdparty/Stripe/STPAddress.m \
../../thirdparty/Stripe/STPAddressFieldTableViewCell.m \
../../thirdparty/Stripe/STPAddressViewModel.m \
../../thirdparty/Stripe/STPAnalyticsClient.m \
../../thirdparty/Stripe/STPApplePayPaymentMethod.m \
../../thirdparty/Stripe/STPAspects.m \
../../thirdparty/Stripe/STPBINRange.m \
../../thirdparty/Stripe/STPBankAccount.m \
../../thirdparty/Stripe/STPBankAccountParams.m \
../../thirdparty/Stripe/STPBundleLocator.m \
../../thirdparty/Stripe/STPCard.m \
../../thirdparty/Stripe/STPCardParams.m \
../../thirdparty/Stripe/STPCardTuple.m \
../../thirdparty/Stripe/STPCardValidator.m \
../../thirdparty/Stripe/STPCategoryLoader.m \
../../thirdparty/Stripe/STPCheckoutAPIClient.m \
../../thirdparty/Stripe/STPCheckoutAPIVerification.m \
../../thirdparty/Stripe/STPCheckoutAccount.m \
../../thirdparty/Stripe/STPCheckoutAccountLookup.m \
../../thirdparty/Stripe/STPCheckoutBootstrapResponse.m \
../../thirdparty/Stripe/STPColorUtils.m \
../../thirdparty/Stripe/STPCustomer.m \
../../thirdparty/Stripe/STPDelegateProxy.m \
../../thirdparty/Stripe/STPDispatchFunctions.m \
../../thirdparty/Stripe/STPEmailAddressValidator.m \
../../thirdparty/Stripe/STPFormEncoder.m \
../../thirdparty/Stripe/STPFormTextField.m \
../../thirdparty/Stripe/STPImageLibrary.m \
../../thirdparty/Stripe/STPLocalizationUtils.m \
../../thirdparty/Stripe/STPObscuredCardView.m \
../../thirdparty/Stripe/STPPaymentActivityIndicatorView.m \
../../thirdparty/Stripe/STPPaymentCardTextField.m \
../../thirdparty/Stripe/STPPaymentCardTextFieldViewModel.m \
../../thirdparty/Stripe/STPPaymentConfiguration.m \
../../thirdparty/Stripe/STPPaymentContext.m \
../../thirdparty/Stripe/STPPaymentContextAmountModel.m \
../../thirdparty/Stripe/STPPaymentMethodTableViewCell.m \
../../thirdparty/Stripe/STPPaymentMethodTuple.m \
../../thirdparty/Stripe/STPPaymentMethodsInternalViewController.m \
../../thirdparty/Stripe/STPPaymentMethodsViewController.m \
../../thirdparty/Stripe/STPPaymentResult.m \
../../thirdparty/Stripe/STPPhoneNumberValidator.m \
../../thirdparty/Stripe/STPPostalCodeValidator.m \
../../thirdparty/Stripe/STPPromise.m \
../../thirdparty/Stripe/STPRememberMeEmailCell.m \
../../thirdparty/Stripe/STPRememberMePaymentCell.m \
../../thirdparty/Stripe/STPRememberMeTermsView.m \
../../thirdparty/Stripe/STPSMSCodeTextField.m \
../../thirdparty/Stripe/STPSMSCodeViewController.m \
../../thirdparty/Stripe/STPStringUtils.m \
../../thirdparty/Stripe/STPSwitchTableViewCell.m \
../../thirdparty/Stripe/STPTheme.m \
../../thirdparty/Stripe/STPToken.m \
../../thirdparty/Stripe/STPUserInformation.m \
../../thirdparty/Stripe/STPWebViewController.m \
../../thirdparty/Stripe/StripeError.m \
../../thirdparty/Stripe/UIBarButtonItem+Stripe.m \
../../thirdparty/Stripe/UINavigationBar+Stripe_Theme.m \
../../thirdparty/Stripe/UINavigationController+Stripe_Completion.m \
../../thirdparty/Stripe/UITableViewCell+Stripe_Borders.m \
../../thirdparty/Stripe/UIToolbar+Stripe_InputAccessory.m \
../../thirdparty/Stripe/UIView+Stripe_FirstResponder.m \
../../thirdparty/UIImage+WebP.m \
../../thirdparty/VideoEncoder/MP4Atom.m \
../../thirdparty/lz4/lz4.c \
../../thirdparty/lz4/lz4frame.c \
../../thirdparty/lz4/lz4hc.c \
../../thirdparty/lz4/xxhash.c \
../../thirdparty/sqlcipher/sqlite3.c
