libuofs5_FILES = ../../legacy/TL/TL/TLRPCcontacts_resetTopPeerRating.m \
../../legacy/TL/TL/TLRPCcontacts_resolveUsername.m \
../../legacy/TL/TL/TLRPCcontacts_search.m \
../../legacy/TL/TL/TLRPCcontacts_sendRequest.m \
../../legacy/TL/TL/TLRPCcontacts_unblock.m \
../../legacy/TL/TL/TLRPCcontest_saveDeveloperInfo.m \
../../legacy/TL/TL/TLRPCdestroy_session.m \
../../legacy/TL/TL/TLRPCdestroy_sessions.m \
../../legacy/TL/TL/TLRPCgeo_saveGeoPlace.m \
../../legacy/TL/TL/TLRPCget_future_salts.m \
../../legacy/TL/TL/TLRPChelp_getAppChangelog.m \
../../legacy/TL/TL/TLRPChelp_getAppPrefs.m \
../../legacy/TL/TL/TLRPChelp_getAppUpdate.m \
../../legacy/TL/TL/TLRPChelp_getCdnConfig.m \
../../legacy/TL/TL/TLRPChelp_getConfig.m \
../../legacy/TL/TL/TLRPChelp_getInviteText.m \
../../legacy/TL/TL/TLRPChelp_getNearestDc.m \
../../legacy/TL/TL/TLRPChelp_getRecentMeUrls.m \
../../legacy/TL/TL/TLRPChelp_getScheme.m \
../../legacy/TL/TL/TLRPChelp_getSupport.m \
../../legacy/TL/TL/TLRPChelp_saveNetworkStats.m \
../../legacy/TL/TL/TLRPChelp_test.m \
../../legacy/TL/TL/TLRPClangpack_getDifference.m \
../../legacy/TL/TL/TLRPClangpack_getLangPack.m \
../../legacy/TL/TL/TLRPClangpack_getLanguages.m \
../../legacy/TL/TL/TLRPClangpack_getStrings.m \
../../legacy/TL/TL/TLRPCmessages_acceptEncryption.m \
../../legacy/TL/TL/TLRPCmessages_addChatUser.m \
../../legacy/TL/TL/TLRPCmessages_checkChatInvite.m \
../../legacy/TL/TL/TLRPCmessages_clearRecentStickers.m \
../../legacy/TL/TL/TLRPCmessages_createChat.m \
../../legacy/TL/TL/TLRPCmessages_deactivateChat.m \
../../legacy/TL/TL/TLRPCmessages_deleteChatUser.m \
../../legacy/TL/TL/TLRPCmessages_deleteHistory.m \
../../legacy/TL/TL/TLRPCmessages_deleteMessages.m \
../../legacy/TL/TL/TLRPCmessages_discardEncryption.m \
../../legacy/TL/TL/TLRPCmessages_editChatAdmin.m \
../../legacy/TL/TL/TLRPCmessages_editChatPhoto.m \
../../legacy/TL/TL/TLRPCmessages_editChatTitle.m \
../../legacy/TL/TL/TLRPCmessages_exportChatInvite.m \
../../legacy/TL/TL/TLRPCmessages_faveSticker.m \
../../legacy/TL/TL/TLRPCmessages_forwardMessagesMeta.m \
../../legacy/TL/TL/TLRPCmessages_getAllChats.m \
../../legacy/TL/TL/TLRPCmessages_getAllDrafts.m \
../../legacy/TL/TL/TLRPCmessages_getAllStickers.m \
../../legacy/TL/TL/TLRPCmessages_getArchivedStickers.m \
../../legacy/TL/TL/TLRPCmessages_getAttachedStickers.m \
../../legacy/TL/TL/TLRPCmessages_getChats.m \
../../legacy/TL/TL/TLRPCmessages_getCommonChats.m \
../../legacy/TL/TL/TLRPCmessages_getDhConfig.m \
../../legacy/TL/TL/TLRPCmessages_getDialogsMeta.m \
../../legacy/TL/TL/TLRPCmessages_getDocumentByHash.m \
../../legacy/TL/TL/TLRPCmessages_getFavedStickers.m \
../../legacy/TL/TL/TLRPCmessages_getFeaturedStickers.m \
../../legacy/TL/TL/TLRPCmessages_getFullChat.m \
../../legacy/TL/TL/TLRPCmessages_getHistory.m \
../../legacy/TL/TL/TLRPCmessages_getMaskStickers.m \
../../legacy/TL/TL/TLRPCmessages_getMessageEditData.m \
../../legacy/TL/TL/TLRPCmessages_getMessages.m \
../../legacy/TL/TL/TLRPCmessages_getMessagesViews.m \
../../legacy/TL/TL/TLRPCmessages_getPeerDialogs.m \
../../legacy/TL/TL/TLRPCmessages_getPeerSettings.m \
../../legacy/TL/TL/TLRPCmessages_getPinnedDialogs.m \
../../legacy/TL/TL/TLRPCmessages_getRecentLocations.m \
../../legacy/TL/TL/TLRPCmessages_getRecentStickers.m \
../../legacy/TL/TL/TLRPCmessages_getSavedGifs.m \
../../legacy/TL/TL/TLRPCmessages_getStickerSet.m \
../../legacy/TL/TL/TLRPCmessages_getStickers.m \
../../legacy/TL/TL/TLRPCmessages_getUnreadMentions.m \
../../legacy/TL/TL/TLRPCmessages_getUnusedStickers.m \
../../legacy/TL/TL/TLRPCmessages_getWebPage.m \
../../legacy/TL/TL/TLRPCmessages_getWebPagePreview.m \
../../legacy/TL/TL/TLRPCmessages_hideReportSpam.m \
../../legacy/TL/TL/TLRPCmessages_importChatInvite.m \
../../legacy/TL/TL/TLRPCmessages_installStickerSet.m \
../../legacy/TL/TL/TLRPCmessages_migrateChat.m \
../../legacy/TL/TL/TLRPCmessages_readEncryptedHistory.m \
../../legacy/TL/TL/TLRPCmessages_readFeaturedStickers.m \
../../legacy/TL/TL/TLRPCmessages_readHistory.m \
../../legacy/TL/TL/TLRPCmessages_readMentions.m \
../../legacy/TL/TL/TLRPCmessages_readMessageContents.m \
../../legacy/TL/TL/TLRPCmessages_receivedMessages.m \
../../legacy/TL/TL/TLRPCmessages_receivedQueue.m \
../../legacy/TL/TL/TLRPCmessages_reorderPinnedDialogs.m \
../../legacy/TL/TL/TLRPCmessages_reorderStickerSets.m \
../../legacy/TL/TL/TLRPCmessages_reportEncryptedSpam.m \
../../legacy/TL/TL/TLRPCmessages_reportSpam.m \
../../legacy/TL/TL/TLRPCmessages_requestEncryption.m \
../../legacy/TL/TL/TLRPCmessages_restoreMessages.m \
../../legacy/TL/TL/TLRPCmessages_saveGif.m \
../../legacy/TL/TL/TLRPCmessages_saveRecentSticker.m \
../../legacy/TL/TL/TLRPCmessages_searchGifs.m \
../../legacy/TL/TL/TLRPCmessages_searchGlobal.m \
../../legacy/TL/TL/TLRPCmessages_sendBroadcast.m \
../../legacy/TL/TL/TLRPCmessages_sendEncrypted.m \
../../legacy/TL/TL/TLRPCmessages_sendEncryptedFile.m \
../../legacy/TL/TL/TLRPCmessages_sendEncryptedService.m \
../../legacy/TL/TL/TLRPCmessages_sendScreenshotNotification.m \
../../legacy/TL/TL/TLRPCmessages_setEncryptedTyping.m \
../../legacy/TL/TL/TLRPCmessages_setTyping.m \
../../legacy/TL/TL/TLRPCmessages_startBot.m \
../../legacy/TL/TL/TLRPCmessages_toggleChatAdmins.m \
../../legacy/TL/TL/TLRPCmessages_toggleDialogPin.m \
../../legacy/TL/TL/TLRPCmessages_uninstallStickerSet.m \
../../legacy/TL/TL/TLRPCmessages_uploadMedia.m \
../../legacy/TL/TL/TLRPCpayments_clearSavedInfo.m \
../../legacy/TL/TL/TLRPCpayments_getPaymentForm.m \
../../legacy/TL/TL/TLRPCpayments_getPaymentReceipt.m \
../../legacy/TL/TL/TLRPCpayments_getSavedInfo.m \
../../legacy/TL/TL/TLRPCpayments_validateRequestedInfo.m \
../../legacy/TL/TL/TLRPCphone_acceptCall.m \
../../legacy/TL/TL/TLRPCphone_confirmCall.m \
../../legacy/TL/TL/TLRPCphone_declineCall.m \
../../legacy/TL/TL/TLRPCphone_discardCall.m \
../../legacy/TL/TL/TLRPCphone_getCallConfig.m \
../../legacy/TL/TL/TLRPCphone_getDhConfig.m \
../../legacy/TL/TL/TLRPCphone_receivedCall.m \
../../legacy/TL/TL/TLRPCphone_requestCall.m \
../../legacy/TL/TL/TLRPCphone_saveCallDebug.m \
../../legacy/TL/TL/TLRPCphone_setCallRating.m \
../../legacy/TL/TL/TLRPCphotos_deletePhotos.m \
../../legacy/TL/TL/TLRPCphotos_editPhoto.m \
../../legacy/TL/TL/TLRPCphotos_getPhotos.m \
../../legacy/TL/TL/TLRPCphotos_getUserPhotos.m \
../../legacy/TL/TL/TLRPCphotos_getWall.m \
../../legacy/TL/TL/TLRPCphotos_readWall.m \
../../legacy/TL/TL/TLRPCphotos_restorePhotos.m \
../../legacy/TL/TL/TLRPCphotos_updateProfilePhoto.m \
../../legacy/TL/TL/TLRPCphotos_uploadPhoto.m \
../../legacy/TL/TL/TLRPCphotos_uploadProfilePhoto.m \
../../legacy/TL/TL/TLRPCping.m \
../../legacy/TL/TL/TLRPCping_delay_disconnect.m \
../../legacy/TL/TL/TLRPCreq_DH_params.m \
../../legacy/TL/TL/TLRPCreq_pq.m \
../../legacy/TL/TL/TLRPCrpc_drop_answer.m \
../../legacy/TL/TL/TLRPCset_client_DH_params.m \
../../legacy/TL/TL/TLRPCupdates_getChannelDifference.m \
../../legacy/TL/TL/TLRPCupdates_getDifference.m \
../../legacy/TL/TL/TLRPCupdates_getState.m \
../../legacy/TL/TL/TLRPCupdates_subscribe.m \
../../legacy/TL/TL/TLRPCupdates_unsubscribe.m \
../../legacy/TL/TL/TLRPCupload_getCdnFile.m \
../../legacy/TL/TL/TLRPCupload_getCdnFileHashes.m \
../../legacy/TL/TL/TLRPCupload_getFile.m \
../../legacy/TL/TL/TLRPCupload_getWebFile.m \
../../legacy/TL/TL/TLRPCupload_reuploadCdnFile.m \
../../legacy/TL/TL/TLRPCupload_saveBigFilePart.m \
../../legacy/TL/TL/TLRPCupload_saveFilePart.m \
../../legacy/TL/TL/TLRPCusers_getFullUser.m \
../../legacy/TL/TL/TLRPCusers_getUsers.m \
../../legacy/TL/TL/TLReceivedNotifyMessage.m \
../../legacy/TL/TL/TLReplyMarkup.m \
../../legacy/TL/TL/TLReportReason.m \
../../legacy/TL/TL/TLResPQ.m \
../../legacy/TL/TL/TLResponseIndirect.m \
../../legacy/TL/TL/TLRichText.m \
../../legacy/TL/TL/TLRpcDropAnswer.m \
../../legacy/TL/TL/TLRpcError.m \
../../legacy/TL/TL/TLScheme.m \
../../legacy/TL/TL/TLSchemeMethod.m \
../../legacy/TL/TL/TLSchemeParam.m \
../../legacy/TL/TL/TLSchemeType.m \
../../legacy/TL/TL/TLSecureCredentialsEncrypted.m \
../../legacy/TL/TL/TLSecureData.m \
../../legacy/TL/TL/TLSecureFile.m \
../../legacy/TL/TL/TLSecurePasswordKdfAlgo.m \
../../legacy/TL/TL/TLSecurePlainData.m \
../../legacy/TL/TL/TLSecureRequiredType.m \
../../legacy/TL/TL/TLSecureSecretSettings.m \
../../legacy/TL/TL/TLSecureValue.m \
../../legacy/TL/TL/TLSecureValueError.m \
../../legacy/TL/TL/TLSecureValueHash.m \
../../legacy/TL/TL/TLSecureValueType.m \
../../legacy/TL/TL/TLSendMessageAction.m \
../../legacy/TL/TL/TLServer_DH_Params.m \
../../legacy/TL/TL/TLServer_DH_inner_data.m \
../../legacy/TL/TL/TLSet_client_DH_params_answer.m \
../../legacy/TL/TL/TLShippingOption.m \
../../legacy/TL/TL/TLStickerPack.m \
../../legacy/TL/TL/TLStickerSet.m \
../../legacy/TL/TL/TLStickerSetCovered.m \
../../legacy/TL/TL/TLTopPeer.m \
../../legacy/TL/TL/TLTopPeerCategory.m \
../../legacy/TL/TL/TLTopPeerCategoryPeers.m \
../../legacy/TL/TL/TLUpdate.m \
../../legacy/TL/TL/TLUpdates.m \
../../legacy/TL/TL/TLUser.m \
../../legacy/TL/TL/TLUserFull.m \
../../legacy/TL/TL/TLUserProfilePhoto.m \
../../legacy/TL/TL/TLUserStatus.m \
../../legacy/TL/TL/TLWallPaper.m \
../../legacy/TL/TL/TLWebAuthorization.m \
../../legacy/TL/TL/TLWebDocument.m \
../../legacy/TL/TL/TLWebPage.m \
../../legacy/TL/TL/TLaccount_AuthorizationForm.m \
../../legacy/TL/TL/TLaccount_Authorizations.m \
../../legacy/TL/TL/TLaccount_Password.m \
../../legacy/TL/TL/TLaccount_PasswordInputSettings.m \
../../legacy/TL/TL/TLaccount_PasswordSettings.m \
../../legacy/TL/TL/TLaccount_PrivacyRules.m \
../../legacy/TL/TL/TLaccount_SentEmailCode.m \
../../legacy/TL/TL/TLaccount_TmpPassword.m \
../../legacy/TL/TL/TLaccount_WebAuthorizations.m \
../../legacy/TL/TL/TLauth_Authorization.m \
../../legacy/TL/TL/TLauth_CheckedPhone.m \
../../legacy/TL/TL/TLauth_CodeType.m \
../../legacy/TL/TL/TLauth_ExportedAuthorization.m \
../../legacy/TL/TL/TLauth_PasswordRecovery.m \
../../legacy/TL/TL/TLauth_SentCode.m \
../../legacy/TL/TL/TLauth_SentCodeType.m \
../../legacy/TL/TL/TLchannels_AdminLogResults.m \
../../legacy/TL/TL/TLchannels_ChannelParticipant.m \
../../legacy/TL/TL/TLchannels_ChannelParticipants.m \
../../legacy/TL/TL/TLchannels_FeedSources.m \
../../legacy/TL/TL/TLcontacts_Blocked.m \
../../legacy/TL/TL/TLcontacts_Contacts.m \
../../legacy/TL/TL/TLcontacts_ForeignLink.m \
../../legacy/TL/TL/TLcontacts_Found.m \
../../legacy/TL/TL/TLcontacts_ImportedContacts.m \
../../legacy/TL/TL/TLcontacts_Link.m \
../../legacy/TL/TL/TLcontacts_Located.m \
../../legacy/TL/TL/TLcontacts_MyLink.m \
../../legacy/TL/TL/TLcontacts_Requests.m \
../../legacy/TL/TL/TLcontacts_ResolvedPeer.m \
../../legacy/TL/TL/TLcontacts_SentLink.m \
../../legacy/TL/TL/TLcontacts_Suggested.m \
../../legacy/TL/TL/TLcontacts_TopPeers.m \
../../legacy/TL/TL/TLhelp_AppChangelog.m \
../../legacy/TL/TL/TLhelp_AppPrefs.m \
../../legacy/TL/TL/TLhelp_AppUpdate.m \
../../legacy/TL/TL/TLhelp_DeepLinkInfo.m \
../../legacy/TL/TL/TLhelp_InviteText.m \
../../legacy/TL/TL/TLhelp_PassportConfig.m \
../../legacy/TL/TL/TLhelp_Support.m \
../../legacy/TL/TL/TLhelp_TermsOfService.m \
../../legacy/TL/TL/TLhelp_TermsOfServiceUpdate.m \
../../legacy/TL/TL/TLmessages_AffectedHistory.m \
../../legacy/TL/TL/TLmessages_AffectedMessages.m \
../../legacy/TL/TL/TLmessages_AllStickers.m \
../../legacy/TL/TL/TLmessages_ArchivedStickers.m \
../../legacy/TL/TL/TLmessages_BotCallbackAnswer.m \
../../legacy/TL/TL/TLmessages_BotResults.m \
../../legacy/TL/TL/TLmessages_Chat.m \
../../legacy/TL/TL/TLmessages_ChatFull.m \
../../legacy/TL/TL/TLmessages_Chats.m \
../../legacy/TL/TL/TLmessages_DhConfig.m \
../../legacy/TL/TL/TLmessages_Dialogs.m \
../../legacy/TL/TL/TLmessages_FavedStickers.m \
../../legacy/TL/TL/TLmessages_FeaturedStickers.m \
../../legacy/TL/TL/TLmessages_FeedMessages.m \
../../legacy/TL/TL/TLmessages_FoundGifs.m \
../../legacy/TL/TL/TLmessages_FoundStickerSets.m \
../../legacy/TL/TL/TLmessages_HighScores.m \
../../legacy/TL/TL/TLmessages_Message.m \
../../legacy/TL/TL/TLmessages_MessageEditData.m \
../../legacy/TL/TL/TLmessages_Messages.m \
../../legacy/TL/TL/TLmessages_PeerDialogs.m \
../../legacy/TL/TL/TLmessages_RecentStickers.m \
../../legacy/TL/TL/TLmessages_SavedGifs.m \
../../legacy/TL/TL/TLmessages_SentEncryptedMessage.m \
../../legacy/TL/TL/TLmessages_StickerSet.m \
../../legacy/TL/TL/TLmessages_StickerSetInstallResult.m \
../../legacy/TL/TL/TLmessages_Stickers.m \
../../legacy/TL/TL/TLpayments_PaymentForm.m \
../../legacy/TL/TL/TLpayments_PaymentReceipt.m \
../../legacy/TL/TL/TLpayments_PaymentResult.m \
../../legacy/TL/TL/TLpayments_SavedInfo.m \
../../legacy/TL/TL/TLpayments_ValidatedRequestedInfo.m \
../../legacy/TL/TL/TLphone_DhConfig.m \
../../legacy/TL/TL/TLphone_DiscardedCall.m \
../../legacy/TL/TL/TLphone_PhoneCall.m \
../../legacy/TL/TL/TLphotos_Photo.m \
../../legacy/TL/TL/TLphotos_Photos.m \
../../legacy/TL/TL/TLstorage_FileType.m \
../../legacy/TL/TL/TLupdates_ChannelDifference.m \
../../legacy/TL/TL/TLupdates_Difference.m \
../../legacy/TL/TL/TLupdates_State.m \
../../legacy/TL/TL/TLupload_CdnFile.m \
../../legacy/TL/TL/TLupload_File.m \
../../legacy/TL/TL/TLupload_WebFile.m \
../../legacy/TL/TLBool.m \
../../legacy/TL/TLCompressedObject.m \
../../legacy/TL/TLDestroySessionsRes_manual.m \
../../legacy/TL/TLFutureSalts.m \
../../legacy/TL/TLMessageContainer.m \
../../legacy/TL/TLMetaConstructor.m \
../../legacy/TL/TLMetaObject.m \
../../legacy/TL/TLMetaRpc.m \
../../legacy/TL/TLMetaType.m \
../../legacy/TL/TLMsgsAck_msgs_ack_manual.m \
../../legacy/TL/TLObject.m \
../../legacy/TL/TLRPCmessages_sendMedia_manual.m \
../../legacy/TL/TLRPCmessages_sendMessage_manual.m \
../../legacy/TL/TLResPQ_resPQ_manual.m \
../../legacy/TL/TLRpcResult.m \
../../legacy/TL/TLSerializationContext.m \
../../legacy/TL/TLUpdate_updateChangePts.m \
../../legacy/TL/TLaccount_PasswordInputSettings_manual.m \
../../legacy/TelegraphKit/TGAcceptEncryptionFutureAction.m \
../../legacy/TelegraphKit/TGActionTableView.m \
../../legacy/TelegraphKit/TGAlertView.m \
../../legacy/TelegraphKit/TGAudioInfo.m \
../../legacy/TelegraphKit/TGButton.m \
../../legacy/TelegraphKit/TGButtonGroupView.m \
../../legacy/TelegraphKit/TGChangeNotificationSettingsFutureAction.m \
../../legacy/TelegraphKit/TGChangePasslockSettingsFutureAction.m \
../../legacy/TelegraphKit/TGChangePeerBlockStatusFutureAction.m \
../../legacy/TelegraphKit/TGChangePrivacySettingsFutureAction.m \
../../legacy/TelegraphKit/TGCircularProgressView.m \
../../legacy/TelegraphKit/TGClearNotificationsFutureAction.m \
../../legacy/TelegraphKit/TGCommon.m \
../../legacy/TelegraphKit/TGContactBinding.m \
../../legacy/TelegraphKit/TGDatabase.m \
../../legacy/TelegraphKit/TGDateLabel.m \
../../legacy/TelegraphKit/TGDeleteProfilePhotoFutureAction.m \
../../legacy/TelegraphKit/TGDialogListBroadcastsMenuCell.m \
../../legacy/TelegraphKit/TGDialogListCell.m \
../../legacy/TelegraphKit/TGDialogListCompanion.m \
../../legacy/TelegraphKit/TGDialogListController.m \
../../legacy/TelegraphKit/TGDialogListMessageSearchCell.m \
../../legacy/TelegraphKit/TGDialogListSearchCell.m \
../../legacy/TelegraphKit/TGDownloadManager.m \
../../legacy/TelegraphKit/TGEncryptedChatServiceAction.m \
../../legacy/TelegraphKit/TGExportContactFutureAction.m \
../../legacy/TelegraphKit/TGFutureAction.m \
../../legacy/TelegraphKit/TGHighlightableButton.m \
../../legacy/TelegraphKit/TGImageTransitionHelper.m \
../../legacy/TelegraphKit/TGIndexSet.m \
../../legacy/TelegraphKit/TGLinearProgressView.m \
../../legacy/TelegraphKit/TGMimeTypeMap.m \
../../legacy/TelegraphKit/TGPagerView.m \
../../legacy/TelegraphKit/TGPhonebookContact.m \
../../legacy/TelegraphKit/TGRemoveContactFutureAction.m \
../../legacy/TelegraphKit/TGReusableLabel.m \
../../legacy/TelegraphKit/TGSharedPtrWrapper.m \
../../legacy/TelegraphKit/TGSwitchView.m \
../../legacy/TelegraphKit/TGSynchronizeEncryptedChatSettingsFutureAction.m \
../../legacy/TelegraphKit/TGTableView.m \
../../legacy/TelegraphKit/TGTableViewCell.m \
../../legacy/TelegraphKit/TGToolbar.m \
../../legacy/TelegraphKit/TGTransitionableImageView.m \
../../legacy/TelegraphKit/TGUpdatePeerLayerFutureAction.m \
../../legacy/TelegraphKit/TGUploadAvatarFutureAction.m \
../../legacy/TelegraphKit/TGView.m \
../../legacy/TelegraphKit/TelegraphKit.m \
../../legacy/TelegraphKit/Third-Party/FMDB/FMDatabase.m \
../../legacy/TelegraphKit/Third-Party/FMDB/FMDatabaseAdditions.m \
../../legacy/TelegraphKit/Third-Party/FMDB/FMResultSet.m \
../../legacy/TelegraphKit/UIImage+ImageEffects.m \
../../thirdparty/RMIntro/core/animations.c \
../../thirdparty/RMIntro/core/buffer.c \
../../thirdparty/RMIntro/core/objects.c \
../../thirdparty/RMIntro/core/program.c \
../../thirdparty/RMIntro/core/rngs.c \
../../thirdparty/RMIntro/core/shader.c \
../../thirdparty/RMIntro/core/timing.c \
../../thirdparty/RMIntro/platform/common/platform_log.c \
../../thirdparty/RMIntro/platform/ios/RMGeometry.m \
../../thirdparty/RMIntro/platform/ios/RMIntroPageView.m \
../../thirdparty/RMIntro/platform/ios/RMIntroViewController.m \
../../thirdparty/RMIntro/platform/ios/texture_helper.m \
../../thirdparty/Reachability.m \
../../thirdparty/Stripe/NSArray+Stripe_BoundSafe.m \
../../thirdparty/Stripe/NSBundle+Stripe_AppName.m \
../../thirdparty/Stripe/NSDecimalNumber+Stripe_Currency.m \
../../thirdparty/Stripe/NSDictionary+Stripe.m \
../../thirdparty/Stripe/NSMutableURLRequest+Stripe.m \
../../thirdparty/Stripe/NSString+Stripe.m \
../../thirdparty/Stripe/NSString+Stripe_CardBrands.m \
../../thirdparty/Stripe/PKPayment+Stripe.m \
../../thirdparty/Stripe/PKPaymentAuthorizationViewController+Stripe_Blocks.m \
../../thirdparty/Stripe/STPAPIClient+ApplePay.m \
../../thirdparty/Stripe/STPAPIClient.m \
../../thirdparty/Stripe/STPAPIPostRequest.m \
../../thirdparty/Stripe/STPAddCardViewController.m \
../../thirdparty/Stripe/STPAddress.m \
../../thirdparty/Stripe/STPAddressFieldTableViewCell.m \
../../thirdparty/Stripe/STPAddressViewModel.m \
../../thirdparty/Stripe/STPAnalyticsClient.m \
../../thirdparty/Stripe/STPApplePayPaymentMethod.m \
../../thirdparty/Stripe/STPAspects.m \
../../thirdparty/Stripe/STPBINRange.m \
../../thirdparty/Stripe/STPBankAccount.m \
../../thirdparty/Stripe/STPBankAccountParams.m \
../../thirdparty/Stripe/STPBundleLocator.m \
../../thirdparty/Stripe/STPCard.m \
../../thirdparty/Stripe/STPCardParams.m \
../../thirdparty/Stripe/STPCardTuple.m \
../../thirdparty/Stripe/STPCardValidator.m \
../../thirdparty/Stripe/STPCategoryLoader.m \
../../thirdparty/Stripe/STPCheckoutAPIClient.m \
../../thirdparty/Stripe/STPCheckoutAPIVerification.m \
../../thirdparty/Stripe/STPCheckoutAccount.m \
../../thirdparty/Stripe/STPCheckoutAccountLookup.m \
../../thirdparty/Stripe/STPCheckoutBootstrapResponse.m \
../../thirdparty/Stripe/STPColorUtils.m \
../../thirdparty/Stripe/STPCustomer.m \
../../thirdparty/Stripe/STPDelegateProxy.m \
../../thirdparty/Stripe/STPDispatchFunctions.m \
../../thirdparty/Stripe/STPEmailAddressValidator.m \
../../thirdparty/Stripe/STPFormEncoder.m \
../../thirdparty/Stripe/STPFormTextField.m \
../../thirdparty/Stripe/STPImageLibrary.m \
../../thirdparty/Stripe/STPLocalizationUtils.m \
../../thirdparty/Stripe/STPObscuredCardView.m \
../../thirdparty/Stripe/STPPaymentActivityIndicatorView.m \
../../thirdparty/Stripe/STPPaymentCardTextField.m \
../../thirdparty/Stripe/STPPaymentCardTextFieldViewModel.m \
../../thirdparty/Stripe/STPPaymentConfiguration.m \
../../thirdparty/Stripe/STPPaymentContext.m \
../../thirdparty/Stripe/STPPaymentContextAmountModel.m \
../../thirdparty/Stripe/STPPaymentMethodTableViewCell.m \
../../thirdparty/Stripe/STPPaymentMethodTuple.m \
../../thirdparty/Stripe/STPPaymentMethodsInternalViewController.m \
../../thirdparty/Stripe/STPPaymentMethodsViewController.m \
../../thirdparty/Stripe/STPPaymentResult.m \
../../thirdparty/Stripe/STPPhoneNumberValidator.m \
../../thirdparty/Stripe/STPPostalCodeValidator.m \
../../thirdparty/Stripe/STPPromise.m \
../../thirdparty/Stripe/STPRememberMeEmailCell.m \
../../thirdparty/Stripe/STPRememberMePaymentCell.m \
../../thirdparty/Stripe/STPRememberMeTermsView.m \
../../thirdparty/Stripe/STPSMSCodeTextField.m \
../../thirdparty/Stripe/STPSMSCodeViewController.m \
../../thirdparty/Stripe/STPStringUtils.m \
../../thirdparty/Stripe/STPSwitchTableViewCell.m \
../../thirdparty/Stripe/STPTheme.m \
../../thirdparty/Stripe/STPToken.m \
../../thirdparty/Stripe/STPUserInformation.m \
../../thirdparty/Stripe/STPWebViewController.m \
../../thirdparty/Stripe/StripeError.m \
../../thirdparty/Stripe/UIBarButtonItem+Stripe.m \
../../thirdparty/Stripe/UINavigationBar+Stripe_Theme.m \
../../thirdparty/Stripe/UINavigationController+Stripe_Completion.m \
../../thirdparty/Stripe/UITableViewCell+Stripe_Borders.m \
../../thirdparty/Stripe/UIToolbar+Stripe_InputAccessory.m \
../../thirdparty/Stripe/UIView+Stripe_FirstResponder.m \
../../thirdparty/UIImage+WebP.m \
../../thirdparty/VideoEncoder/MP4Atom.m \
../../thirdparty/lz4/lz4.c \
../../thirdparty/lz4/lz4frame.c \
../../thirdparty/lz4/lz4hc.c \
../../thirdparty/lz4/xxhash.c \
../../thirdparty/sqlcipher/sqlite3.c
